const zhCN = {
  public: {
    never: '绝不',
    center: '居中',
    login: '登录',
    email: '邮箱',
    seen: '查看',
    name: '名称',
    can: '能',
    username: '用户名',
    editUser: '编辑用户',
    create: '创建',
    dashboard: '仪表板',
    dashboards: '仪表板',
    folder: '文件夹',
    import: '导入',
    export: '导出',
    srpFrame: 'SRP-Frame',
    newSrpFrame: '新建SRP-Frame',
    newUser: '新用户',
    addNewUser: '添加新用户',
    exportCsv: '导出CSV',
    excelCSVDialect: 'Excel CSV 本地',
    toggleLegend: '切换图例',
    text: '文本',
    text_: '文本',
    manage: '管理',
    home: '首页',
    none: '毫无',
    exact: '精确的',
    divider: '分隔符',
    playlists: '播放列表',
    snapshots: '快照',
    explore: '探索',
    admin: '管理员',
    preferences: '偏好设置',
    password: '密码',
    changePassword: '修改密码',
    signOut: '登出',
    alerting: '告警',
    alert: '告警',
    alertRules: '告警规则',
    notificationChanels: '通知方式',
    configuration: '配置',
    datasources: '数据源',
    users: '用户',
    team: '团队',
    teams: '团队',
    plugins: '插件',
    images: '图片',
    apiKeys: 'API 密钥',
    orgSetting: '组织设置',
    serverAdmin: '服务管理员',
    org: '组织',
    orgs: '组织',
    settings: '设置',
    stats: '统计',
    orgsexport: '组织导出',
    orgsImport: '组织导入',
    help: '帮助',
    changelog: '版本更新记录',
    apiDoc: 'API 文档',
    technicalDoc: '技术文挡',
    applicationDemo: '应用示例',
    platformUrl: '论坛',
    timeRange: '时间范围',
    saveDashboard: '保存仪表板',
    duplicatePanel: '复制面板',
    duplicateCard: '复制卡片',
    remove: '移除',
    removePanel: '移除面板',
    addDatasource: '添加数据源',
    select: '选择',
    test: '测试',
    delete: '删除',
    deleteUser: '删除用户',
    back: '返回',
    userName: '用户名',
    save: '保存',
    uiTheme: 'UI 主题',
    dark: '黑色',
    gray: '灰色',
    light: '白色',
    default: '默认',
    disabled: '禁用',
    utc: '世界标准时间',
    homeDashboard: '主页仪表板',
    homeSrpFrame: '主页 SRP Frame',
    timezone: '时区',
    organizations: '组织',
    newOrg: '新建组织',
    id: 'Id',
    newOrganization: '新建组织',
    orgName: '组织名称',
    value: '值',
    value_: '值',
    exportDash: '导出仪表板',
    exportDatasouce: '导出数据源',
    exportSRPFrames: '导出SRP Frames',
    exportImages: '导出图片',
    exportPreferences: '导出偏好',
    exportFile: '导出组织文件',
    browse: '浏览',
    user: '用户',
    reset: '重置',
    invite: '邀请',
    inviteUser: '邀请用户',
    loginUser: '登录者',
    role: '角色',
    current: '当前',
    currentOrg: '当前组织:',
    sessions: '会话',
    lastSeen: '最后上线',
    loggedOn: '登录',
    ipAddress: 'IP 地址',
    browserAndOs: '浏览器和操作系统',
    switchTo: '切换',
    newChannel: '新建途径',
    type: '类型',
    Type: '输入',
    management: '管理',
    permissions: '权限',
    systemConfigure: '系统配置',
    newLanguage: '新建语言',
    language: '语言',
    sysLanguage: '系统语言',
    edit: '编辑',
    general: '基本的',
    logo: '图标',
    title: '标题',
    icon: '图标',
    cancel: '取消',
    sendTest: '发送测试',
    newDashboard: '新建仪表板',
    newPanel: '新建面板',
    addQuery: '添加查询',
    addPanel: '添加面板',
    to: '到',
    customTimeRange: '自定义时间范围',
    refreshDashboard: '刷新仪表板',
    conflict: '冲突',
    saveOverwrite: '保存并覆盖',
    update: '更新',
    searchMember: '搜索团队',
    addMember: '添加成员',
    members: '成员',
    permission: '许可',
    yes: '是',
    no: '否',
    dashboardSettings: '仪表板设置',
    file: '文件',
    fileProgress: '进度',
    close: '关闭',
    overwrite: '覆盖',
    error: '错误',
    uploader: '上传者',
    prePage: '上一页',
    nextPage: '下一页',
    confirm: '确定',
    warn: '警告',
    upload: '上传',
    path: '路径',
    orgProfile: '组织概况',
    add: '添加',
    unsavedChanges: '未保存的更改',
    doYouSaveYourChanges: '您想保存更改吗?',
    discard: '丢弃',
    newPlaylist: '新建播放列表',
    interval: '间隔',
    addDaashboards: '添加仪表板',
    starred: '收藏',
    Starred: '星标',
    tags: '标签',
    view: '查看',
    load: '加载',
    enable: '使能',
    refresh: '刷新',
    api: '请求接口',
    visible: '可见',
    accumulative: '累加',
    link: '链接',
    limit: '限制',
    last: '历时',
    main: '主页',
    right: '右侧',
    left: '左侧',
    defaultLanguage: '默认语言',
    theme: '主题',
    sideMenu: '侧边菜单',
    addPermission: '添加权限',
    addPermissionFor: '添加权限',
    style: '样式',
    links: '链接',
    JsonModel: 'Json Model',
    variable: '变量',
    variables: '变量',
    search: '搜索',
    newFolder: '新建文件夹',
    importDashboard: '导入仪表板',
    importFolder: '导入文件夹',
    target: '目标',
    folderImportSetting: '文件夹导入设置',
    clear: '清除',
    filterBy: '过滤',
    filter: '过滤',
    move: '移动',
    treeMenu: '树形菜单',
    annotations: '注释',
    new: '新建',
    queryName: '查询名称',
    dataSource: '数据源',
    enabled: '启用',
    hidden: '隐藏',
    color: '颜色',
    query: '查询',
    versions: '版本',
    notFound: '未找到',
    saveAs: '另存为',
    description: '描述',
    addTags: '添加标签',
    editable: '可编辑的',
    deleteDashboard: '删除仪表板',
    all: '所有',
    selected: '选中',
    selectedAll: '全选',
    selectedDefault: '默认选中',
    selectedColor: '选中颜色',
    change: '改变',
    importOverwrite: '导入(覆盖)',
    publishedBy: '发布者',
    options: '选项',
    importFormDashboard: '从Json文件导入仪表板',
    info: '信息',
    url: '网址',
    tooltip: '提示信息',
    openInNewTab: ' 新标签页中打开',
    saveChanges: '保存变化',
    savecurrentTimeRange: '保存当前时间范围',
    version: '版本',
    date: '日期',
    updatedBy: '更新者',
    notes: '注释',
    restore: '恢复',
    latest: '最新的',
    comparing: '比较',
    duplicate: '副本',
    definition: '定义',
    option: '选项',
    label: '标签',
    hide: '隐藏',
    values: '值',
    intervalOptions: '时间间隔选项',
    uptate: '更新',
    defaultValue: '默认值',
    regex: '正则表达式',
    sort: '排序',
    example: '例如',
    addOption: '添加选项',
    tags_: '标签',
    line: '行',
    characters: '字符',
    saving: '保存中',
    shareDashboard: '分享 仪表板',
    share: '分享',
    more: '更多',
    inspect: '检查',
    snapshot: '快照',
    report: '报表',
    copy: '复制',
    timeout: '超时',
    seconds: '秒',
    copyToClipboard: '复制到剪贴板',
    enter: '进入',
    backToDashboard: '返回仪表板',
    resetDashboard: '重置仪表板',
    axes: '坐标轴',
    leftY: '左Y轴',
    rightY: '右Y轴',
    show: '显示',
    unit: '单位',
    scale: '比例',
    auto: '自动',
    decimals: '小数位数',
    mode: '模式',
    align: '对齐',
    level: '级别',
    legend: '图例',
    width: '宽度',
    oddColor: '奇数行颜色',
    evenColor: '偶数行颜色',
    min: '最小值',
    max: '最大值',
    avg: '平均',
    total: '总数',
    from: '从',
    fromFolder: '源文件',
    targetFolder: '目标文件',
    To: '到',
    metric: '指标',
    URL: '网址',
    adjustableFontSize: '可调节字体大小',
    cardOpacity: '卡片透明度',
    cardOpacityTips: '透明度值在0.1-1之间，值越小越透明',
    fontWeight: '字体粗细',
    adjustableFontSizeTip: '字体大小跟随窗口大小调整',
    timeConversion: '时间转换',
    openTitleUseE: '您可以使用快捷方式e打开面板标题',
    field: '字段',
    fontSize: '字体大小',
    prefix: '前缀',
    postfix: '后缀',
    bold: '加粗',
    decimalLegendTooltip: '覆盖图例和提示的自动小数位数精度',
    decimalsTooltip: '覆盖轴的自动小数位数精度。',
    coloring: '配色',
    thresholds: '阈值',
    colors: '颜色',
    invert: '反转',
    background: '背景',
    YMin: 'Y轴最小值',
    YMax: 'Y轴最大值',
    lineColor: '线颜色',
    fillColor: '填充颜色',
    valueMappings: '值映射',
    YAxis: 'Y轴',
    buckets: '周期',
    size: '大小',
    XAxis: 'X轴',
    dataFormat: '数据格式',
    format: '格式化',
    display: '显示',
    scheme: '设计',
    space: '间隔',
    round: '圆角',
    histogram: '直方图',
    columns: '列',
    time: '时间',
    order: '顺序',
    addtags: '添加标签',
    scenario: '脚本',
    alias: '别名',
    labels: '标签',
    newValue: '新值',
    allValues: '所有值',
    customInterval: '自定义间隔',
    queries: '查询',
    visualization: '可视化',
    cards: '卡片',
    repeating: '重复',
    repeat: '重复',
    titleMargin: '标题边距',
    fontColor: '字体颜色',
    backgroundColor: '背景颜色',
    sidebarColor: '侧边栏颜色',
    scrollbarColor: '滚动条颜色',
    rule: '规则',
    for: '为了',
    timeFor: '持续',
    conditions: '条件',
    notifications: '通知',
    sendto: '发送到',
    message: '讯息',
    draggable: '可拖拽',
    height: '高度',
    imgHeight: '图片高度',
    item: 'item',
    titleColor: '标题颜色',
    valueColor: '值的颜色',
    metrics: '指标',
    logs: '日志',
    split: '分割',
    clearAll: '清除所有',
    runQuery: '运行查询',
    gobackEsc: '返回(Esc)',
    newName: '新建名称',
    copyTags: '复制标签',
    recentlyViewed: '最近浏览',
    fonts: '字体',
    titleQuery: '标题查询',
    maxItems: '最大项数',
    sortOrder: '排序顺序',
    forText: '为',
    data: '数据',
    Auto: '自动',
    scroll: '滚动',
    dateFormat: '日期格式',
    colorMode: '颜色模式',
    choose: '选择',
    base: '基数',
    addMapping: '添加映射',
    dataLinks: '数据链接',
    removePanelText: '您确定要移除此面板吗?',
    embed: '嵌入',
    addName: '添加名称',
    timeEnd: '结束时间',
    deprecated: '不推荐使用',
    groupBy: '分组',
    thenBy: '然后',
    script: '脚本',
    var: '变量',
    params: '参数',
    model: '模型',
    window: '窗口',
    service: '服务',
    subscription: '订阅',
    resourceGroup: '资源组',
    namespace: '名称空间',
    resourceName: '资源名称',
    aggregation: '聚合',
    top: '顶部',
    workspace: '工作区',
    showHelp: '显示帮助',
    rawQuery: '原始查询',
    anonymous: '匿名',
    patterns: `模式`,
    resolution: '分辨率',
    fill: '填充',
    filters: '过滤器',
    connection: '连接',
    host: '主机',
    database: '数据库',
    httpMode: 'HTTP 模式',
    formatAs: '格式',
    aliasBy: '别名',
    FROM: '从',
    GroupBy: '分组',
    orderBy: '订购',
    desc: '降序',
    Limit: '限制',
    tz: '时区',
    note: '注意',
    databaseName: '数据库名称',
    user_: '用户',
    details: '详情',
    switch: '切换',
    filterByNameOrType: '通过名称或类型来过滤',
    testing: '测试中...',
    unknownPlugin: '未知的插件',
    disable: '禁用',
    panel: '仪表板',
    datasource: '数据源',
    Changlog: '变更记录',
    log: '日志',
    loading: '正在加载',
    folderPermissions: '文件夹权限',
    confirmDelete: '确认删除',
    Enhanced: '增强版',
    ReportUpgrade: '加购报表',
    Upgrade: '升级版',
    Standard: '标准版',
    Professional: '专业版',
    Advanced: '高阶版',
    ProfessionalShared: '专业共享版',
    Lite: '精简版',
    ProfessionalWA: '专业版-WA',
    CustomizedV1: '定制版 V1',
    number: '数字',
    numbers: '数字',
    signature: '签名',
    signIn: '登录',
    failed: '失败的',
    doing: '进行中的',
    wait: '等待中的',
    download: '下载',
    state: '状态',
    success: '成功',
    timeLast: '过去',
    minute: '分钟',
    hour: '小时',
    day: '天',
    month: '月',
    months: '月',
    days: '天',
    hours: '小时',
    minutes: '分钟',
    CustomTimeRange: '自定义时间范围',
    defaultTimeRange: ' 默认时间范围',
    addTime: '添加自定义时间范围',
    margin: '边距',
    saveCurrentVariables: '保存当前变量',
    year: '年',
    second: '秒',
    setValueMappings: '设置值映射',
    addValueMapping: '添加一个值映射',
    setRangeMappings: '设置范围映射',
    addRangeMapping: '添加范围映射',
    panelJson: '面板 JSON',
    defaultCustom: '默认自定义',
    timeRangeCustom: '自定义时间范围',
    millisecond: '毫秒',
    milliseconds: '毫秒',
    productsComparison: '版本比较',
    superiorPlugins: '精品插件',
    subscribe: '订阅',
    pointSize: '点的大小',
    loginNamePlaceHolder: '邮箱或用户名',
    standardLogin: '标准',
    LDAPusername: 'LDAP用户名',
    emailTip: '请输入邮箱',
    pwdTip: '请输入密码',
    incorrectTip: '邮箱或密码错误',
    loginDesc: '登录到Dashboard',
    loginCloudDesc: '登录到在线Dashboard',
    alarm: '告警',
    audio: '音频',
    position: '位置',
    yearPrefix: '前缀为年份',
    alarmSource: '告警来源',
    alarmType: '告警类型',
    activate: '激活',
    activatePage: '激活并刷新此页面',
    preview: '预览',
    fixedFontSize: '固定字体大小',
    activateSuccess: '激活成功',
    activateFail: '激活失败',
    activated: '已激活',
    orgInitManagement: '组织初始化',
    uploadFile: '文件上传',
    deleteSuccess: '删除成功',
    deleteFail: '删除失败',
    previewLoginPage: '登录页预览',
    previewMmanufacturerIcon: '右上角出品方图标预览',
    noFileFound: '没有发现文件',
    noFileMatch: '未找到与您的查询匹配的文件.',
    overwriteSameName: '覆盖同名文件',
    synchronousOrgs: '一键同步',
    importToOrg: '组织同步',
    sureToOverwriteSameFile: '确定覆盖同名文件吗',
    jump: '跳过',
    findFileByName: '按名称查找文件',
    orgInitImport: '组织初始化同步',
    orgInitImportDesc: '将系统备份的组织初始化中的仪表板、数据源、SRP Frames、图片及偏好导入至这个新建的组织中',
    currentOrgExport: '当前组织导出',
    currentOrgImport: '当前组织导入',
    importOrg: '--请选择--',
    exportCurrentOrgFile: '导出当前组织文件',
    orgsExportDes: '此处为系统级的组织导出，请选择要导出的组织进行导出。',
    orgsImportDes: '此处为系统级的组织导入，请上传文件进行导入。',
    widthAdjust: '宽度自适应',
    week: '周',
    weeks: '周',
    nameCol: '名称列',
    valueCol: '数值列',
    enoughPanels: '面板数量已达最大',
  },

  expore: {
    dedup: '重复数据删除 ',
    noDedup: '没有重复数据删除',
    noDedupExact: '对相同行的连续行进行重复数据删除，忽略ISO日期时间。',
    noDedupNumbers: '忽略数字（例如IP地址，延迟）时相同的连续行的重复数据删除。',
    noDedupSignature: '具有相同标点符号和空格的连续行的重复数据删除。',
    noLogs: '找不到日志',
    scanOlderLog: '扫描较旧的日志',
    stopScan: '停止扫描',
    editModeBtn: '编辑模式按钮',
  },

  time: {
    now: '现在',
    timeOptions: '时间选项',
    autoRefresh: '自动刷新',
    nowDelayNow: '现在延迟-',
    hidetimePicker: '隐藏时间选择器',
    hidetimeRange: '隐藏时间范围',
    hideCustomRange: '隐藏自定义范围',
    hideRefreshing: '隐藏刷新',
    configQuickRanges: '配置快速范围',
    last5minutes: '过去5分钟',
    last15minutes: '过去15分钟',
    last30minutes: '过去30分钟',
    last1hour: '过去1小时',
    last3hour: '过去3小时',
    last6hour: '过去6小时',
    last12hour: '过去12小时',
    last24hour: '过去24小时',
    last2days: '过去2天',
    last7days: '过去7天',
    last30days: '过去30天',
    last90days: '过去90天',
    last6months: '过去6个月',
    last1year: '过去1年',
    last2year: '过去2年',
    last5year: '过去5年',
    yesterday: '昨天',
    daybeforeyesterday: '前天',
    thisdaylastweek: '上周的这一天',
    previousweek: '上周',
    previousmonth: '前一个月',
    previousyear: '前一年',
    today: '今天',
    todaysofar: '今天到现在为止',
    thisweek: '本周',
    thisweeksofar: '本周到现在为止',
    thismonth: '本月',
    thismonthsofar: '这个月到现在为止',
    thisyear: '今年',
    thisyearsofar: '今年到目前为止',
    customTimeFormat: '自定义显示格式',
    yesterday8hTotoday8h: '昨天8:00到今天8:00'
  },

  panelGeneral: {
    queryResult: '查询结果',
    addQuery: '添加查询',
    addExpression: '添加表达式',
    queryInspector: '查询检查器',
    querySetLabels: '使用key = value语法设置标签：',
    stringInput: '字符串输入',
    customIntervalTip: `值默认为空，会根据面板的显示大小自动调整间隔；也可以自定义数据查询间隔
    （单位支持ms，s，m，h，d，w，M，y，该数字可以自定义），例如1ms，2s，3m，4h，5d，6w，7M，8y ...`,
    relativeTime: '相对时间',
    hideTimeInfo: '隐藏时间信息',
    timeShift: '时间偏移',
    notValid: '无效的时间跨度',
    cacheTimeout: '缓存超时',
    cacheTimeoutTip: `如果您的时间序列存储区具有查询缓存，则此选项可以覆盖默认的缓存超时。 指定一个以秒为单位的数值。`,
    panelTransparent: '面板透明度',
    SelfAdaption: '自适应',
    descriptionPlaceholder: '面板描述, 支持markdown和链接',
    maxPerRow: '每行最大值',
    repeatNote: '注意：您可能需要更改变量选择才能看到实际效果',
    panelTitleStyle: '面板标题样式',
    hidePanelTitle: '隐藏面板标题',
    panelMarginTip: '请输入数字作为边框的宽度',
    panelTitleScheme: '面板标题方案',
    predefinedStyles: '预定义样式',
    fontGradient: '字体渐变',
    startGradientColor: '初始渐变颜色',
    endGradientColor: '结束渐变色',
    pillarColor: '柱子颜色',
    panelLinks: '面板链接',
    noAlertInfo: '面板未定义警报规则',
    createAlert: '创建警报',
    stateHistory: '状态历史',
    deleteAlert: '删除警报',
    deleteAlertTip1: '您确定要删除此警报规则吗？',
    deleteAlertTip2: '您需要保存dashboard后才能使删除生效',
    testRule: '测试规则',
    backQueries: '返回查询',
    notSupportedAlert: '警报查询不支持转换',
    noStateChange: '没有记录状态变化',
    collapseAll: '全部收缩',
    expandAll: '全部展开',
    evaluatingRule: '评估规则',
    copyToClipboard: '复制到剪贴板',
    deleteAlertHistory: '删除警报历史记录',
    deleteAlertHistoryText: '您确定要删除此警报的所有历史记录和注释吗？',
    clearHistory: '清除历史记录',
    last50Change: '最近50个状态更改',
    evaluateEvery: '评估频率',
    forTip: `如果警报规则已配置为持续，查询违反了配置的阈值，则它将首先从正常转到未决状态。从正常转到未决状态Dashboard将不会发送任何通知。 警报规则的触发时间超过“持续时间”后，它将更改为“告警”并发送告警通知`,
    noData: '无数据和错误处理',
    allNull: '如果没有数据或所有值都为空',
    setStateTo: '将状态设置为',
    stateError: '如果执行错误或超时',
    newTagName: '新标签名称...',
    newTagVal: '新标签值...',
    addTag: '添加标签',
    addCard: '添加卡片',
    noCardTitle: '面板未定义卡片规则',
    deleteCard: '删除卡片',
    sureDeleteCard: '您确定要删除此卡吗？',
    dataTag: '数据标签',
    dataShow: '数据显示',
    imgUrl: '图片链接',
    addCardItem: '添加卡片子项',
    PanleBackground: '面板背景',
    BackgroundImage: '背景图片',
    HorizontalPadding: '面板横向填充值',
    tip1: '请输入一个数组作为面板横向填充值',
    VerticalPadding: '面板纵向填充值',
    tip2: '请输入一个数组作为面板纵向填充值',
    TopPadding: '标题上部填充值',
    tip3: '请输入一个数组作为标题上部填充值',
    customTimeRange: '自定义时间区间',
    defaultTimeRange: '默认时间区间',
    addCustomTimeRange: '添加自定义时间区间',
    minute: '分钟',
    hour: '时间',
    day: '天',
    month: '月份',
    tableView: '查看数据表',
    PanelTimeRefresh: '面板时间刷新',
    PanelTime: '面板时间',
    PanelRefresh: '面板刷新',
    PanelTimeShow: '面板时间显示',
    PanelRefreshShow: '面板刷新显示',
    PanelTimeColor: '面板时间颜色',
    PanelRefreshColor: '面板刷新颜色',
    PanelRefreshTextColor: '面板刷新文字颜色',
    PanelTimeTextColor: '面板刷新时间颜色',
    PanelBgColor: "面板背景颜色",
    valueCol: '数值列',
    value: '数值',
    metricItem: '指标项',
    panelTimeVariable: '面板时间关联变量',
    PanelTimeRange: '前后时间范围'
  },

  permissions: {
    isPermissions: '什么是权限？',
    dashPermissions: `是指控制列表（ACL）模型用于限制对仪表板文件夹的访问。用户或团队可以为文件夹或单个仪表板分配的权限。`,
    loadPermissions: '正在载入权限...',
    noPersssions: '未设置权限,只能由管理员访问。',
    JsonModelDes: '下面的JSON是定义仪表板的数据结构。包括设置，面板设置和布局，查询等。',
    settingsView: '找不到设置页面',
    settingPageNotFound: '找不到设置页面，或者您没有访问权限',
    makeEditable: '使可编辑',
    defaultPer: '默认权限',
    viewEvery: '每个人都有查看的权限',
    editEvery: '每个人都有编辑的权限',
    canViewDash: '可以查看仪表板',
    canEditDash: '可以新建, 编辑和删除仪表板',
    canAdminDash: '可以新建或删除权限而且可以可以新建, 编辑和删除仪表板。',
  },

  variables: {
    onDashLoad: '仪表板加载完成',
    onTimeChange: '时间范围变更',
    refreshButEnabled: '刷新按钮可见',
    optionalDisplayName: '可选的显示名称',
    autoOption: '自动选项',
    varEmptyTitle: '还没有变量',
    addVariable: '添加变量',
    varEmptyInfo: ` <p>
            变量开启可以更好的和仪表板动态交互与互动. 您可以使用变量代替指标查询中对服务器或传感器名称的硬编码。
            变量在仪表板顶部显示为下拉选择框。通过这些下拉菜单很容易更改显示在仪表板上的数据. 参考
            <a class="external-link" href="http://docs.grafana.org/reference/templating/" target="_blank">
                模板文档
            </a>
            获取更多信息
            </p>`,
    varDo: '变量有什么作用？',
    stepcount: '步数',
    stepcountTip: '当前时间范围应划分多少次才能计算出值',
    minInterval: '最小时间间隔',
    minIntervalTip: '计算值不低于此阈值',
    valComma: '值用逗号分隔',
    selectionOptions: '选择选项',
    multiValue: '多选',
    multiValueTip: '启用同时选择多个值',
    includeAlloption: '包含所有选项',
    previewofvalues: '值预览',
    constantOptions: '常数选项',
    customOptionsTip: '您的指标前缀',
    customTypeDes: '手动定义变量值',
    textOptions: '文本选项',
    customOptions: '自定义选项',
    defaultVal: '默认值，如果有',
    queryOptions: '查询选项',
    variableUptateText: '何时更新此变量的值。',
    queryPlaceholder: '指标名称或标签查询',
    regexPlaceholder: '可选，如果要提取系列名称或度量标准节点段的一部分。',
    sortPlaceholder: '如何对这个变量的值进行排序。',
    dataOptions: '数据源选项',
    instanceNameFilter: '实例名称过滤器',
    instanceNameFilterTip: '正则表达式过滤器在变量值下拉列表中从中选择数据源实例。 留下所有空白。',
    dependentOptions: '相关选项',
    dependentVar: '相关变量',
    addOption: '添加选项',
    variableItem: '变量子项',
    variableText: '变量文本',
    variableVal: '变量值',
    queryDes: '从数据源查询中获取变量值',
    queryValueGroup: '值组/标签（实验功能）',
    tagsQuery: '标签查询',
    tagValsQuery: '标签值查询',
    customAllVal: '自定义所有值',
    metricNameOrTag: '指标名称或标签查询',
    showMore: '展示更多',
    defineTime: '定义时间间隔（例如1m，1h，1d）',
    datasourceTip: '使您能够动态切换多个面板的数据源',
    constantTip: '定义一个隐藏的常数变量，对于要共享的仪表板中的度量前缀有用',
    adhocTip: '快速添加键/值过滤器',
    textboxTip: '定义一个文本框变量，用户可以在其中输入任意字符串',
    defineVarTip: '手动定义变量值',
    all: '全部',
    importVariables: '导入变量',
    selectFile: '请选择xxx.xlsx文件.',
    orgOverwriteInfo: '以下变量与当前页面已有的变量重复，请选择是否覆盖',
    fixDefaultValue: '固定默认值',
  },

  serverAdmin: {
    userSearchPlaceholder: '通过名称/登录名/电子邮件查找用户',
    seenTip: '上次查看到现在时间',
    newOrgDes:
      '每个组织都有自己的仪表板、数据源和配置，不能在组织之间共享。一个用户可能属于多个组织，但在多租户部署中最常使用多个组织。',
    settingDes: '配置完成后，请单击右侧的刷新按钮, 配置生效。',
    totalDashboards: '仪表板总数',
    totalUsers: '用户总数',
    activeUsers: '活动用户(过去30天可见)',
    activeAdmins: '活动管理员(过去30天可见)',
    activeEditors: '活动编辑者(过去30天可见)',
    activeViewers: '活动观看者(过去30天可见)',
    activeSessions: '活跃时间',
    totalOrgs: '组织总数',
    totalDatasources: '数据源总数',
    totalPlaylists: '播放列表总数',
    totalSnapshots: '快照总数',
    totalDashboardTags: '仪表板标签总数',
    totalStarredDashboards: '已加星标仪表板总数',
    totalAlerts: '告警总数',
    totalAdmins: '管理员总数',
    totalEditors: '可编辑者总数',
    totalViewers: '可观看者总数',
    selectOrg: '请选择导出组织',
    exportOrgFile: '导出组织文件',
    startImport: '开始导入',
    importOverwrite: '导入 (覆盖)',
    orgOverwriteInfo: '以下内容在当前org中重复，请选择是否覆盖',
    appOverwriteInfo: '以下内容与当前app重复，请选择是否覆盖！',
    startImportOrgInfo: '开始将数据导入到指定的org中。',
    startImportStruInfo: '开始将数据导入相同的结构。',
    systemAdmin: '系统管理员',
    logoutAllDevices: '从所有设备注销用户',
    userStatus: '使用者状态',
    editOrg: '编辑组织',
    orgUser: '组织用户',
    restartAppInfo: '配置变更，请重启app服务',
    orgSearchPlaceholder: '通过名称查找组织',
  },

  dashGeneral: {
    deleteDashProTitle: '不能删除预配置的仪表板',
    deleteDashProText1: `此仪表板由Grafanas设置管理，无法删除。 从配置文件将其删除`,
    deleteDashProText2: `<i>查看<a class="external-link" href="http://docs.grafana.org/administration/provisioning/#dashboards" target="_blank">
        文档</a>有关配置的更多信息</i>
        </br>
        文件路径:`,
    deleteDashText: '您要删除此仪表板吗？',
    deleteDashText2: `这个仪表板包含 {alerts}告警. 删除此仪表板也将删除这些告警信息`,
    dashHasDeleted: '仪表板已删除',
    hasDeletedText: '{title} 已被删除',
    tagInfo: '按Enter键添加标签',
    refreshInView: '可见视图刷新',
    editableTip: '取消选中，然后保存并重新加载以禁用所有仪表板编辑',
    mobileOptions: '移动端配置',
    panelOptions: '面板配置',
    graphUseTip: '使用快捷键在选项之间循环：CTRL + O或CMD + O',
    graphTip: 'Graph 提示',
    rowToGroup: '行变组',
    rowToGroupTip: '行面板会自动生成为移动页面上的组',
    gridColumnLevel: '网格列级别',
    gridColumnLevelTip: '如果从高等级切换到低等级，您需要保存配置然后重新加载页面',
  },

  srpFrame: {
    findSrpPlaceholder: '通过名称查找SRP Frame',
    noSrpFrameInfo: '没有匹配到查询的SRP Frame',
    noSrpFrameFound: '没有匹配到SRP Frame',
    srpHasSameName: '已存在相同名称的SRP Frame',
    deleteSrpText: '您是否要删除所选SRP Frame及其所有配置',
    deleteSrpsText: '您是否要删除所选SRP Frame及其所有配置',
    manageSrpSubTitle: '管理SRP Frame及其权限',
    langManList: '语言管理列表',
    nosrpLangInfo: `<div>您尚未添加任何语言配置。</div>`,
    situationRoom: '战情室预览',
    singleDisplay: '单片式预览',
    titleDes: '标题描述',
    logoLink: '左上角logo链接',
    powerLink: '右上角logo链接',
    menuList: '菜单列表',
    marquee: '跑马灯',
    notice: '通知',
    alarmDialog: '告警弹框',
    showTime: '显示时间',
    addAudio: '添加音频配置',
    showTimeTip: '告警弹框多久后消失，默认一直显示',
    enableMulti: '开启多种告警',
    dispaly55: '一片式',
    situation: '三片式',
    deleteMenuTitle: '删除菜单',
    deleteMenuText: '您确定要删除此列表吗？',
    autoplay: '轮播',
    autoPlayIterval: '轮播间隔时间',
    autoPlayUrl: '轮播网址',
    newFirstMenu: '新建第一级菜单',
    noMenuListInfo: `您尚未添加菜单列表。`,
    autoplayTip: `当更新自动播放的时间时，单位有s/m/h/d和never。`,
    fontColorTips: '菜单栏文字颜色',
    selectColorTips: '菜单栏选中文字颜色',
    selectedBgColor: "菜单栏背景颜色",
    bgColorTips: '菜单栏背景颜色',
    scrollColorTTips: '菜单栏滚动条颜色',
    ScrollBorder: '隐藏滚动条边框',
    ScrollBorderTips: '隐藏滚动条边框，开启代表隐藏滚动条边框线',
    sidebarColorTips: '菜单栏右侧边框颜色',
    menHoverTips: '菜单栏悬停颜色',
    menuBgImgTips: '菜单栏悬停背景图片',
    menuListImgTips: '菜单栏背景图片',
    menuSideTips: '菜单栏右侧边框图片',
    menuIconOpenTips: '菜单打开图标',
    menuIconCloseTips: '菜单关闭图标',
    menuIconWidthTips: '菜单打开图标宽度，单位是px',
    menuIconHeightTips: '菜单关闭图标高度，单位是px',
    titleShow: '面板支持修改操作，如果需要在srp中支持修改则需要将其打开',
    addMenulist: '添加菜单项',
    editMenulist: '修改菜单项',
    refreshMarquee: `当更新跑马灯刷新时间时，单位有s/m/h/d和never。`,
    refreshAlertNoticeTip: `当更新刷新时间时，单位有s/m/h/d和never。`,
    authType: '验证类型',
    headerKey: '请求头设置',
    ssoUrl: 'sso 地址',
    alertName: '告警名称',
    alertTimeRange: '告警时间范围',
    allAsRead: '全部标记为已读',
    linkEnable: '链接启用',
    rightTitle: '右侧标题',
    rightUrl: '右侧网址',
    bottomUrl: '底部网址',
    titleDisplay: '标题显示',
    mainPageTip: '主页对应于菜单列表的内容。',
    dashboardView: 'dashboard 视图',
    closeToHome: '关闭跳转到首页',
    heightAdjust: '高度自适应',
    dashboardHeader: '仪表板头部',
    dashboardHeaderAll: '仪表板头部全选',
    userVisible: '用户可见',
    userIconVisible: '用户图标可见',
    collapseSidemenu: '折叠菜单',
    expandSubmenu: '展开子菜单',
    expandlevel: '展开级数',
    sideWidth: '侧边宽度',
    sideDrag: '侧边可拖拽',
    srpFramesPermissions: 'SRP 权限',
    srpFramePerTip: `什么是SRP权限?<br>是指使用访问控制列表（ACL）模型来限制对SRP的访问,</br>可以向用户或团队分配SRP的权限。`,
    srpSetting: 'SRP Frame 设置',
    srpNameExistInfo: 'SRP 名称已经存在了',
    deleteSrpInfo: `您是否要删除{srpName}及其所有配置`,
    deleteLanguage: '删除语言',
    deleteLanguageInfo: '您确定要删除这种语言？',
    selectUser: '选择一个用户',
    ViewallEvent: '查看所有事件',
    Markallasread: '全部标记为已读',
    MenuLogobackColor: '菜单图标背景色',
    AudioFrequency: '音频',
    LogoutUrl: '登出链接',
    expandedShow: '显示展开',
    expandedShowTip: '配置打开到关闭，一级标题中配置有Dashboard及URL会被删除',
    titleFontSize: '标题字体大小',
    subTitleFontSize: '子标题字体大小',
    menuHeight: 'SRP菜单高度',
    threeTitleFontSize: '三级标题大小',
    menuColor: '菜单颜色',
    gradualShow: '渐变',
    gradualStartColor: '渐变开始颜色',
    gradualEndColor: '渐变结束颜色',
    tipsColor: '提示框背景色',
    tipsShow: '提示框显示',
    searchInputShow: '搜索框显示',
    menuBgImg: '菜单背景图',
    menuListBgImg: '侧边栏背景图',
    menuSideBg: '菜单侧边背景图',
    menuIconOpen: '菜单开启图标',
    menuIconClose: '菜单关闭图标',
    menuIconWidth: '菜单图标宽度',
    menuIconHeight: '菜单图标高度',
    PanelTitleShow: '插件头部显示',
    fontSizeTip: '字体单位结尾为px或者vw',
    teamSelected: '选择团队',
    clickClose: '点击关闭',
    expanded: '展开',
    menuPermission: '菜单权限',
    srpVariables: 'SRP 变量',
    bgImg: '背景图片',
    addBackSetting: '添加返回配置',
    backTitle: '返回标题',
    backUrl: '返回链接',
    backParameter: '返回参数',
  },

  configuration: {
    /* Datasources */
    datasourceEmptyTitle: '尚未定义数据源',
    datasourceProTip: '您可以通过配置文件定义数据源.',
    datasourceProTipLinkTitle: '了解更多',
    proTip: '特别提示',
    tsdb: '时间序列数据库',
    logging: '日志、文档数据库',
    cloud: '云端',
    otherType: '其他',
    url: '网址',
    access: '访问方式',
    line1Entry: '访问模式控制如何处理对数据源的请求.',
    line2Entry: '如果没有其他说明，应该是首选方式.',
    line3Entry: '代理访问为默认模式：',
    line4Entry:
      '所有请求都将从浏览器发出到Grafana后端/服务器，后者再将请求转发到数据源，' +
      '从而避免可能的跨域资源共享（CORS）要求。 如果选择此访问方式，则需要可以从grafana后端/服务器访问该地址',
    line5Entry: '客户端访问模式:',
    line6Entry:
      '所有请求都将从浏览器直接向数据源发出，并且可能要遵守跨域资源共享（CORS）的要求。' +
      '如果选择此访问方式，则需要可以从浏览器访问地址。',
    server: '服务端',
    defaultDatasource: '设置为默认数据源',
    defaultDatasourceTip: '在面板中选择数据源时使用该名称，在新面板中预先选择了默认数据源',
    leftEntry: '你访问的方式是',
    direct: '客户端访问(direct)',
    proxy: '代理访问(proxy)',
    directRight: '这意味着需要从浏览器访问该地址',
    proxyRight: '这意味着需要从grafana后端/服务器访问该地址',
    specialTip: '指定完整的超文本传输协议地址（例如超文本传输协议：//你的服务地址：8080）',
    ssoUrl: '指定SSO地址',
    ssoTip:
      '如果链接域名不同于sso域名，是否将sso域名用作链接域名？例如，当它是https://xxxxxx.trial.hz.wise-paas.com.cn时，' +
      '您可以将https://api-sso-ensaas.hz.wise-paas.com.cn配置为sso网址 ，或者当它是内部网址时，您可以使用与内部网址对应的sso网址。.',
    ssoTipData: '请配置SSO网址，例如 https://api-sso-ensaas.hz.wise-paas.com.cn.',
    ssoUrlData: 'SSO地址',
    auth: '验证方式',
    basicAuth: '基础验证',
    AdvancedList: '参数配置',
    AdvancedLabel: '键',
    AdvancedValue: '值',
    withCredentials: '凭证验证',
    credentialsTip: '凭据提示：是否应将跨站点请求发送凭据（例如cookie或auth标头),即用当前登录者信息访问datasource.',
    anonymous: '匿名账户验证',
    basicAuthDetails: '基本身份验证详细信息',
    advancedHttp: 'HTTP高级设置',
    advancedTip: '默认情况下，Grafana代理会删除转发的Cookie,通过指定名称，设置转发到数据源的cookie。',
    whitelistedCookies: '白名单Cookie',
    caCert: 'CA证书验证',
    tlsAuth: 'TLS客户端验证',
    tlsTip: '需用于验证自签名TLS证书',
    skipTLS: '跳过TLS验证',
    allowCleartextPasswords: '允许明文密码',
    oAuth: '转发OAuth验证',
    oAuthTip: '将用户上游的身份验证转发到数据源(传递它们的访问令牌).',
    tslAuthDetial: 'TLS身份验证详细信息',
    tslContent: 'TLS证书已加密并存储在Grafana数据库中.',
    caCertContent: 'CA证书',
    clientCert: '客户端证书',
    clientKey: '客户端密钥',
    beginCre: '开始于 -----开始于证书-----',
    beginKey: '开始于---开始于使用RSA私钥-----',
    handlError: '数据查询错误处理',
    keepLebal: '保留上次正确的数据',
    chooseDataSourceType: '选择一个数据源类型',
    wantDelete: '确定要删除此数据源吗?',
    dupQuery: '复制查询',
    disAndEn: '禁用/启用查询',
    removeQuery: '移除查询',
    undefinedError: '未定义的错误',
    HTTPError: 'HTTP 错误',
    HTTPErrorStatus: 'HTTP错误状态',
    /*Users*/
    pendInvite: '待处理的邀请',
    sendInvite: '发送邀请将现有Grafana用户添加到组织中',
    inviteEntry: '请邀请或添加用户到该组织中',
    deleteUser: '确定要删除用户',
    /*Teams*/
    noHaveTeam: `您尚未创建任何团队`,
    teamProTip: '将文件夹和仪表板的权限分配给团队而不是用户，以简化管理',
    searchTeams: '搜索团队',
    newTeam: '新建团队',
    teamTip: '这是可选的，主要用于允许自定义团队',
    teamSetting: '团队设置',
    update: '更新',
    members: '成员',
    addMember: '添加成员',
    addTeamMember: '添加团队成员',
    addToTeam: '添加到成员',
    subTitle: '管理成员和设置',
    selectTeam: '选择一个团队',
    noTeam: '未找到团队',
    /*Plugins*/
    findMore: '前往Grafana.com上查找更多插件',
    mpTip: '还有插件未注册，请在MP上重新启动该应用程序',
    grafanaTip: '还有插件未注册, 请重启grafana-server.exe服务',
    uploadTime: '上传时间',
    isRegister: '是否已注册',
    pluginTip: '您上传的文件正在存储',
    regPlugin: '插件上传 & 注册',
    fileName: '文件名称',
    deleteText: '你确定要删除 {name} 插件吗 ?',
    deleteText2: '如果删除了，与它相关的仪表板将会出错 !',
    selectZip: '请选择插件文件（.zip的文件格式）',
    errorType: '文件格式不正确, 请选择.zip格式文件',
    fileSize: '请选择小于15M的插件',
    pluginUpload: '插件上传',
    fileProgress: '上传进度',
    findCatalog: '了解更多插件请前往WISE-PaaS Catalog',
    purchasedPlugins: '购买的插件',
    customPlugin: '自定义插件',
    /*Images */
    imageUpload: '图片上传',
    imageType: '图片上传格式错误,请上传bmp, jpg, jpeg, png, gif, svg 格式的图片.',
    picSize: '请上传10M以内的图片',
    imageName: '图片名称',
    copySuccess: '复制成功',
    toPage: '跳转到',
    totalPage: '共',
    page: '页',
    clickMes: '请单击选择按钮',
    imageNameSame: '图像名称相同，是否上传？',
    deleteConf: '您确定删除这张图片吗?',
    copyDefeated: '复制失败',
    copyTip: '请复制文件的路径',
    /* APIKey */
    newAPiKey: '新建Api密钥',
    apiTip: '您尚未添加任何API密钥.',
    apiProTip: '请记住，您可以提供对其他应用程序的只读API访问。',
    addAPiKey: '添加Api密钥',
    keyName: '密钥名称',
    tooltipText: 'api密钥有效期。例如，如果密钥将持续一天，则为1d。 所有受支持的单位是：s，m，h，d，w，M，y',
    liveTime: '有效时间',
    apiKeyCreated: '已创建API密钥',
    key: '密钥',
    keyMas1: '您将只能在这里查看一次该密钥!它不以这种形式存储,所以一定要立即复制.',
    keyMas2: ' 您可以使用Authorization HTTP标头对请求进行身份验证，例如',
    existKey: '现有密钥',
    keyExpires: '到期日期',
    configTip: '请在下面设置与当前组织相关的配置.',
    sysTip: '未启用系统匿名，请联系系统管理员以在系统配置中将其打开',
    orgAnno: '组织匿名配置',
    WeChat: 'We Chat',
    Sms: 'Sms',
    Smtp: 'Smtp',
    Host: '地址',
    User: '用户名',
    Password: '密码',
    FromAddress: '创建地址',
    FromName: '创建名称',
    SkipVerify: '跳过验证',
    CertFile: '证书文件',
    KeyFile: '密钥文件',
    orgRole: '组织权限',
    configChange: '配置变更',
    localbrowsertime: '本地浏览器时间',
  },

  reporting: {
    reporting: '报表',
    reports: '报表',
    tasks: '任务',
    newReport: '新建报表',
    editReport: '编辑报表',
    taskName: '任务名称',
    reportTitle: '报表标题',
    schedule: '排程',
    selectedSchedule: '排程',
    scheduling: '排程',
    once: '一次性',
    deleteTask: '您确定删除这个任务吗?',
    editInfo: '编辑任务，跳转到PDF列表页面,可以暂停重启任务',
    filterByName: '根据名称查找',
    deleteFile: '您确定删除这个文件吗?',
    deleteFiles: '您确定删除这些文件吗?',
    fileName: '文件名',
    reportBranding: '报表标志',
    companyLogo: '公司图标地址',
    docFooterInfo: `这个图标会出现在报表的页脚,支持的格式有:jpg,jpeg,bmp,png。
            </br>png格式的需要在URL的尾部加上fmt=png。`,
    emailBranding: '邮件标志',
    footerLinkText: '页脚链接文字',
    footerLinkUrl: '页脚链接网址',
    sourceDash: '仪表板',
    sendEmail: '发送电子邮件',
    recipients: '收件者',
    multiEmail: '您可以添加多个邮箱地址,使用;分隔。',
    timeRangeInfo: '在报告中指定数据查询的时间范围，默认显示为在仪表板中设置的时间范围。',
    frequency: '频率',
    taskType: '任务类型',
    taskInfo: '如果面板无法导出PDF，此面板位置显示为空白；如果面板无法导出EXCEL，EXCEL中的不包含此面板的数据',
    layout: '布局',
    pdfStyle: 'PDF 样式',
    simpleGird: '单排显示-每-行显示一个面板。网格显示-仪表板上一行可以显示多个面板',
    simple: '单排',
    gird: '网格',
    messageInfo: '请检查附件中的报告。如果发现任何问题，请访问仪表板服务进行检查。',
    monthly: '每月',
    weekly: '每周',
    daily: '每天',
    hourly: '每小时',
    immediately: '立刻',
    delayTime: '延迟时间',
    signleTaskMaxWaitTime: '最大等待时间',
    deleteType: '您确定删除选中的类型下的所有文件吗？',
    deleteTypeAndFile: '您确定删除选中的类型和文件吗？',
    deleteTypeDesc: '选中的类型下的文件都将被删除'
  },

  navTreeConfig: {
    createFolderSubTitle: '创建一个新文件夹来组织您的仪表板',
    createImportSubTitle: '从Json文件导入仪表板',
    srpSubTitle: '管理SRP-Frame',
    dashboardsSubTitle: '管理仪表板和文件夹',
    exploreSubTitle: '探索您的数据',
    alertingSubTitle: '告警规则和通知',
    reportingSubTitle: '创建和管理的PDF和EXCEL报表',
    configurationSubTitle: '组织：',
    datasourcesDes: '添加和配置数据源',
    usersDes: '管理组织成员',
    teamsDes: '管理组织组',
    pluginsDes: '查看和配置插件',
    imagesDes: '查看和配置图片',
    orgSettingDes: 'Organization preferences',
    apikeysDes: '创建和管理API密钥',
    currentOrgSettingsDes: '当前组织设置',
    serverAdminSubTitle: '管理所有用户和组织',
    keyboardShortcuts: '键盘快捷键',
    superiorPluginsSubTitle: '精品插件展示',
  },
  help: {
    ShortcutsTotal: '快捷键',
    mod: '模组',
    modDesc: 'Windows、Linux上的CTRL键,Mac上的CMD键',
    globalEntry: '总体',
    focusedPanel: '聚焦的面板',
    goHomeDashboard: '跳转到主页仪表板',
    goProfile: '跳转到个人资料',
    openSearch: '打开搜索',
    ExitEntry: '退出编辑或者设置的面板',
    refreshAllPanel: '刷新所有面板',
    toggleEntry: '切换非活动/查看模式',
    kioskMode: '切换kiosk模式 (隐藏顶部导航)',
    expandAllRows: '展开所有行',
    collapseAllRows: '折叠所有行',
    autoFix: '切换自动调整面板（实验功能）',
    toggleGraph: '切换分享十字准线',
    togglePanelsLegend: '切换所有面板图例',
    togglePanelEditView: '切换到面板编辑模式',
    togglePanleFullscreen: '切换到面板全屏模式',
    openPanelShareModal: '打开面板共享模式',
    togglePanelLegend: '切换面板图例',
    zoomOutTimeRange: '缩小时间范围',
    moveTimeBack: '向后移动时间范围',
    moveTimeForward: '向前移动时间范围',
  },

  comparison: {
    function: '功能',
    professional: '专业版',
    standard: '标准版',
    standardEdge: 'Edge标准版',
    professionalEdge: 'Edge专业版',
    advanced: '高阶版\n(WebAccess)',
    professionalWA: '专业版-WA\n(WebAccess)',
    enhanced: '增强版\n(iFactory)',
    lite: '精简版\n(iFactory)',
    professionalDesc: 'Dashboard 专业版',
    standardDesc: 'Dahboard标准版',
    standardEdgeDesc: '与IoT Edge整合的Dashboard标准版',
    professionalEdgeDesc: '与IoT Edge整合的 Dashboard 专业版',
    advancedDesc: '与 WebAccess 整合的 Dashboard 高阶版',
    professionalWADesc: '与 WebAccess 整合的 Dashboard 专业版',
    enhancedDesc: '与 iFactory 整合的 Dashboard 增强版',
    liteDesc: '与 iFactory 整合的 Dashboard 精简版',
    dashboardManage: 'Dashboard创建和管理',
    datasourceManage: '数据源创建和管理',
    alertNotification: 'Alert&Notification&Annotation',
    userManage: 'User/Team管理',
    innerPanel: '内置Panel插件',
    innerDatasource: '内置Datasource插件',
    onlyTestDB: '仅支持TestDB Datasource',
    onlyIotEdge: '仅支持IoT Edge Datasource',
    onlyWebAccess: '仅支持WebAccess Datasource',
    outerPanel: '外置Panel插件',
    outerDatasource: '外置Datasource插件',
    changeLogo: '自定义企业logo（Dashboard icon，非powered by WISE-PaaS）',
    SRPManage: 'SRP-Frame管理',
    uploadManage: '图片、插件上传管理',
    mobileTypesetting: '移动端排版',
    dashboardExport: 'Dashboard报表导出',
    multilingual: '多语言',
    dataImport: 'Dashboard资料备份导入',
    emailCounsel: '电子邮件咨询',
    orderCounsel: '工单咨询',
    onlineVideo: '在线技术文档和视频教程',
    onlineCourse: '线上专场培训',
    onlineCustomizedCourse: '线上定制化培训',
    onlineRemoteSupport: '在线远程技术支持',
    wechatSupport: '微信技术支持',
    weekdaysService: '5*8响应技术问题',
    solution: '解决方案\n(iFactory)',
    solutionDesc: 'EHS或者TPM解决方案搭配的版本',
    restrictDatasource: '仅支持资产和警报中心等数据源',
  },

  pluginsDesc: {
    function: '功能介绍',
    introduction: '简介',
    complexDatatable: {
      introduction: 'Complex Table是一款可灵活配置，满足复杂多样的表格，支持表格的反写功能及各种灵活设置。',
      desc: {
        feature1: '支持表格行修改，添加，删除；',
        feature2: '支持表格整列数据的修改；',
        feature3: '支持各种告警的灵活设置；',
        feature4: '支持自定义新增一列；',
      },
    },
    oracle: {
      introduction:
        '支持关系数据库Oracle数据的接入，通过简单的界面引导配置，即可快速进行单表，单视图，以及多表，多视图之间的关联、查询。',
      desc: {
        feature1: '支持单表、单视图界面引导查询、SQL语句查询；',
        feature2: '支持多表，多视图之间级联界面引导查询、SQL语句查询；',
        feature3: 'Oracle 类型变量查询支持界面化引导方式；',
        feature4: 'Oracle 支持动态变量查询；',
      },
    },
    snowflake: {
      introduction:
        '支持Snowflake弹性数据仓库数据的接入，通过简单配置连接信息，即可便捷、快速接入其数据在Dashboard上进行呈现。',
      desc: {
        feature1: '支持灵活的链接信息配置；',
        feature2: '支持通过SQL查询，进行数据呈现；',
        feature3: '请求支持动态变量查询；',
      },
    },
    streetView: {
      introduction:
        'Street View Panel是一款用于显示地图详细信息的插件，可详细到街道的展示。支持对特定经纬度位置进行标记并显示当前位置的数据，支持实时绘制轨迹图，支持地图上显示热图信息。',
      desc: {
        feature1: '支持世界范围的地理位置坐标；',
        feature2: '支持timeserie和table两种数据类型；',
        feature3: '提供动态轨迹绘制功能；',
        feature4: '支持地图叠加热图显示效果；',
        feature5: '支持中心经纬度的设定；',
        feature6: '阈值颜色设置；',
      },
    },
    choropleth: {
      introduction:
        'Choropleth Map Panel是一款用于显示各省份数据等级或分布的地图插件。此插件支持两种显示模式，一种是各区域根据不同的数据显示不同的颜色等级，并可标注气泡显示当前的数值。另一种仅需要展示各区域的数值差异则以更加立体的效果显示，同样可标注气泡显示当前区域的数值，数据分布一目了然。',
      desc: {
        feature1: '支持颜色等级和分布两种显示模式；',
        feature2: '颜色等级模式支持颜色区间自定义；',
        feature3: '数据标注气泡可支持样式设定；',
      },
    },
    scatterMap: {
      introduction:
        'Scatter Map panel是一款用于显示地理位置数据的美观的世界地图插件。可以对特定经纬度位置进行标记并显示当前位置的数据，支持灵活的区域，边界线等颜色设定和位置标记样式的设定。',
      desc: {
        feature1: '支持世界范围的地理位置坐标；',
        feature2: '支持timeserie和table两种数据类型；',
        feature3: '支持地图中心经纬度，缩放等级设定，是否可拖拽的设定；',
        feature4: '散射，气泡等的大小，颜色设定；',
        feature5: '阈值颜色设置；',
        feature6: '提供marker跳动标注显示；',
        feature7: '提供水域，陆地，边界,行政名称的颜色修改；',
      },
    },
    hydrograph: {
      introduction:
        'Hydrograph Panel是一个用来显示百分比数值的WISE-PaaS/Dashboard 插件，代表当前的占比情况。该插件使用动画形式的波浪来展示百分比，效果炫酷。支持域值和颜色的自定义，可以让波浪在不同的数据下展示不同的颜色，搭配数值百分比显示，直观易懂。其使用配置简单，效果炫酷。',
      desc: {
        feature1: '支持字体大小和保留小数点个数设置；',
        feature2: '支持自定义计算区间最大值，结合当前数据计算百分比；',
        feature3: '支持多域值和颜色设置，可根据需要添加不同的域值区间展示不同的业务含义；',
        feature4: '图形大小自适应外部panel大小；',
      },
    },
    thermometer: {
      introduction:
        'Thermometer panel是WISE-PaaS/Dashboard的一个温度计插件。该插件可直观的显示温度的数值和温度的状态，可用于任何需要展示温度的场景中。',
      desc: {
        feature1: '支持Table和Timeserie数据源，支持数据的统计值显示（例如最大值、最小值、平均值、最新值等）；',
        feature2: '灵活的刻度设置支持最大最小刻度值设置，支持刻度区间设置；',
        feature3: '支持温度的阈值区间自定义；',
        feature4: '支持字体的大小设置和温度单位的设置；',
        feature5: '温度计图形显示根据panel大小可自适应调整；',
      },
    },
  },

  admin: {
    editProfile: '编辑个人资料',
    disableLoginTooltip: '登录信息锁定 - 在另一个系统中管理.',
    perferenceTooltip: '找不到想要的仪表板? 首先把仪表板收藏, 然后它应该就出现在这个选择框中.',
    homeSrpFrameTooltip: '选择SRP Frame的名称和语言，然后就可以进入SRP Frame主页',
    switchOrganization: '切换组织',
    changeYourPassword: '修改你的密码',
    oldPassword: '旧密码',
    newPassword: '新密码',
    confirmPassword: '确认密码',
    changePassword: '修改密码',
    ldapEnabled: `当启用ldap或auth代理身份验证时，您无法更改密码。`,
    chooseDefaultDashboard: 'Choose default dashboard',
    chooseDefaultSRPFrame: '选择默认的SRP Frame',
  },
  alerting: {
    states: '状态',
    howToAdd: '如何添加告警',
    pauseTitle: '暂停告警规则将阻止其执行',
    editAlertRule: '编辑告警规则',
    addingAlert: '添加一个警告',
    alertText1: '告警是可以在任何仪表板的图形面板中的告警标签中添加和配置，让您使用现有查询构建和可视化告警。',
    alertText2: '要持久保存警报规则更改，请记住保存仪表板。',
    okText: '正常',
    keepState: '保持最后状态',
    alertText: '告警',
    no_dataText: '无数据',
    pausedText: '暂停',
    pendingText: '等待',
    unknownText: '未知',
    forText: '持续了',
    forTextStatus: '状态',
    newNoticeChannel: '新建通知方式',
    notificationMes: '通知消息详细信息...',
    editNoticeChannel: '编辑通知方式',
    defaultSend: '默认(发送所有告警)',
    defaultSendTip: '对所有告警使用此通知',
    includeImage: '包括图像',
    includeImageTip: '捕获图像并将其包含在通知中',
    disableMessage: '禁用解析消息',
    disableMessageTip: '禁用当告警状态返回false时发送的解析消息[OK]',
    sendReminders: '发送提醒',
    sendRemindersTip: '为触发的告警发送额外通知',
    sendReminderEvery: '发送每一个提醒',
    sendReminderEveryTip: '指明发出提醒的频率。例如每隔30秒、1分钟、10分钟、30分钟或1小时等。',
    sendReminderText: '在计算规则之后会发送警告提醒。因此，一个提醒永远不会比一个配置的警报规则评估间隔更频繁地发送。',
    removeAlertText2: `面板包括一个告警规则，删除面板也将删除告警规则`,
    toConfirm: '以确认',
    searchAlerts: '搜索告警',
    noHasAlert: '尚未定义任何通知规则.',
    addChannel: '添加规则',
    proTip: '您可以在告警通知中包括图像.',
    errorTip: '该数据源不支持告警查询',
    errorTip1: '警报查询中不支持模板变量',
    errorTip2: '找不到任何指标查询',
  },
  create: {
    convertToRow: '转换为行',
    pasteCopiedPanel: '粘贴复制的面板',
    chooseVisualization: '选择可视化',
    cycleViewMode: '视图模式切换',
    timeRangeZoomOut: '时间范围缩小',
    saveNameText: '在选定的文件夹中已经存在同名的仪表板。',
    saveNameText2: '您仍然想保存这个仪表板吗?',
    saveVersionText: '有人更新了这个仪表板。',
    newDashboardFolder: '新建仪表板文件夹',
    startPlaylist: '开始播放列表',
    playlistsaved: '播放列表已保存',
    unableSavePlaylist: '无法保存播放列表',
    playlistDeleted: '播放列表已删除',
    unableDeletePlaylist: '无法删除播放列表',
    previousDashboard: '去上一个仪表板',
    stopPlaylist: '停止播放列表',
    nextDashboard: '去下一个仪表板',
    inNormalMode: '正常模式',
    inTVMode: 'TV 模式',
    withAutoFitPanels: '自动配合面板',
    inKioskMode: 'Kiosk 模式',
    playlistDescription: `播放列表会在仪表板的预选列表中循环显示。 播放列表可能是建立情景意识的好方法，或者只是向团队或访问者展示您的指标。`,
    playlistEmpty: '播放列表为空，请在下面添加仪表板。',
    findDashboardsByName: '按名称查找仪表板',
    addToPlaylist: '添加到播放列表',
    snapshotUrl: '快照路径',
    external: '外部的',
    uploadJsonFile: '上传. json文件',
    grafanaComDashboard: '仪表板',
    pasteGrafanaComDashboardUrlId: '粘贴仪表板url或id',
    couldNotFindDashboard: '找不到仪表板',
    orPasteJSON: '或者粘贴JSON',
    markAsFavorite: '标记为最喜爱的',
    addNoteDescribeChanges: '添加注释来描述您的更改...',
    openOriginalDashboard: '打开原本的仪表板',
    openMobilePage: '打开手机页面',
    shareLinkInfo: '创建到这个仪表板或面板的直接链接，使用下面的选项进行定制。',
    currentTimeRange: '当前时间范围',
    templateVariables: '模板变量',
    snapshotDeleteText: '您确认想要删除快照',
    shareSnapshotInfo: `快照是一种即时共享交互式仪表板的方式。
        创建后，我们<strong>剥离敏感数据</strong>，如查询(度量、模板和注释)和面板链接，
        只在仪表板中嵌入可见的度量数据和系列名称。`,
    shareSnapshotInfo1: `请记住，你的<strong>快照可以被任何有链接并能到达URL的人</strong>查看。
        明智的分享。`,
    snapshotName: '快照名称',
    expire: '到期',
    shareSnapshotInfo2: `如果收集仪表板指标需要很长时间，则可能需要配置超时值。`,
    localSnapshot: '本地的快照',
    copyLink: '复制链接',
    makeMistake: '你出现错误了吗?',
    deleteSnapshot: '删除快照。',
    exportsharingExternally: '导出用于外部共享',
    exportsharingTooltip: `对于在grafana.com上公开分享仪表板非常有用。将模板化数据源名称。然后只能与特定的仪表板导入API一起使用。`,
    saveToFile: '保存到文件',
    viewJSON: '查看 JSON',
    clickButtonGenerateReport: '单击按钮生成报告',
    saveToPdf: '保存为pdf',
    sharePanel: '分享面板',
    directLinkRenderedImage: '直接链接渲染图像',
    shareModalInfoText: `下面的html代码可以粘贴在另一个网页中。除非启用了匿名访问，否则查看该页面的用户需要被签名到WISE-PaaS/Dashboard中以加载图表。`,
    selectA: '选择一个',
    dataSource: '数据源',
    uidValidationError: `在{folderTitle}文件中名称为{dashboardTitle}的Dashboard有相同uid`,
    importUidValidationError: '在{folderTitle}文件中名称为{dashboardTitle}的Dashboard有相同uid',
  },
  dashboards: {
    /*Home*/
    installGrafana: '安装 WISE-IoTSuite/Dashboard',
    creatDatasource: '创建第一个数据源',
    addDatasource: '添加数据源',
    createDashboard: '创建第一个仪表板',
    newDashboard: '新建仪表板',
    inviteTeam: '邀请您的团队',
    addUsers: '添加用户',
    installApp: '安装应用程序 & 插件',
    explorePlugin: '探索插件库',
    starredDashboard: '已加星标的仪表板',
    recentlyView: '最近浏览的仪表板',
    installedApp: '已安装的应用程序',
    installedPanel: '已安装的面板',
    installedDatasource: '已安装的数据源',
    clearCurrentQuery: '清除当前搜索查询和过滤',
    noDashFound: '没有仪表板发现',
    noMatch: '未找到与您的查询匹配的仪表板.',
    findByName: '按名称查找仪表板',
    starred: '星标',
    filterByTag: '按标签过滤',
    filterByStar: '按星标筛选',
    deleteText: '你想要删除',
    deleteText1: '选定的文件夹和仪表板',
    deleteText2: '选定文件夹下的仪表板都将被删除',
    deleteText3: '选定的文件夹和其下的仪表板',
    deleteText4: '选择的仪表板',
    chooseDashboard: '选择仪表板文件夹',
    moveMessage: '移动',
    moveToDash: '选定的仪表板到以下文件夹',
    updateOn: '更新于',
    uniqueMas: '唯一标识符(uid)',
    uniqueTip: ` 仪表板的唯一标识符（uid）可用于在多个已安装WISE-PaaS/Dashboard之间唯一标识仪表板,uid允许使用一致的网址来访问仪表板，
        因此更改仪表板的标题不会破坏任何指向该仪表板的书签链接。`,
    sameName: '已有同名仪表板存在于此文件夹中',
    sameFolder: '具有相同名称的文件夹或仪表板已在常规文件夹中存在',
    requiredName: '名称是必须的',
    folderMas: '这是保留名称，不能用于文件夹.',
    subTitleDashboard: '管理文件夹的仪表板和权限',
    forderSetting: '文件夹设置',
    /*Playlist */
    noPlayList: '尚未创建播放列表.',
    playTip: '您可以使用播放列表在电视上循环显示面板，而无需用户控制',
    createPlay: '创建播放列表',
    deletePlay: `确定要删除播放列表{name}?`,
    editPlay: '编辑播放列表',
    creDashboard: '创建仪表板',
    manDashboard: '管理仪表板',
    moveTo: '将仪表板添加/移动到您的文件夹中',
    hasNoDashboard: '这个文件夹还没有任何仪表板',
  },
  treeMenu: {
    openleftMenu: '打开左侧菜单栏',
    dataConfig: '数据配置',
    headersConfig: 'Headers 配置',
    generalConfig: '通用配置',
    defaultExpandedWidth: '默认展开宽度',
    initialGroup: '初始资产组',
    groupVariableAssociation: '资产组变量关联',
    objectVariableAssociation: '资产变量关联',
    selectAsset: '选中资产组',
    selectAssetObj: '选中资产',
    refreshVisible: '刷新可见',
    area: '区域',
    pleaseInputObjectGroupName: '请输入资产组名称',
    titleColor: '标题颜色',
    inputBgColor: '背景色',
    inputTxtColor: "文字颜色",
    inputBorderColor: "边框颜色",
    backgroundColor: '背景颜色',
    fontColor: '字体颜色',
    menuActiveBgColor: '选中颜色',
    menuActiveFontColor: '选中文字颜色',
    menuScrollColor: '滚动条颜色',
    menuIconOpenUrl: '打开图标地址',
    menuFontSize: '文字大小',
    menuFontSpacing: '文字间距',
    menuFontTips: '需要添加px单位',
    menuIconCloseUrl: '关闭图标地址',
    treeMenuProperty: '查询资产',
    treeMenuTagMultiple: '资产开启多选',
    menuAll: '选择所有',
    searchStyles: "搜索框样式",
    menuStyles: "菜单样式"
  },
  annotations: {
    emptyListCtaTitle: '未添加自定义注释查询',
    buttonTitle: '添加注释查询',
    infoBoxTitle: '什么是注释?',
    infoBoxHTML1: `注释提供了一种将事件数据集成到你的graphs面板的方法。它们在所有graph面板中显示为垂直线
        和图标。当您把鼠标悬停在一个注释图标上时，可以看到这个事件的事件文本和标记。您可以通过按住CTRL或CMD +点击graph(或拖拽区域)直接在仪表板里添加注释事件。
        这些将存储在仪表板的注释数据库中。`,
    infoBoxHTML2: '查看',
    infoBoxHTML3: '注释文档',
    infoBoxHTML4: '获取更多信息。',
    builtIn: '(内置)',
    hiddenTooltip: '隐藏注释查询切换控制是否显示在仪表板的顶部',
    annotationQueryFailed: '注释查询失败',
  },
  dashboardStyle: {
    styleSetting: '仪表板样式设定',
    background: '仪表板背景',
    color: '背景色',
    image: '背景图片',
    panelStyle: '面板样式设定',
    preStyle: '预设样式',
    border: '面板边框',
    borderColor: '边框颜色',
    borderStyle: '边框样式',
    borderWidth: '边框宽度',
    borderWidthTip: '请输入数字作为边框的宽度',
    panelRadius: '面板圆角设置',
    radius: '圆角模式',
    radiusColor: '圆角颜色',
    borderShadow: '边框阴影',
    borderGradient: '边框渐变',
    gradientMode: '渐变模式',
    gradientColor: '渐变颜色',
    panelTitle: '面板标题',
    startColor: '渐变开始颜色',
    endColor: '渐变结束颜色',
    pillarColor: '柱子颜色',
    shadowShow: '阴影显示',
    reduceTopMargin: '缩小上边距',
  },
  dashboardLinks: {
    links: '仪表板链接',
    linkTitle: '尚未添加仪表板链接',
    addLink: '添加仪表板链接',
    pTip: '仪表板链接允许您将指向其他仪表板和网站的链接直接放置在仪表板标题下方.',
    whatLink: '仪表板链接是什么?',
    withTag: '标签',
    include: '包括',
    asDrop: '作为下拉菜单',
    varValue: '变量值',
    oneLine: '启用一行显示',
  },
  orgsImport: {
    datalog: '导入的数据日志.',
    closeDataLog: '导入完成.',
    wait: '等待...',
    sameStructImport: '相同结构导入',
    importSpecifiedOrg: '导入到指定组织',
    selectFile: '请选择exportedOrgs.xxx.zip文件.',
    startImport: '开始打印相关日志信息 . . .',
    waitOverwrite: '请等待片刻，正在覆盖您刚选择的项.',
    callOverwrite: '开始调用覆盖的方法.',
    annoInfoSuccess: '所选{name}数据源的匿名信息已成功更新.',
    annoInfoError: '{org}组织中的{name}数据源匿名信息更新失败.',
    dataUpSuccess: '所选{name}数据源更新成功.',
    dataUpFailed: '所选数据源更新失败.',
    dashOverSuccess: '所选{name}仪表板信息已成功更新.',
    dashOverFaild: '{orgId}组织中仪表板覆盖失败.',
    srpUpSuccess: '所选{name} SRPFrame已更新成功.',
    srpUpFailed: '"{orgId}组织下SRPFrame覆盖失败."',
    startGet: '开始获取每个文件的内容.',
    tip: '提示',
    importMoreOne: '当导入组织超过一个时,仅为您导入第一个({name})组织的数据.',
    importText2: '您是否仍想导入{name} 组织数据?',
    dashExist: '{orgName}组织,{folder}文件夹下的{slug}仪表板已存在.',
    dashImportSucc: '{orgName}组织,{folder}文件夹下的仪表板{slug}导入成功.',
    dashImportFalied: '{org}组织下仪表板导入失败.',
    folderResult: '{folder}文件夹下仪表板已成功返回.',
    getOrgFailed: '{orgName} 组织下{folder}文件夹获取失败.',
    getFrameFailed: '获取SRP-Frame失败.',
    srpImportSuccess: '{orgName}组织下的SRP-Frame 导入成功.',
    srpImportFailed: '{currentId}组织下的SRP-Frame导入失败.',
    srpExist: '{orgName}组织下的{srpName} {type} 已经存在.',
    datasourceError: '导入数据源的时候发生了错误.',
    dataImportSuccess: '{paasOrgName} 组织下 {datasourceName} 数据源导入成功.',
    dataImportFailed: '{currentId}组织下数据源导入失败.',
    annoImportSuccess: '{paasOrgName}组织下数据源匿名信息导入成功.',
    annoImportFalied: '{currentId} 组织下数据源匿名信息导入失败.',
    creNewOrg: '创建新组织 {orgName} 并导入数据.',
    creOrgFailed: '创建组织失败.',
    nowImportSRPFrame: '开始导入SRP-Frame...',
    dashsImportFalied: '仪表板导入失败.',
    createFolderFalied: '创建文件夹失败.',
    preferenceError: '导入组织偏好的时候发生了错误.',
    imgUploadSuccess: '{orgName}组织下图片{imageName}导入成功',
    imgUploadError: '{orgName}组织下图片{imageName}导入失败',
  },
  versions: {
    showMoreVersions: '展示更多的版本',
    compareVersions: '比较版本',
    restoreToVersion: '恢复版本到',
    viewJSONDiff: '查看 JSON 差异',
    canCompareText: '您一次只能比较两个版本',
  },
  mobile: {
    groups: '分组',
    recover: '恢复',
    addGroup: '添加分组',
    noDashboardGroupAddedYet: '还没有添加仪表板分组',
    whatAreDashboardGroup: '什么是仪表板分组?',
    whatAreDashboardGroupInfo: `我们建议通过建立分组，将大量数据以分组方式呈现在移动设备的小屏幕上`,
    movePanel: '移动面板',
    moveOut: '移出',
    moveToRecover: '移动到回收站',
  },
  graph: {
    drawModes: '绘制模式',
    bars: '柱形',
    lines: '线形',
    points: '点',
    modeOptions: '模式选择',
    fillGradient: '填充渐变',
    lineWidth: '线宽',
    staircase: '阶梯',
    pointRadius: '点径',
    plotSelected: 'Plot 可选',
    plotDblclick: 'Plot 双击',
    hoverTooltip: '悬停提示',
    stackedValue: '堆叠值',
    stackTotal: '堆叠总数',
    stackingNullValue: '堆叠和空值',
    stack: '堆叠',
    percent: '百分比',
    nullValue: '空值',
    stackPanel: '面板堆叠',
    drilldownDetailLink: '钻取详细链接',
    includeTimeRange: '包含时间范围',
    includeCurrentTime: '包含当前时间',
    urlParams: 'Url 参数',
    urlParamsTips: '此处勾选变量后，在Url中使用[变量]，可在新链接中将此变量传递至新页面',
    XAxis: 'X轴',
    precisionFormat: '精度格式',
    adjustableTimeRange: '可调整时间范围',
    numberOfBuckets: '周期值',
    XMin: 'X轴最小值',
    XMax: 'X轴最大值',
    YAxes: 'Y轴',
    YAxis: 'Y轴',
    alignLeftAndRightYaxes: '对齐左右y轴',
    AlignmentYaxesTooltip: 'Y轴对齐是基于这个值，从Y=0开始',
    decimalPrecision: '覆盖y轴的自动小数位数精度',
    asTable: '表格格式',
    toTheRight: '靠右',
    widthTooltip: '设置图例表格/块的最小宽度',
    hideSeries: '隐藏系列',
    withOnlyNulls: '仅有空值',
    withOnlyZeros: '仅有零值',
    seriesOverrides: '系列覆盖',
    aliasOrRegex: '别名或正则表达式',
    addSeriesOverride: '添加系列覆盖',
    addSeriesOverrideTip: '正则表达式匹配的例子: /server[0-3]/i',
    thresholdsTimeRegions: '阈值和时间区域',
    addThreshold: '添加阈值',
    thresholdsDisabled: `<strong>禁用</strong>可视化阈值选项。访问Alert选项卡更新阈值。
        <br>为了重新启用阈值，必须从该面板删除告警规则。`,
    fillColor: '填充颜色',
    line: '线',
    lineColor: '线颜色',
    addTimeRegion: '添加时间区域',
    addTimeRegionTip: '所有配置的时间区域都是UTC时间',
    statistics: '统计数据',
    UCL: '上控制限',
    CL: '中心线',
    LCL: '下控制限',
    showDetails: '显示详细信息',
    infoTextLink: `使用数据链接，您可以引用数据变量，如系列名称、标签和值。键入CMD + 空格键，
        CTRL+空格，或$来打开变量建议。`,
    addLink: '添加链接',
    customScale: '刻度',
    customScaleEnable: '自定义刻度',
    markingArea: '标记区域',
    startTime: '开始时间',
    endTime: '结束时间',
    linkageSettings: '联动设置',
    addALinkage: '添加一组联动',
    lineFill: '线填充',
    Linewidth: '线宽',
    nullPointMode: '空点方式',
    fillBelowTo: '下方填充至',
    staircaseLine: '阶梯线',
    Dashes: '破折号',
    HiddenSeries: '隐藏的系列',
    DashLength: '破折线长度',
    DashSpace: '破折线间距',
    Discrete: '离散',
    PointsRadius: '点径',
    Yaxis: 'Y-轴',
    Zindex: 'Z层级',
    Transform: '转换',
    Hideintooltip: '隐藏工具提示',
    DiscreteDataType: '离散数据类型',
    DiscreteDayShift: '离散日后退',
    showModes: '显示绘制方式',
    showXSlider: '显示X轴滑块',
    graphMode: '图像方式',
    showMaxPoint: '显示最大值点',
    Spline: '平滑',
    markingMaxPoint: '标记最大值点',
    dateFormatAsX: '日期格式和X轴一致',
    hideValue: '隐藏值',
    metricNameColor: '文字颜色',
    metricNameSize: '文字大小',
    metricNamePositionUp: '名称上移',
    showValue: '显示值',
  },
  math: {
    math: '数学公式',
    calculate: '计算',
    expression: '表达式',
    expressionTip: `A,B,C,D 代表数据源,<br>支持的操作符有 +, -, *, /, ().`,
    inputTip: '请输入正确的表达式',
    addMetric: '增加指标',
  },
  singlestat: {
    thresholdsTip: `定义两个阈值<br>50,80将会产生: 值 < 50 = 绿色, 50 < = 值 < 80
        = 黄色, 值 > = 80 = 红色。注意：阈值支持填写也支持配置query返回，若同时填写了阈值和配置了一笔query时，query返回阈值的优先级高`,
    sparkLines: 'Spark线',
    fullHeight: '完整的高度',
    gauge: '计量器',
    minValueText: '最小值大于最大值。',
    thresFontSize: '阈值字体大小',
    thresholdLabels: '阈值标签',
    thresholdMarkers: '阈值标记',
    setValueMappings: '设置值映射',
    addValueMapping: '添加一个值映射',
    setRangeMappings: '设置范围映射',
    addRangeMapping: '添加范围映射',
  },
  text: {
    autoplayInterval: '自动播放间隔',
    autoplayUrl: '播放网址',
    addUrl: '增加网址',
  },
  heatmap: {
    bucketBound: '周期边界',
    bucketBoundTip: '使用系列标签作为上或下周期的边界。',
    bucketsTip: 'Y轴上的周期数。',
    sizeYTip: '周期的大小。优先于周期选项。',
    splitFactor: '分割因子',
    splitFactorTooltip: `仅适用于对数尺度。默认情况下，Y值被以(1,2,4,8,16，…)为底的整数幂所分割)。该选项允许将每个默认周期拆分为指定数量的周期。`,
    bucketsXTip: 'X轴上的周期数。',
    sizeXTip: '周期的大小。数值或间隔(10s、5m、1h等)。支持的时间间隔:ms, s, m, h, d, w, m, y。优先于周期选项。',
    dataFormatTip: `时间序列:规律时间序列创建热图。<br> 时间序列周期:使用从数据源返回的直方图数据。每个系列表示周期的上下限是一个系列标签。`,
    reverseOrder: '倒序',
    yBucketBoundTip: '使用系列标签作为上或下周期的边界。',
    exponent: '指数',
    colorScale: '色阶',
    showLegend: '显示图例',
    hideZero: '隐藏零值',
    showTooltip: '显示提示',
  },
  pluginlist: {
    recentlyViewed: '警告:当清除浏览器缓存时，此列表将被清除.',
    searchOptions: '搜索选项',
    limitNumberTo: '限制数量',
  },
  dashlist: {
    showHeadings: '显示标题',
  },
  alertlist: {
    alertsFromDashboard: '来自此仪表板的警报',
    alertName: '告警名称',
    alertNameQuery: '告警名称查询',
    dashboardTitle: '仪表板的标题',
    dashboardTitleQuery: '仪表板标题查询',
    dashboardTags: '仪表板标签',
    stateFilter: '状态过滤',
    ok: '正常',
    paused: '暂停',
    noData: '无数据',
    executionError: '执行错误',
    pending: '等待',
  },
  table: {
    tableTransform: '表转换',
    paging: '分页',
    rowsPerPage: '每页行数',
    columnStyles: '列样式',
    applyColumnsNamed: '应用于列名称为',
    patternTip: '指定正则表达式使用/my.*regex/语法',
    columnHeader: '列标题',
    renderValueLink: '渲染值为链接',
    nameOrRegex: '名称或正则表达式',
    overrideHeaderLabel: '覆盖标题标签',
    sanitizeHTML: '处理HTML',
    preserveFormatting: '保存格式',
    commaSeparatedValues: '逗号分隔值',
    urlInfo1: '指定一个网址(相对或绝对)',
    urlInfo2: '使用特殊变量来指定单元格的值:',
    urlInfo3: '指当前单元格值',
    urlInfo4: '指当前行的第n列值。列索引从0开始。例如,',
    urlInfo5: '指第二列的值。',
    urlInfo6: '语法。缺省值是URI编码的。如果该值是一个完整的URL，您可以禁用使用的所有编码',
    tooltipInfo1: '指定链接工具提示的文本。',
    tooltipInfo2: '当用户将指针悬停在带有link的单元格上时，将显示此标题。使用与网址相同的变量。',
    removeRule: '删除规则',
    addColumnStyle: '添加列样式',
  },
  bargauge: {
    calc: '计算',
    orientation: '方向',
    templateVariables: '模板变量:',
  },
  checkLicense: {
    checkLicense: '检查License',
    welcome: '欢迎使用WISE-PaaS/Dashboard',
    nolicenseKey: '没有许可密钥或非法许可密钥',
    recheck: '重新检查',
    subscribeText: '请点击下面的按钮订阅',
    toSubscribe: '订阅',
    toLogin: '登录',
    subscribeText1: '成功订阅?登录',
    productInformation: '产品信息',
    productName: '产品名称',
    partNumber: '零件号',
    subscribedSpace: '订阅空间',
    datacenter: '数据中心',
    cluster: '集群',
    workspace: '工作空间',
    namespace: '名称空间',
  },
  testdata: {
    optional: '可选择的',
    lines: '线',
    step: '步长',
    stepInfo: '数据点之间的秒数。',
    csvValueInfo: `逗号分隔值。每个值可以是int、float或null，但不能是
        是空的。删除空格和尾随逗号。`,
    onCount: '数量',
    onCountInfo: `一个循环中值的个数。在周期的开始应该有on值。`,
    offCount: '数量',
    offCountInfo: '周期内的off值个数。',
    onValue: '值',
    onValueInfo: 'on的值可以是int、float或null。',
    offValue: '值',
    offValueInfo: 'off的值可以是int、float或null。',
    speed: '速度',
    spread: '扩散',
    noise: '噪波',
    bands: 'Bands',
    fetchURL: '获取URL',
    annotationScenario: '注释的场景',
    setup: '设置',
    setupText: '有关设置可重复测试环境的更多信息,请参阅github。',
    seriesCount: '序列个数',
    Address: '地址',
    Value: '值',
    Longitude: '经度',
    Latitude: '纬度',
    startValue: '开始的值',
  },
  stackdriver: {
    Authentication1: `<h4>Stackdriver身份验证</h4>
        <p>有两种方法来验证Stackdriver插件-要么通过上传服务帐户密钥文件,
        要么通过自动从谷歌元数据服务器检索凭据。后一种选项仅在GCE虚拟机上运行Grafana时可用。</p>

        <h5>上传服务帐户密钥文件</h5>
        <p>首先您需要创建一个谷歌云平台(GCP)服务帐号
        获取您想要显示数据的项目。一个Grafana数据源与一个GCP项目集成。如果你想要可视化来自多个GCP项目的数据那么你需要为每个GCP项目创建一个数据源。
        </p>
        <p>
          <strong>监控查看器</strong> 角色提供了Grafana需要的所有权限。 下面的API需要在GCP上
          启用数据源才能工作 <a class="external-link" target="_blank" href="https://console.cloud.google.com/apis/library/monitoring.googleapis.com">
          监控API</a>
        </p>

        <h5>GCE默认的服务帐户</h5>
        <p>如果Grafana运行在谷歌计算引擎(GCE)虚拟机上，那么Grafana可以
        从元数据服务器自动检索默认的项目id和身份验证令牌。为了让其生效，您需要确保您有一个服务帐户，该帐户被设置为虚拟机的默认帐户
        机器，并且服务帐户已被授予对Stackdriver监视API的读访问权。
        </p>

        <p>关于如何创建服务帐户的详细说明可以在 <a class="external-link" target="_blank"
            href="http://docs.grafana.org/datasources/stackdriver/">
            在这个文档</a>找到。
        </p>`,
    authentication: '身份认证',
    authenticationInfo: `上传您的服务帐户密钥文件或粘贴文件内容。该文件内容将被加密并保存在Grafana数据库中。`,
    authenticationType: '认证类型',
    uploadServiceAccount: '上传服务帐户密钥文件',
    pasteServiceAccount: '或粘贴服务帐户密钥JSON',
    uploadedKeyDetails: '上传关键细节',
    project: '工程',
    clientEmail: '客户电子邮件',
    tokenURI: 'Token URI',
    privateKey: '私钥',
    resetServiceAccountKey: '重置服务帐户密钥',
    resetInfo: '重置清除上传的密钥，并上传新的文件。',
    saveChanges: '不要忘记在上传文件后保存您的更改。',
    verifyTest: '通过单击保存 &测试验证GCE默认的服务帐户',
    service: '服务',
    selectServices: '选择服务',
    selectMetric: '选择指标',
    groupBy: '分组依据',
    aggregation: '聚合',
    selectReducer: '选择 Reducer',
    advancedOptions: '高级选项',
    aligner: '调整器',
    selectAlignment: '选择调整方式',
    alignmentPeriod: '校准周期',
    aliasBy: '别名',
    aliasPatterns: `<h5>别名模式</h5>通过使用别名模式，以任何方式格式化图例键。
        <br /> <br />举例:`,
    aliasPatterns1: `结果: &nbsp;&nbsp;<code>cpu/usage_time - server1-europe-west-1</code><br />
        <br /><strong>模式</strong>`,
    aliasPatterns2:
      `<ul><li><code>{${'{{metricDescriptor.type}}'}}</code> = 指标类型 e.g.compute.googleapis.com/instance/cpu/usage_time</li>` +
      `<li><code>{${'{{metricDescriptor.name}}'}}</code> = 指标的名称部分 e.g. instance/cpu/usage_time</li>` +
      `<li><code>{${'{{metricDescriptor.service}}'}}</code>= 指标的服务部分 e.g. compute</li>` +
      `<li><code>{${'{{metricDescriptor.label.label_name}}'}}</code> = 指标元数据标签 e.g.metricDescriptor.label.instance_name</li>` +
      `<li><code>{${'{{resource.label.label_name}}'}}</code> = 资源元数据标签 e.g. resource.label.zone</li>` +
      `<li><code>{${'{{bucket}}'}}</code> = 在Dashboard中使用热图时，用于分配指标的周期边界</li></ul>`,
    annotationInfo1: `注释查询格式`,
    annotationInfo2: `注释是一个覆盖在图表上的事件。注释渲染的开销很大，所以限制返回的行数很重要。`,
    annotationInfo3: `标题和文本字段支持模板，并可以使用查询返回的数据。例如，标题字段可以有以下文本:`,
    annotationInfo4: `有值:`,
    annotationInfo5: `举例结果:`,
    annotationInfo6: `metric/point的值`,
    annotationInfo7: `类型 例如`,
    annotationInfo8: `metric的名称部分 例如.`,
    annotationInfo9: `metric的服务部分 例如.`,
    annotationInfo10: `Metric标签元数据 例如.`,
    annotationInfo11: `标签元数据 例如.`,
  },
  prometheus: {
    scrapeInterval: 'Scrape间隔',
    scrapeTooltip: `将其设置为Prometheus配置文件中定义的全局scrape间隔。这将用作Prometheus步骤查询参数的下限。`,
    queryTimeout: '查询超时',
    queryTimeoutTip: '设置Prometheus查询超时时间。',
    HTTPMethod: 'HTTP方法',
    HTTPMethodTip: '指定查询Prometheus的HTTP方法。(POST仅在Prometheus>= v2.1.0中可用)',
    misc: '其他项',
    customQueryParameters: '自定义查询参数',
    validation: '值无效，您可以使用带有时间单位说明符的数值: y, M, w, d, h, M, s',
    customQueryTip: '向parameters或Thanos查询添加自定义参数。',
    customQueryPlace: `举例: max_source_resolution=5m&timeout=10`,
    noMetricsFound: '(没有发现指标)',
    loadingMetrics: '加载指标...',
    promQLCheatSheet: 'PromQL备忘单',
    enterPromQLQuery: '输入一个PromQL查询',
    legendTip: `使用名称或模式控制时间序列的名称。例如，{{hostname}}将被替换为标签主机名的标签值。`,
    legendFormat: '图例格式',
    minStep: '最小步长',
    minStepTip: `根据时间范围和面板宽度为自动处理留出空白。注意，查询中使用的实际日期将被调整为间隔步长的倍数。`,
    instant: '即时',
    linkGraphInPrometheus: '链接到Prometheus的图表',
    CHEATTitle1: '请求速率',
    CHEATLabel1: `给定一个HTTP请求计数器，该查询计算过去5分钟内每秒的平均请求速率。`,
    CHEATTitle2: `请求延迟的95%`,
    CHEATLabel2: `计算5分钟窗口中HTTP请求速率的第95个百分比。`,
    CHEATTitle3: `告警发射`,
    CHEATLabel3: `总结了过去24小时内发出的警报。`,
    searchExpression: '搜索表达式',
    step: '步',
    fieldFormats: '字段格式',
    otherOptions: '其他选项',
    ALERTS: '告警',
    alertname: '告警名称',
    tagLabel: '标签1,标签2',
    instance: '实例',
    otherOptionsTip: `时间戳的单位为毫秒。如果序列值的单位是秒，则将其范围向量乘以1000。`,
    seriesValueTimestamp: '序列值作为时间戳',
  },
  postgres: {
    schema: '模式',
    schema_: '模式',
    SSLMode: 'SSL模式',
    SSLModeInfo: '这个选项决定一个安全的SSL TCP/IP连接是否或以什么优先级与服务器协商。',
    configured: '配置的',
    versionInfo: `这个选项控制PostgreSQL查询构建器中可用的函数。`,
    timescaleDB: '时间量程DB',
    Help: `<a href="https://github.com/timescale/timescaledb" class="pointer" target="_blank">时间量程DB</a>
        是作为PostgreSQL扩展构建的时间序列数据库。如果启用，WISE-PaaS/Dashboard将使用<code>time_bucket</code>
        在<code>$__timeGroup</code>宏指令并在查询生成器中显示TimescaleDB特定的聚合函数。`,
    minTimeIntervalInfo: `时间间隔设置自动组的下限。建议设置为写频率，
        例如<code>1m</code> 如果你的数据每分钟都被写入。`,
    userPermission: `<h5>用户权限</h5>
		<p>数据库用户应该只被授予要查询的指定数据库和表上的SELECT权限。
        WISE-PaaS/Dashboard不验证查询是否安全，因此查询可以包含任何SQL语句。例如，这样的语句<code>DELETE FROM user;</code>和
        <code>DROP TABLE user;</code>将被执行。为了防止这种情况发生，我们<strong>强烈</strong>建议您创建一个特定的PostgreSQL用户，并限制其权限。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">时间序列:\n` +
      `- 返回列名为<i>time</i> (UTC时间，单位为秒或时间戳)\n` +
      `- 返回以数字类型作为值的列(s)\n` +
      `可选:\n` +
      `  - 返回列名为<i>metric</i>来表示系列名称。\n` +
      `  - 如果返回多个值列，metric列作为前缀。\n` +
      `  - 如果没有metric列，则使用值列的列名作为系列名\n\n` +
      `时间序列查询的结果集需要按时间排序。\n\n` +
      `表:\n` +
      `- 返回任意一组列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; “time”列\n` +
      `- $__timeEpoch -&gt; 提取(从列中)作为“time”列\n` +
      `- $__timeFilter(column) -&gt; 在时间'2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'之间的列\n` +
      `- $__unixEpochFilter(column) -&gt;  列 &gt;= 1492750877 并且列 &lt;= 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 并且列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column,'5m'[, fillvalue]) -&gt; (提取(从列中)/300)::bigint*300\n` +
      `     通过设置fillvalue, WISE-PaaS/Dashboard将根据间隔填充缺失的值\n` +
      `     fillvalue可以是一个文字值，NULL或previous;previous将填充之前看到的值，如果还没有看到，则为NULL\n` +
      `- $__timeGroupAlias(column,'5m') -&gt; (提取(从列中)/300)::bigint*300 作为 "time"\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; floor(column/300)*300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; floor(column/300)*300 作为 "time"\n\n` +
      `使用$__timeGroup分组和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroup(date_time_col, '1h'),\n` +
      `  sum(value) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY time\n` +
      `ORDER BY time\n\n` +
      `或者使用这些指令构建你自己的条件语句，它们只返回值:\n` +
      `- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__unixEpochFrom() -&gt;  1492750877\n` +
      `- $__unixEpochTo() -&gt;  1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp:
      `
        <pre class="gf-form-pre alert alert-info"><h6>注释查询格式</h6>
注释是一个覆盖在图表上的事件。 查询每行最多可以有三列，` +
      `时间列是强制性的。 注释渲染的开销很大，所以限制返回的行数很重要。

- 列的别名: <b>time</b> 获取注释事件时间。 使用epoch time或任何本机日期数据类型。
- 列的别名: <b>text</b> 获取注释文本
- 列的别名: <b>tags</b> 获取注释文本标签。 这是一个逗号分隔的标记字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; "time" 列
- $__timeEpoch -&gt; 提取(从列中)作为 "time"列
- $__timeFilter(column) -&gt; 在时间 '2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'之间的列
- $__unixEpochFilter(column) -&gt;  列 &gt;= 1492750877 并且列 &lt;= 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 并且列 &lt;= 1494497183142514872

或者使用这些指令构建你自己的条件语句，它们只返回值:
- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'
- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'
- $__unixEpochFrom() -&gt;  1492750877
- $__unixEpochTo() -&gt;  1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
		</pre>`,
  },
  cloudDatasource: {
    nameDetail: 'CloudWatch 详细信息',
    authPro: '验证提供者身份',
    tip: '提示:凭据配置文件名称，如〜/.aws/credentials中所指定，默认保留空白.',
    creName: '凭证配置文件名称',
    keyId: '访问密钥的身份标识号',
    secretKey: '秘密访问密钥',
    ranTip: '承担角色的ARN',
    defaultRegion: '默认区域',
    customMet: '自定义指标',
    regTip: '指定区域,例如对于美国西部(俄勒冈州),请使用“ us-west-2”作为区域.',
    customTip: '自定义指标的命名空间.',
    annotationProfile: '前缀匹配',
    annotationAction: '行动',
    alarmName: '警报名称',
    region: '地区',
    dimensions: '尺寸',
    info: 'Id可以包含数字，字母和下划线，并且必须以小写字母开头.',
    expression: '表达式',
    minPro: '最小时间',
    minTime: '点之间的最小间隔（以秒为单位）',
    aliasVar: '别名替换变量:',
    selectReg: '选择地区',
    nameSpace: '名称空间',
    selectName: '选择名称空间',
    metricName: '指标名称',
    selectMetricName: '选择指标名称',
    idTip: 'Id可以包含数字，字母和下划线，并且必须以小写字母开头.',
    expressionTip:
      '(可选）您可以在此处添加表达式。 请注意，如果正在使用引用其他查询的数学表达式，则将无法基于该查询创建警报规则',
    aliasTip:
      '别名替换变量:{{metric}}, {{stat}}, {{namespace}}, {{region}}, {{period}}, {{label}}, {{YOUR_DIMENSION_NAME}}',
    match: '完全匹配',
    matchTip: '仅显示与所有定义的维度名称完全匹配的指标',
    period: '期间',
    periodTip: '点之间的最小间隔以秒为单位',
    queryPro: '查询预览',
    dataId: '指标数据查询ID',
    dataQuery: '指标数据查询表达式',
  },
  elaDatasource: {
    elaDetail: 'Elasticsearch 详细信息',
    indexName: '索引名称',
    indexPlace: 'es-索引-名称',
    pattern: '模式',
    timeField: '时间字段名称',
    maxDatapoint: '最大并发请求数',
    minInter: '最小时间间隔',
    intervalTip: '值无效，您可以将数字与时间单位说明符一起使用: y, M, w, d, h, m, s',
    tipBefore: '按时间间隔自动分组的下限,建议设置为写入频率，例如',
    tipEnd: '如果您的数据每分钟写入一次.',
    massName: '消息字段名称',
    levelName: '级别字段名称',
    log: '日志',
    fieldMap: '字段映射',
    minCount: '最小文件数',
    timEdge: '修剪边缘',
    trmTip: '修剪时间序列数据点上的边缘',
    offSet: '偏移',
    offTip: '将每个存储桶的起始值更改为指定的正（+）或负偏移（-）持续时间，例如1h表示一个小时，或1d表示一天',
    orderBy: '订购依据',
    mis: '缺失',
    misMas: '缺失参数定义了应如何处理缺失值的文档。 默认情况下，它们将被忽略，但也可以将它们视为具有值',
    lucQuery: 'Lucene查询',
    pre: '精度',
    preTip: 'Elasticsearch v5.0及更高版本:脚本语言不难,采用',
    preTip2: 'Elasticsearch v5.0之前版本：如果未更改，默认情况下脚本语言为Groovy。 供Groovy使用',
    preEnd: '引用变量',
    predict: '预测',
    pres: '百分比',
    precisTh: '阈值精确度',
    elaTip: '单击以切换显示/隐藏指标',
    filterQueries: '过滤查询',
  },
  grafanaDatasource: {
    filterBy: '筛选依据',
    dashboardType: '仪表盘:这将获取整个仪表盘的注释和警报状态更改，并仅在事件源面板上显示它们.',
    tagType: '标签:这将获取与标签过滤器匹配的所有注释事件.',
    maxLimit: '最大限制',
    annoTip:
      '默认情况下,WISE-PaaS/Dashboard仅显示与查询中所有标签匹配的注释,启用此选项将返回与查询中的任何标签匹配的注释',
    aTag: '在此处输入为"foo"的标签将匹配',
    fooTag: '注释标签"foo"',
    annoKey: '格式为"foo:bar"的注释键值标签',
    queryName: '测试数据:随机数',
  },
  azureDatasource: {
    azureDetial: 'Azure监视器详细信息',
    azureCloud: 'Azure云',
    cloudTip: '选择Azure云.',
    directId: '目录（租户）编号',
    clientId: '应用程序（客户端)编号',
    clientSert: '客户机密',
    defaultDesc: '默认订阅',
    loadSub: '加载订阅',
    appDetail: '应用程序见解详细信息',
    apiKey: 'API密钥',
    appId: '应用程序编号',
    logDetail: 'Azure日志分析API详细信息',
    logTip: '与Azure Monitor API相同的详细信息',
    defaultWork: '默认工作区',
    loadWork: '加载工作区',
    defaultTip: '为Azure日志分析查询选择默认/首选工作区.',
    workTip: '工作区是从上面选择的默认订阅中提取的.',
    metricName: '度量标准命名空间',
    timeGra: '时间粒度',
    autoInterval: '自动间隔',
    dimen: '规模',
    eq: '等于',
    legendFormat: '图例格式化',
    aliasPatterns: '别名模式(有关更多信息，请参见帮助)',
    shortCut: '(运行查询: Shift+Enter, 触发建议: Ctrl+Space)',
    formatAs: '格式',
    rowQuery: '原始查询',
    helpMas: `表格类型格式:
      --返回任何一组列
      格式为时间序列:
      -需要类型为datetime的列
      -返回具有数字数据类型作为值的第一列
      -(可选：返回具有字符串类型的第一列以表示系列名称。如果未找到任何列，则将value列的列名称用作系列名称)
      时间序列查询示例:
      Azure活动
      | 其中$__timeFilter()
      | 按类别汇总bin()，bin(TimeGenerated，60分钟)
      | 按TimeGenerated升序排序
      巨集:
       -$__timeFilter()->datetime>=(2018-06-05T18:09:58.907Z)和TimeGenerated <= datetime(2018-06-05T20:09:58.907Z）
       -$__timeFilter(datetimeColumn) -> datetimeColumn >= datetime(2018-06-05T18:09:58.907Z)和datetimeColumn <= datetime(2018-06-05T20:09:58.907Z)
       -$__escapeMulti($myTemplateVar) -> $myTemplateVar应该是包含非法字符的多值模板变量
       -$__contains(aColumn,$myTemplateVar) -> ($myTemplateVar)中的aColumn
         如果使用“全部”选项，则选中“包括所有选项”复选框,然后在"自定义所有值"字段中键入:全部,如果选择全部1==1
       或者使用这些仅返回值的内置变量来构建自己的条件:
       -$__timeFrom -> datetime(2018-06-05T18:09:58.907Z)
       -$__timeTo -> datetime(2018-06-05T20:09:58.907Z)
       -$__interval -> 5m
       例子:
       -| $__timeFilter
       -| TimeGenerated >= $__timeFrom和TimeGenerated <= $__timeTo
       -|按类别,bin(TimeGenerated,$__interval)汇总count()`,
    splitOn: '分裂',
    notSupport: '没有注释支持',
    annotationFormat: '注释查询格式',
    annotationTip: `注释是覆盖在图形上方的事件。查询每行最多可以有三列，datetime列是必需的。注释渲染很昂贵，因此限制返回的行数很重要。
       -具有日期时间类型的列。
       -别名为Text或text的列，用于注释文本
       -具有别名的列:标签用于注释标签.这应该返回逗号分隔的标签字符串，例如'标签1,标签2'
       巨集:
           -$__timeFilter() -> 时间生成 >= datetime(2018-06-05T18"09:58.907Z)和TimeGenerated <= datetime(2018-06-05T20:09:58.907Z)
           -$__timeFilter(datetimeColumn)-> datetimeColumn >= datetime(2018-06-05T18:09:58.907Z)和datetimeColumn <= datetime(2018-06-05T20:09:58.907Z）
           或者使用这些仅返回值的内置变量来构建自己的条件:
           -$__timeFrom -> datetime(2018-06-05T18:09:58.907Z)
           -$__timeTo -> datetime(2018-06-05T20:09:58.907Z)
           -$__interval -> 5m`,
    matchAny: '任意匹配',
  },
  graphDatasource: {
    graphDetail: 'Graphite 细节',
    topTip: '此选项控制Graphite查询编辑器中可用的功能.',
    mas1: '有不同类型的Graphite兼容后端.您可以在此处指定使用的类型.如果使用的是',
    mas2:
      '然后在此处选择.这将启用Metrictank特定的功能，例如查询处理元数据。Metrictank是针对Graphite和朋友的多租户时间序列引擎.',
    graphQuery: 'Graphite查询',
    graphEvent: 'Graphite事件标签',
    series: '系列',
    tagKey: '标签键',
    tagValue: '标签值',
    and: '和',
    function: '函数',
    or: '或者',
  },
  dashboardDatasource: {
    tipMas: '该仪表板没有其他面板。向其他面板添加查询，然后重试',
    resultMas: '使用面板结果',
  },
  influxdbDatasource: {
    influxdbDetial: 'InfluxDB详细信息',
    httpTip: `您可以使用GET或POST HTTP方法来查询您的InfluxDB数据库.POS方法允许您执行繁重的请求(带有大量WHERE子句),而GET方法将限制您，如果查询太大,则会返回错误.`,
    access: '数据库访问',
    accessTip: `为此数据源设置数据库不会拒绝对其他数据库的访问.InfluxDB查询语法允许在查询中切换数据库.例如在_internal或SELECT * FROM " _internal" .."database" LIMIT 10 中显示测量值`,
    accessMas: '为了支持数据隔离和安全性，请确保在InfluxDB中配置了适当的权限.',
    minInter: '最小时间间隔',
    intervalTip: `自动分组时间间隔的下限.建议设置为写入频率,例如,如果每分钟写入一次数据,则为1m.`,
    where: 'WHERE',
    select: '选择',
    slimit: '没有限制',
    place: '通过$timeFilter限制事件中选择文本个数为1000',
    filedMap: '字段映射',
    filedTip: '如果您的influxdb查询返回多个字段,则需要在下面指定列名.注释事件由标题、标签和附加文本字段组成.',
  },
  inputDatasource: {
    shareData: '共享数据:',
    enterCsv: '输入 CSV',
    infoBox: `此数据存储在数据源json中，并在对任何数据源的初始请求中返回给每个用户.这是输入一些值的合适位置.大型数据集将在其他数据源中表现更好.`,
    noteMas: '对此数据的更改将仅在刷新浏览器后反映出来.',
  },
  lokiDatasource: {
    maxLine: '最大行数',
    tip: `Loki查询必须包含返回的最大行数限制（默认值：1000）。增加此限制可为临时分析提供更大的结果集。如果显示日志结果时浏览器变慢，请减小此限制.`,
    deviceField: '派生字段',
    fieldTip: '派生字段可用于从日志消息中提取新字段并根据其值创建链接',
    hideMas: '隐藏示例日志消息',
    showMas: '显示示例日志消息',
    debugLog: '调试日志消息',
    placeholderMas: '在此处粘贴示例日志行以测试派生字段的正则表达式',
    tooltip: '用于解析和捕获日志消息的某些部分,您可以在模板中使用捕获的组.',
    enterQuery: '输入Loki查询',
    noLabel: '(未找到标签)',
    loadLabel: '加载标签...',
    logLabel: '日志标签',
  },
  datasource: {
    connectionLimits: '连接限制',
    maxOpen: '最大开放连接数',
    unlimited: '无限制的',
    maxOpeInfo1: `开放的数据库连接的最大数目。如果`,
    maxOpeInfo2: '最大空闲连接数',
    maxOpeInfo3: '大于0并且',
    maxOpeInfo4: '最大开放连接数',
    maxOpeInfo5: '小于',
    maxOpeInfo6: '那么',
    maxOpeInfo7: '会减少到匹配',
    maxOpeInfo8: '限制。如果设置为0，则对开放的连接数没有限制。',
    maxOpeInfo9: '如果数据库是共享类型，最大开放连接数不能超过100。',
    maxIdle: '最大闲置连接数',
    maxIdleInfo1: `空闲连接池中的最大连接数。如果`,
    maxIdleInfo2: `大于0，但小于`,
    maxIdleInfo3: `限制。如果设置为0，表示不保留空闲连接。`,
    maxIdleInfo4: '那么',
    maxLifetime: '最大使用期',
    maxLifetime1: '一个连接可以被重用的最大时间(以秒为单位)。如果设置为0，连接将永远被重用。',
    maxLifetime2: '这个值应该总是低于配置值',
    maxLifetime3: 'wait_timeout',
    maxLifetime4: '在MySQL.',
    minTimeInterval: `最小时间间隔`,
    minInfo1: `自动组按时间间隔设置的下限。例如，建议设置为写频率`,
    minInfo2: `如果你的数据每分钟都被写入`,
    FROM: '从',
    timeColumn: '时间列',
    metricColumn: '指标列',
    metricColumnInfo: `列用作值列的度量名称。`,
    SELECT: '选择',
    WHERE: `WHERE`,
    GROUPBY: '分组',
    ORDERBY: '排序',
    JOIN: '结合',
    ON: 'ON',
    formatAs: '格式',
    editSQL: '编辑SQL',
    queryBuilder: `查询生成器`,
    generatedSQL: '生成SQL',
    warning: '警告',
    warnText: `切换到查询生成器可能会覆盖原始SQL。`,
    dataSourceError: '数据源错误',
  },
  opentsdb: {
    aggregator: '聚合',
    aliasInfo: `使用像$tag_tagname替换标记值的部分别名`,
    metricName: '指标名称',
    seriesAlias: '系列别名',
    downSample: '下采样',
    downSampleInfo: `空白为自动，或例如 `,
    disableDownsampling: '禁用下采样',
    filtersInfo: `过滤器不能与标签一起使用, 两者都可以单独使用，但不能同时使用。`,
    key: '键',
    addFilter: '添加过滤器',
    tagsInfo: '请使用过滤器，标签在opentsdb 2.2中已弃用',
    addTag: '添加标签',
    rate: '比率',
    counter: '计数',
    counterMax: '最大计数',
    maxValue: '极最值',
    resetValue: '重置值',
    resetvalue: '重置值',
    explicitTags: '显式标签',
    metricsQuery: '指标查询',
    eventname: '事件.事件名',
    showGlobalAnnotations: '展示总体的查询?',
  },
  mysql: {
    userPermission: `<h5>用户权限</h5>
		<p>
            数据库用户应该只被授予要查询的指定数据库和表上的SELECT权限。
            WISE-PaaS/Dashboard不验证查询是否安全，因此查询可以包含任何SQL语句。例如，这样的语句<code>USE otherdb;</code>和
            <code>DROP TABLE user;</code>将被执行。为了防止这种情况发生，我们
			<strong>强烈</strong>建议您创建一个特定MySQL用户，并限制其权限。
			查阅<a class="external-link" target="_blank" href="http://docs.grafana.org/features/datasources/mysql/">MySQL数据源文档</a>获取更多的信息。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">时间序列:\n` +
      `- 返回列名为time或者time_sec(UTC时间), unix时间戳或任何sql原生日期数据类型。您可以使用下面的指令。\n` +
      `- 返回以数字类型作为值的列(s)\n` +
      `可选:\n` +
      `  - 返回列名为<i>metric</i>来表示系列名称。\n` +
      `  - 如果返回多个值列，metric列作为前缀。\n` +
      `  - 如果没有metric列，则使用值列的列名作为系列名\n\n` +
      `时间序列查询的结果集需要按时间排序。\n\n` +
      `表:\n` +
      `- 返回任意一组列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; UNIX_TIMESTAMP(列)作为time_sec\n` +
      `- $__timeEpoch(column) -&gt; UNIX_TIMESTAMP(列)作为time_sec\n` +
      `- $__timeFilter(column) -&gt; FROM_UNIXTIME(1492750877)和FROM_UNIXTIME(1492750877)之间的列\n` +
      `- $__unixEpochFilter(column) -&gt;  time_unix_epoch &gt; 1492750877 和 time_unix_epoch &lt; 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt; 列 &gt;= 1494410783152415214 和 列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column,'5m'[, fillvalue]) -&gt; cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed)\n` +
      `     通过设置fillvalue, WISE-PaaS/Dashboard将根据间隔填充缺失的值\n` +
      `     fillvalue可以是一个文字值，NULL或previous;previous将填充之前看到的值，如果还没有看到，则为NULL\n` +
      `- $__timeGroupAlias(column,'5m') -&gt; cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed) 作为 "time\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; 列 DIV 300 * 300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; 列 DIV 300 * 300 作为 "time"\n\n` +
      `使用$__timeGroup进行分组和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroupAlias(timestamp_col, '1h'),\n` +
      `  sum(value_double) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY 1\n` +
      `ORDER BY 1\n\n` +
      `或者使用这些指令构建你自己的条件语句，它们只返回值:\n` +
      `- $__timeFrom() -&gt; FROM_UNIXTIME(1492750877)\n` +
      `- $__timeTo() -&gt;  FROM_UNIXTIME(1492750877)\n` +
      `- $__unixEpochFrom() -&gt;  1492750877\n` +
      `- $__unixEpochTo() -&gt;  1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp: `
        <pre class="gf-form-pre alert alert-info"><h6>注释查询格式</h6>
注释是一个覆盖在图表上的事件。询每行最多可以有三列，<i>time</i> 或者 <i>time_sec</i>列是强制性的.
注释渲染的开销很大，所以限制返回的行数很重要。

- 列的别名: <b>time</b> 或者 <i>time_sec</i> 获取注释事件时间。使用epoch time或任何本机日期数据类型。
- 列的别名: <b>text</b> 获取注释文本
- 列的别名: <b>tags</b> 获取注释文本标签。 这是一个逗号分隔的标记字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; UNIX_TIMESTAMP(列) 作为 time (或者作为time_sec)
- $__timeEpoch(column) -&gt; UNIX_TIMESTAMP(列) 作为 time (或者作为time_sec)
- $__timeFilter(column) -&gt; FROM_UNIXTIME(1492750877) 到 FROM_UNIXTIME(1492750877)的列
- $__unixEpochFilter(column) -&gt;  time_unix_epoch &gt; 1492750877 并且 time_unix_epoch &lt; 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 并且列 &lt;= 1494497183142514872

或者使用这些指令构建你自己的条件语句，它们只返回值:
- $__timeFrom() -&gt; FROM_UNIXTIME(1492750877)
- $__timeTo() -&gt;  FROM_UNIXTIME(1492750877)
- $__unixEpochFrom() -&gt;  1492750877
- $__unixEpochTo() -&gt;  1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
		</pre>`,
  },
  mssql: {
    encrypt: '加密',
    encryptInfo: '确定安全的SSL TCP/IP连接是否或在何种程度上要与服务器协商。',
    encryptInfo1: `客户端和服务器之间发送的数据未加密。`,
    encryptInfo2: `客户端和服务器之间发送的数据在登录包之外不会被加密。(默认)`,
    encryptInfo3: `客户端和服务器之间发送的数据是加密的。`,
    encryptInfo4: `如果你使用的是旧版本的Microsoft SQL Server，比如2008和2008R2，你可能需要禁用加密才能连接。`,
    userPermission: `<h5>用户权限</h5>
		<p>
			数据库用户应该只被授予要查询的指定数据库和表上的SELECT权限。
			WISE-PaaS/Dashboard不验证查询是否安全，因此查询可以包含任何SQL语句。例如，这样的语句
			<code>USE otherdb;</code>和<code>DROP TABLE user;</code>将被执行。为了防止这种情况发生，我们
			<strong>强烈</strong>建议您创建一个特定MSSQL用户，并限制其权限。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">时间序列:\n` +
      `- 返回列名为time(UTC时间), unix时间戳或任何sql原生日期数据类型。您可以使用下面的指令。\n` +
      `- 返回的任何其他列都是时间点值。\n` +
      `可选:\n` +
      `  - 返回列名为<i>metric</i>来表示系列名称。\n` +
      `  - 如果返回多个值列，metric列用作前缀。\n` +
      `  如果没有找到名为metric的列，则使用值列的列名作为系列名称\n\n` +
      `时间序列查询的结果集需要按时间排序。\n\n` +
      `表:\n` +
      `- 返回任意一组列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; 列作为time\n` +
      `- $__timeEpoch(column) -&gt; DATEDIFF(second, '1970-01-01', column)作为time\n` +
      `- $__timeFilter(column) -&gt; 在'2017-04-21T05:01:17Z' 和 '2017-04-21T05:01:17Z'之间的列\n` +
      `- $__unixEpochFilter(column) -&gt; 列 &gt;= 1492750877 并且列 &lt;= 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 并且列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column, '5m'[, fillvalue]) -&gt; CAST(ROUND(DATEDIFF(second, '1970-01-01', column)/300.0, 0) as bigint)*300.\n` +
      `     通过设置fillvalue, WISE-PaaS/Dashboard将根据间隔填充缺失的值\n` +
      `     fillvalue可以是一个文字值,NULL或previous; previous将填充之前看到的值，如果还没有看到，则为NULL\n` +
      `- $__timeGroupAlias(column, '5m'[, fillvalue]) -&gt; CAST(ROUND(DATEDIFF(second, '1970-01-01', column)/300.0, 0) as bigint)*300 AS [time]\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; FLOOR(column/300)*300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; FLOOR(column/300)*300 AS [time]\n\n` +
      `使用$__timeGroup进行分组和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroup(date_time_col, '1h') AS time,\n` +
      `  sum(value) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY $__timeGroup(date_time_col, '1h')\n` +
      `ORDER BY 1\n\n` +
      `或者使用这些指令构建你自己的条件语句，它们只返回值:\n` +
      `- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__unixEpochFrom() -&gt; 1492750877\n` +
      `- $__unixEpochTo() -&gt; 1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp: `<pre class="gf-form-pre alert alert-info"><h6>注释查询格式</h6>
注释是一个覆盖在图表上的事件。查询每行最多可以有三列，<b>time</b>列是强制性的.注释渲染的开销很大，所以限制返回的行数很重要。

- 列的别名: <b>time</b> 获取注释事件时间。使用epoch time或任何本机日期数据类型。
- 列的别名: <b>text</b> 获取注释文本
- 列的别名: <b>tags</b> 获取注释文本标签。 这是一个逗号分隔的标记字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; 列 作为 time
- $__timeEpoch(column) -&gt; DATEDIFF(second, '1970-01-01', column) 作为 time
- $__timeFilter(column) -&gt; '2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'的列
- $__unixEpochFilter(column) -&gt; 列 &gt;= 1492750877 并且列 &lt;= 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 并且列 &lt;= 1494497183142514872

或者使用这些指令构建你自己的条件语句，它们只返回值:
- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'
- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'
- $__unixEpochFrom() -&gt; 1492750877
- $__unixEpochTo() -&gt; 1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
        </pre>`,
  },
  logoSetting: {
    orgName: '组织名称',
    srpFramePBLogo: '右上角出品方图标',
    srpFramePBLogoConf: '右上角出品方图标',
    loginPageBgConf: '登录页背景图配置',
    loginTopLogoConf: '登录框顶部logo配置',
    loginTopLogo: '登录框顶部logo',
    copyrightInfoConf: '登录页版权信息配置',
    copyrightInfo: '版权信息',
    copyrightTips: '此处填写登录页的版权信息文字内容，不填写则显示默认版权信息，填写为"null"则不显示版权信息',
    loginPageConf: '登录页配置',
    activateDes: '点击右侧激活按钮，即可刷新页面并激活logo设置功能进行保存。'
  },
};

export default zhCN;
