const zhTW = {
  public: {
    never: '絕不',
    center: '居中',
    login: '登錄',
    email: '郵箱',
    seen: '查看',
    name: '名稱',
    can: '能',
    username: '用戶名',
    editUser: '編輯用戶',
    create: '創建',
    dashboard: '儀表板',
    dashboards: '儀表板',
    folder: '文件夾',
    import: '導入',
    export: '導出',
    srpFrame: 'SRP-Frame',
    newSrpFrame: '新建SRP-Frame',
    newUser: '新用戶',
    addNewUser: '添加新用戶',
    exportCsv: '導出CSV',
    excelCSVDialect: 'Excel CSV 本地',
    toggleLegend: '切換圖例',
    text: '文本',
    text_: '文本',
    manage: '管理',
    home: '首頁',
    none: '毫無',
    exact: '精確的',
    divider: '分隔符',
    playlists: '播放列表',
    snapshots: '快照',
    explore: '探索',
    admin: '管理員',
    preferences: '偏好設置',
    password: '密碼',
    changePassword: '修改密碼',
    signOut: '登出',
    alerting: '告警',
    alert: '告警',
    alertRules: '告警規則',
    notificationChanels: '通知方式',
    configuration: '配置',
    datasources: '數據源',
    users: '用戶',
    team: '團隊',
    teams: '團隊',
    plugins: '插件',
    images: '圖片',
    apiKeys: 'API 密鑰',
    orgSetting: '組織設置',
    serverAdmin: '服務管理員',
    org: '組織',
    orgs: '組織',
    settings: '設置',
    stats: '統計',
    orgsexport: '組織導出',
    orgsImport: '組織導入',
    help: '幫助',
    changelog: '版本更新記錄',
    apiDoc: 'API 文檔',
    technicalDoc: '技術文擋',
    applicationDemo: '應用示例',
    platformUrl: '論壇',
    timeRange: '時間範圍',
    saveDashboard: '保存儀表板',
    duplicatePanel: '復制面板',
    duplicateCard: '複製卡片',
    remove: '移除',
    removePanel: '移除面板',
    addDatasource: '添加數據源',
    select: '選擇',
    test: '測試',
    delete: '刪除',
    deleteUser: '刪除用戶',
    back: '返回',
    userName: '用戶名',
    save: '保存',
    uiTheme: 'UI 主題',
    dark: '黑色',
    gray: '灰色',
    light: '白色',
    default: '默認',
    disabled: '禁用',
    utc: '世界標準時間',
    homeDashboard: '主頁儀表板',
    homeSrpFrame: '主頁 SRP Frame',
    timezone: '時區',
    organizations: '組織',
    newOrg: '新建組織',
    id: 'Id',
    newOrganization: '新建組織',
    orgName: '組織名稱',
    value: '值',
    value_: '值',
    exportDash: '導出儀表板',
    exportDatasouce: '導出數據源',
    exportSRPFrames: '導出SRP Frames',
    exportImages: '導出圖片',
    exportPreferences: '導出偏好',
    exportFile: '導出組織文件',
    browse: '瀏覽',
    user: '用戶',
    reset: '重置',
    invite: '邀請',
    inviteUser: '邀請用戶',
    loginUser: '登錄者',
    role: '角色',
    current: '當前',
    currentOrg: '當前組織:',
    sessions: '會話',
    lastSeen: '最後上線',
    loggedOn: '登錄',
    ipAddress: 'IP 地址',
    browserAndOs: '瀏覽器和操作系統',
    switchTo: '切換',
    newChannel: '新建途徑',
    type: '類型',
    Type: '輸入',
    management: '管理',
    permissions: '權限',
    systemConfigure: '系統配置',
    newLanguage: '新建語言',
    language: '語言',
    sysLanguage: '系統語言',
    edit: '編輯',
    general: '基本的',
    logo: '圖標',
    title: '標題',
    icon: '圖標',
    cancel: '取消',
    sendTest: '發送測試',
    newDashboard: '新建儀表板',
    newPanel: '新建面板',
    addQuery: '添加查詢',
    addPanel: '添加面板',
    to: '到',
    customTimeRange: '自定義時間範圍',
    refreshDashboard: '刷新儀表板',
    conflict: '沖突',
    saveOverwrite: '保存並覆蓋',
    update: '更新',
    searchMember: '搜索團隊',
    addMember: '添加成員',
    members: '成員',
    permission: '許可',
    yes: '是',
    no: '否',
    dashboardSettings: '儀表板設置',
    file: '文件',
    fileProgress: '進度',
    close: '關閉',
    overwrite: '覆蓋',
    error: '錯誤',
    uploader: '上傳者',
    prePage: '上一頁',
    nextPage: '下一頁',
    confirm: '確定',
    warn: '警告',
    upload: '上傳',
    path: '路徑',
    orgProfile: '組織概況',
    add: '添加',
    unsavedChanges: '未保存的更改',
    doYouSaveYourChanges: '您想保存更改嗎?',
    discard: '丟棄',
    newPlaylist: '新建播放列表',
    interval: '間隔',
    addDaashboards: '添加儀表板',
    starred: '收藏',
    Starred: '星標',
    tags: '標簽',
    view: '查看',
    load: '加載',
    enable: '使能',
    refresh: '刷新',
    api: '請求接口',
    visible: '可見',
    accumulative: '累加',
    link: '鏈接',
    limit: '限制',
    last: '歷時',
    main: '主頁',
    right: '右側',
    left: '左側',
    defaultLanguage: '默認語言',
    theme: '主題',
    sideMenu: '側邊菜單',
    addPermission: '添加權限',
    addPermissionFor: '添加權限',
    style: '樣式',
    links: '鏈接',
    JsonModel: 'Json Model',
    variable: '變量',
    variables: '變量',
    search: '搜索',
    newFolder: '新建文件夾',
    importDashboard: '導入儀表板',
    importFolder: '導入資料夾',
    target: '目標',
    folderImportSetting: '資料夾導入設定',
    clear: '清除',
    filterBy: '過濾',
    filter: '過濾',
    move: '移動',
    treeMenu: '樹形菜單',
    annotations: '註釋',
    new: '新建',
    queryName: '查詢名稱',
    dataSource: '數據源',
    enabled: '啟用',
    hidden: '隱藏',
    color: '顏色',
    query: '查詢',
    versions: '版本',
    notFound: '未找到',
    saveAs: '另存為',
    description: '描述',
    addTags: '添加標簽',
    editable: '可編輯的',
    deleteDashboard: '刪除儀表板',
    all: '所有',
    selected: '选中',
    selectedAll: '全選',
    selectedDefault: '默認選中',
    selectedColor: '選中顏色',
    change: '改變',
    importOverwrite: '導入(覆蓋)',
    publishedBy: '發布者',
    options: '選項',
    importFormDashboard: '從Json文件導入儀表板',
    info: '信息',
    url: '網址',
    tooltip: '提示信息',
    openInNewTab: ' 新標簽頁中打開',
    saveChanges: '保存變化',
    savecurrentTimeRange: '保存當前時間範圍',
    version: '版本',
    date: '日期',
    updatedBy: '更新者',
    notes: '註釋',
    restore: '恢復',
    latest: '最新的',
    comparing: '比較',
    duplicate: '副本',
    definition: '定義',
    option: '選項',
    label: '標簽',
    hide: '隱藏',
    values: '值',
    intervalOptions: '時間間隔選項',
    uptate: '更新',
    defaultValue: '默認值',
    regex: '正則表達式',
    sort: '排序',
    example: '例如',
    addOption: '添加選項',
    tags_: '標簽',
    line: '行',
    characters: '字符',
    saving: '保存中',
    shareDashboard: '分享 儀表板',
    share: '分享',
    more: '更多',
    inspect: '檢查',
    snapshot: '快照',
    report: '報表',
    copy: '復制',
    timeout: '超時',
    seconds: '秒',
    copyToClipboard: '復制到剪貼板',
    enter: '進入',
    backToDashboard: '返回儀表板',
    resetDashboard: '重置儀表板',
    axes: '坐標軸',
    leftY: '左Y軸',
    rightY: '右Y軸',
    show: '顯示',
    unit: '單位',
    scale: '比例',
    auto: '自動',
    decimals: '小數位數',
    mode: '模式',
    align: '對齊',
    level: '級別',
    legend: '圖例',
    width: '寬度',
    oddColor: '奇數行顏色',
    evenColor: '偶數行顏色',
    min: '最小值',
    max: '最大值',
    avg: '平均',
    total: '總數',
    from: '從',
    To: '到',
    metric: '指標',
    URL: '網址',
    adjustableFontSize: '可調節字體大小',
    cardOpacity: '卡片透明度',
    cardOpacityTips: '透明度值在0.1-1之間，值越小越透明',
    fontWeight: '字體粗細',
    adjustableFontSizeTip: '字體大小跟隨窗口大小調整',
    timeConversion: '時間轉換',
    openTitleUseE: '您可以使用快捷方式e打開面板標題',
    field: '字段',
    fontSize: '字體大小',
    prefix: '前綴',
    postfix: '後綴',
    bold: '加粗',
    decimalLegendTooltip: '覆蓋圖例和提示的自動小數位數精度',
    decimalsTooltip: '覆蓋軸的自動小數位數精度。',
    coloring: '配色',
    thresholds: '閾值',
    colors: '顏色',
    invert: '反轉',
    background: '背景',
    YMin: 'Y軸最小值',
    YMax: 'Y軸最大值',
    lineColor: '線顏色',
    fillColor: '填充顏色',
    valueMappings: '值映射',
    YAxis: 'Y軸',
    buckets: '周期',
    size: '大小',
    XAxis: 'X軸',
    dataFormat: '數據格式',
    format: '格式化',
    display: '顯示',
    scheme: '設計',
    space: '間隔',
    round: '圓角',
    histogram: '直方圖',
    columns: '列',
    time: '時間',
    order: '順序',
    addtags: '添加標簽',
    scenario: '腳本',
    alias: '別名',
    labels: '標簽',
    newValue: '新值',
    allValues: '所有值',
    customInterval: '自定義間隔',
    queries: '查詢',
    visualization: '可視化',
    cards: '卡片',
    repeating: '重復',
    repeat: '重復',
    titleMargin: '標題邊距',
    fontColor: '字體顏色',
    backgroundColor: '背景顏色',
    sidebarColor: '側邊欄顏色',
    scrollbarColor: '滾動條顏色',
    rule: '規則',
    for: '為了',
    timeFor: '持續',
    conditions: '條件',
    notifications: '通知',
    sendto: '發送到',
    message: '訊息',
    draggable: '可拖拽',
    height: '高度',
    imgHeight: '圖片高度',
    item: 'item',
    titleColor: '標題顏色',
    valueColor: '值的顏色',
    metrics: '指標',
    logs: '日誌',
    split: '分割',
    clearAll: '清除所有',
    runQuery: '運行查詢',
    gobackEsc: '返回(Esc)',
    newName: '新建名稱',
    copyTags: '復制標簽',
    recentlyViewed: '最近瀏覽',
    fonts: '字體',
    titleQuery: '標題查詢',
    maxItems: '最大項數',
    sortOrder: '排序順序',
    forText: '為',
    data: '數據',
    Auto: '自動',
    scroll: '滾動',
    dateFormat: '日期格式',
    colorMode: '顏色模式',
    choose: '選擇',
    base: '基數',
    addMapping: '添加映射',
    dataLinks: '數據鏈接',
    removePanelText: '您確定要移除此面板嗎?',
    embed: '嵌入',
    addName: '添加名稱',
    timeEnd: '結束時間',
    deprecated: '不推薦使用',
    groupBy: '分組',
    thenBy: '然後',
    script: '腳本',
    var: '變量',
    params: '參數',
    model: '模型',
    window: '窗口',
    service: '服務',
    subscription: '訂閱',
    resourceGroup: '資源組',
    namespace: '名稱空間',
    resourceName: '資源名稱',
    aggregation: '聚合',
    top: '頂部',
    workspace: '工作區',
    showHelp: '顯示幫助',
    rawQuery: '原始查詢',
    anonymous: '匿名',
    patterns: `模式`,
    resolution: '分辨率',
    fill: '填充',
    filters: '過濾器',
    connection: '連接',
    host: '主機',
    database: '數據庫',
    httpMode: 'HTTP 模式',
    formatAs: '格式',
    aliasBy: '別名',
    FROM: '從',
    GroupBy: '分組',
    orderBy: '訂購',
    desc: '降序',
    Limit: '限制',
    tz: '時區',
    note: '註意',
    databaseName: '數據庫名稱',
    user_: '用戶',
    details: '詳情',
    switch: '切換',
    filterByNameOrType: '通過名稱或類型來過濾',
    testing: '測試中...',
    unknownPlugin: '未知的插件',
    disable: '禁用',
    panel: '儀表板',
    datasource: '數據源',
    Changlog: '變更記錄',
    log: '日誌',
    loading: '正在加載',
    folderPermissions: '文件夾權限',
    confirmDelete: '確認刪除',
    Enhanced: '增強版',
    ReportUpgrade: '加購報表',
    Upgrade: '升級版',
    Standard: '標準版',
    Professional: '專業版',
    Advanced: '高階版',
    ProfessionalShared: '專業共享版',
    Lite: '精簡版',
    ProfessionalWA: '專業版-WA',
    CustomizedV1: '定製版 V1',
    number: '數字',
    numbers: '數字',
    signature: '簽名',
    signIn: '登入',
    failed: '失敗的',
    doing: '進行中的',
    wait: '等待中的',
    download: '下載',
    fromFolder: '原始檔案',
    targetFolder: '目標檔案',
    state: '狀態',
    success: '成功',
    timeLast: '過去',
    minute: '分鐘',
    hour: '小時',
    day: '天',
    month: '月',
    months: '月',
    days: '天',
    hours: '小時',
    minutes: '分鐘',
    CustomTimeRange: '自定義時間範圍',
    defaultTimeRange: '默認時間範圍',
    addTime: '添加自定義時間範圍',
    margin: '邊距',
    saveCurrentVariables: '保存當前變量',
    year: '年',
    second: '秒',
    setValueMappings: '設置值映射',
    addValueMapping: '添加一個值映射',
    setRangeMappings: '設置範圍映射',
    addRangeMapping: '添加範圍映射',
    panelJson: '面板 JSON',
    defaultCustom: '默認自定義',
    timeRangeCustom: '自定義時間範圍',
    millisecond: '毫秒',
    milliseconds: '毫秒',
    productsComparison: '版本比較',
    superiorPlugins: '精品插件',
    subscribe: '訂閲',
    pointSize: '點的大小',
    loginNamePlaceHolder: '郵箱或用戶名',
    standardLogin: '標準',
    LDAPusername: 'LDAP用戶名',
    emailTip: '請輸入郵箱',
    pwdTip: '請輸入密碼',
    incorrectTip: '郵箱或密碼錯誤',
    loginDesc: '登入到Dashboard',
    loginCloudDesc: '登入到線上Dashboard',
    alarm: '告警',
    audio: '音訊',
    position: '位置',
    yearPrefix: '前綴為年份',
    alarmSource: '告警來源',
    alarmType: '告警類型',
    activate: '激活',
    activatePage: '激活並刷新此頁面',
    preview: '預覽',
    fixedFontSize: '固定字體大小',
    activateSuccess: '激活成功',
    activateFail: '激活失败',
    activated: '已激活',
    orgInitManagement: '組織初始化',
    uploadFile: '文件上傳',
    deleteSuccess: '刪除成功',
    deleteFail: '刪除失敗',
    previewLoginPage: '登錄頁預覽',
    previewMmanufacturerIcon: '右上角出品方圖標預覽',
    noFileFound: '沒有發現文件',
    noFileMatch: '未找到與您的査詢匹配的檔案.',
    overwriteSameName: '覆蓋同名文件',
    synchronousOrgs: '一鍵同步',
    importToOrg: '組織同步',
    sureToOverwriteSameFile: '確定覆蓋同名檔案嗎？',
    jump: '跳過',
    findFileByName: '按名稱查找檔案',
    orgInitImport: '組織初始化同步',
    orgInitImportDesc: '將系統備份的組織初始化中的儀錶板、資料來源、SRP Frames、圖片及偏好導入至這個新建的組織中',
    currentOrgExport: '當前組織導出',
    currentOrgImport: '當前組織導入',
    importOrg: '--請選擇--',
    exportCurrentOrgFile: '導出當前組織文件',
    orgsExportDes: '此處為系統級的組織匯出，請選擇要匯出的組織進行匯出。',
    orgsImportDes: '此處為系統級的組織導入，請上傳文件進行導入。',
    widthAdjust: '寬度自適應',
    week: '周',
    weeks: '周',
    nameCol: '名稱列',
    valueCol: '數值列',
    enoughPanels: '面板數量已達最大',
  },

  expore: {
    dedup: '重復數據刪除 ',
    noDedup: '沒有重復數據刪除',
    noDedupExact: '對相同行的連續行進行重復數據刪除，忽略ISO日期時間。',
    noDedupNumbers: '忽略數字（例如IP地址，延遲）時相同的連續行的重復數據刪除。',
    noDedupSignature: '具有相同標點符號和空格的連續行的重復數據刪除。',
    noLogs: '找不到日誌',
    scanOlderLog: '掃描較舊的日誌',
    stopScan: '停止掃描',
    editModeBtn: '編輯模式按鈕',
  },

  time: {
    now: '現在',
    timeOptions: '時間選項',
    autoRefresh: '自動刷新',
    nowDelayNow: '現在延遲-',
    hidetimePicker: '隱藏時間選擇器',
    hidetimeRange: '隱藏時間範圍',
    hideCustomRange: '隱藏自定義範圍',
    hideRefreshing: '隱藏刷新',
    configQuickRanges: '配置快速範圍',
    last5minutes: '過去5分鐘',
    last15minutes: '過去15分鐘',
    last30minutes: '過去30分鐘',
    last1hour: '過去1小時',
    last3hour: '過去3小時',
    last6hour: '過去6小時',
    last12hour: '過去12小時',
    last24hour: '過去24小時',
    last2days: '過去2天',
    last7days: '過去7天',
    last30days: '過去30天',
    last90days: '過去90天',
    last6months: '過去6個月',
    last1year: '過去1年',
    last2year: '過去2年',
    last5year: '過去5年',
    yesterday: '昨天',
    daybeforeyesterday: '前天',
    thisdaylastweek: '上周的這一天',
    previousweek: '上周',
    previousmonth: '前一個月',
    previousyear: '前一年',
    today: '今天',
    todaysofar: '今天到現在為止',
    thisweek: '本周',
    thisweeksofar: '本周到現在為止',
    thismonth: '本月',
    thismonthsofar: '這個月到現在為止',
    thisyear: '今年',
    thisyearsofar: '今年到目前爲止',
    customTimeFormat: '自定義顯示格式',
    yesterday8hTotoday8h: '昨天8:00到今天8:00'
  },

  panelGeneral: {
    queryResult: '查詢結果',
    addQuery: '添加查詢',
    addExpression: '添加表達式',
    queryInspector: '查詢檢查器',
    querySetLabels: '使用key = value語法設置標簽：',
    stringInput: '字符串輸入',
    customIntervalTip: `值默認為空，會根據面板的顯示大小自動調整間隔；也可以自定義數據查詢間隔
    （單位支持ms，s，m，h，d，w，M，y，該數字可以自定義），例如1ms，2s，3m，4h，5d，6w，7M，8y ...`,
    relativeTime: '相對時間',
    hideTimeInfo: '隱藏時間信息',
    timeShift: '時間偏移',
    notValid: '無效的時間跨度',
    cacheTimeout: '緩存超時',
    cacheTimeoutTip: `如果您的時間序列存儲區具有查詢緩存，則此選項可以覆蓋默認的緩存超時。 指定一個以秒為單位的數值。`,
    panelTransparent: '面板透明度',
    SelfAdaption: '自适应',
    descriptionPlaceholder: '面板描述, 支持markdown和鏈接',
    maxPerRow: '每行最大值',
    repeatNote: '註意：您可能需要更改變量選擇才能看到實際效果',
    panelTitleStyle: '面板標題樣式',
    hidePanelTitle: '隱藏面板標題',
    panelMarginTip: '請輸入數字作為邊框的寬度',
    panelTitleScheme: '面板標題方案',
    predefinedStyles: '預定義樣式',
    fontGradient: '字體漸層',
    startGradientColor: '初始漸變顏色',
    endGradientColor: '結束漸變色',
    pillarColor: '柱子顏色',
    panelLinks: '面板鏈接',
    noAlertInfo: '面板未定義警報規則',
    createAlert: '創建警報',
    stateHistory: '狀態歷史',
    deleteAlert: '刪除警報',
    deleteAlertTip1: '您確定要刪除此警報規則嗎？',
    deleteAlertTip2: '您需要保存dashboard後才能使刪除生效',
    testRule: '測試規則',
    backQueries: '返回查詢',
    notSupportedAlert: '警報查詢不支持轉換',
    noStateChange: '沒有記錄狀態變化',
    collapseAll: '全部收縮',
    expandAll: '全部展開',
    evaluatingRule: '評估規則',
    copyToClipboard: '復制到剪貼板',
    deleteAlertHistory: '刪除警報歷史記錄',
    deleteAlertHistoryText: '您確定要刪除此警報的所有歷史記錄和註釋嗎？',
    clearHistory: '清除歷史記錄',
    last50Change: '最近50個狀態更改',
    evaluateEvery: '評估頻率',
    forTip: `如果警報規則已配置為持續，查詢違反了配置的閾值，則它將首先從正常轉到未決狀態。從正常轉到未決狀態Dashboard將不會發送任何通知。 警報規則的觸發時間超過“持續時間”後，它將更改為“告警”並發送告警通知`,
    noData: '無數據和錯誤處理',
    allNull: '如果沒有數據或所有值都為空',
    setStateTo: '將狀態設置為',
    stateError: '如果執行錯誤或超時',
    newTagName: '新標簽名稱...',
    newTagVal: '新標簽值...',
    addTag: '添加標簽',
    addCard: '添加卡片',
    noCardTitle: '面板未定義卡片規則',
    deleteCard: '刪除卡片',
    sureDeleteCard: '您確定要刪除此卡嗎？',
    dataTag: '數據標簽',
    dataShow: '數據顯示',
    imgUrl: '圖片鏈接',
    addCardItem: '添加卡片子項',
    PanleBackground: '面板背景',
    BackgroundImage: '背景圖片',
    HorizontalPadding: '面板橫向填充值',
    tip1: '請輸入一個數組作為面板橫向填充值',
    VerticalPadding: '面板縱向填充值',
    tip2: '請輸入一個數組作為面板縱向填充值',
    TopPadding: '標題上部填充值',
    tip3: '請輸入一個數組作為標題上部填充值',
    customTimeRange: '自定義時間區間',
    defaultTimeRange: '默認時間區間',
    addCustomTimeRange: '添加自定義時間區間',
    minute: '分鐘',
    hour: '時間',
    day: '天',
    month: '月份',
    tableView: '查看數據表',
    PanelTimeRefresh: '面板時間重繪',
    PanelTime: '面板時間',
    PanelRefresh: '面板重繪',
    PanelTimeShow: '面板時間顯示',
    PanelRefreshShow: '面板重繪顯示',
    PanelTimeColor: '面板時間顏色',
    PanelRefreshColor: '面板重繪顏色',
    PanelRefreshTextColor: '面板刷新文字颜色',
    PanelTimeTextColor: '面板刷新时间颜色',
    PanelBgColor: "面板背景顏色",
    valueCol: '數值列',
    value: '數值',
    metricItem: '指標項',
    panelTimeVariable: '面板時間關聯變數',
    PanelTimeRange: '前後時間範圍'
  },

  permissions: {
    isPermissions: '什麽是權限？',
    dashPermissions: `是指控制列表（ACL）模型用於限制對儀表板文件夾的訪問。用戶或團隊可以為文件夾或單個儀表板分配的權限。`,
    loadPermissions: '正在載入權限...',
    noPersssions: '未設置權限,只能由管理員訪問。',
    JsonModelDes: '下面的JSON是定義儀表板的數據結構。包括設置，面板設置和布局，查詢等。',
    settingsView: '找不到設置頁面',
    settingPageNotFound: '找不到設置頁面，或者您沒有訪問權限',
    makeEditable: '使可編輯',
    defaultPer: '默認權限',
    viewEvery: '每個人都有查看的權限',
    editEvery: '每個人都有編輯的權限',
    canViewDash: '可以查看儀表板',
    canEditDash: '可以新建, 編輯和刪除儀表板',
    canAdminDash: '可以新建或刪除權限而且可以可以新建, 編輯和刪除儀表板。',
  },

  variables: {
    onDashLoad: '儀表板加載完成',
    onTimeChange: '時間範圍變更',
    refreshButEnabled: '刷新按鈕可見',
    optionalDisplayName: '可選的顯示名稱',
    autoOption: '自動選項',
    varEmptyTitle: '還沒有變量',
    addVariable: '添加變量',
    varEmptyInfo: ` <p>
            變量開啟可以更好的和儀表板動態交互與互動. 您可以使用變量代替指標查詢中對服務器或傳感器名稱的硬編碼。
            變量在儀表板頂部顯示為下拉選擇框。通過這些下拉菜單很容易更改顯示在儀表板上的數據. 參考
            <a class="external-link" href="http://docs.grafana.org/reference/templating/" target="_blank">
                模板文檔
            </a>
            獲取更多信息
            </p>`,
    varDo: '變量有什麽作用？',
    stepcount: '步數',
    stepcountTip: '當前時間範圍應劃分多少次才能計算出值',
    minInterval: '最小時間間隔',
    minIntervalTip: '計算值不低於此閾值',
    valComma: '值用逗號分隔',
    selectionOptions: '選擇選項',
    multiValue: '多選',
    multiValueTip: '啟用同時選擇多個值',
    includeAlloption: '包含所有選項',
    previewofvalues: '值預覽',
    constantOptions: '常數選項',
    customOptionsTip: '您的指標前綴',
    customTypeDes: '手動定義變量值',
    textOptions: '文本選項',
    customOptions: '自定義選項',
    defaultVal: '默認值，如果有',
    queryOptions: '查詢選項',
    variableUptateText: '何時更新此變量的值。',
    queryPlaceholder: '指標名稱或標簽查詢',
    regexPlaceholder: '可選，如果要提取系列名稱或度量標準節點段的一部分。',
    sortPlaceholder: '如何對這個變量的值進行排序。',
    dataOptions: '數據源選項',
    instanceNameFilter: '實例名稱過濾器',
    instanceNameFilterTip: '正則表達式過濾器在變量值下拉列表中從中選擇數據源實例。 留下所有空白。',
    dependentOptions: '相關選項',
    dependentVar: '相關變量',
    addOption: '添加選項',
    variableItem: '變量子項',
    variableText: '變量文本',
    variableVal: '變量值',
    queryDes: '從數據源查詢中獲取變量值',
    queryValueGroup: '值組/標簽（實驗功能）',
    tagsQuery: '標簽查詢',
    tagValsQuery: '標簽值查詢',
    customAllVal: '自定義所有值',
    metricNameOrTag: '指標名稱或標簽查詢',
    showMore: '展示更多',
    defineTime: '定義時間間隔（例如1m，1h，1d）',
    datasourceTip: '使您能夠動態切換多個面板的數據源',
    constantTip: '定義一個隱藏的常數變量，對於要共享的儀表板中的度量前綴有用',
    adhocTip: '快速添加鍵/值過濾器',
    textboxTip: '定義一個文本框變量，用戶可以在其中輸入任意字符串',
    defineVarTip: '手動定義變量值',
    all: '全部',
    importVariables: '導入變量',
    selectFile: '請選擇xxx.xlsx文件.',
    orgOverwriteInfo: '以下內容與當前頁面已有的變數重複，請選擇是否覆蓋',
    fixDefaultValue: '固定默認值',
  },

  serverAdmin: {
    userSearchPlaceholder: '通過名稱/登錄名/電子郵件查找用戶',
    seenTip: '上次查看到現在時間',
    newOrgDes:
      '每個組織都有自己的儀表板、數據源和配置，不能在組織之間共享。一個用戶可能屬於多個組織，但在多租戶部署中最常使用多個組織。',
    settingDes: '配置完成後，請單擊右側的刷新按鈕, 配置生效。',
    totalDashboards: '儀表板總數',
    totalUsers: '用戶總數',
    activeUsers: '活動用戶(過去30天可見)',
    activeAdmins: '活動管理員(過去30天可見)',
    activeEditors: '活動編輯者(過去30天可見)',
    activeViewers: '活動觀看者(過去30天可見)',
    activeSessions: '活躍時間',
    totalOrgs: '組織總數',
    totalDatasources: '數據源總數',
    totalPlaylists: '播放列表總數',
    totalSnapshots: '快照總數',
    totalDashboardTags: '儀表板標簽總數',
    totalStarredDashboards: '已加星標儀表板總數',
    totalAlerts: '告警總數',
    totalAdmins: '管理員總數',
    totalEditors: '可編輯者總數',
    totalViewers: '可觀看者總數',
    selectOrg: '請選擇導出組織',
    exportOrgFile: '導出組織文件',
    startImport: '開始導入',
    importOverwrite: '導入 (覆蓋)',
    orgOverwriteInfo: '以下內容在當前org中重復，請選擇是否覆蓋',
    appOverwriteInfo: '以下內容與當前app重復，請選擇是否覆蓋！',
    startImportOrgInfo: '開始將數據導入到指定的org中。',
    startImportStruInfo: '開始將數據導入相同的結構。',
    systemAdmin: '系統管理員',
    logoutAllDevices: '從所有設備註銷用戶',
    userStatus: '使用者狀態',
    editOrg: '編輯組織',
    orgUser: '組織用戶',
    restartAppInfo: '配置變更，請重啟app服務',
    orgSearchPlaceholder: '通過名稱查找組織',
  },

  dashGeneral: {
    deleteDashProTitle: '不能刪除預配置的儀表板',
    deleteDashProText1: `此儀表板由Grafanas設置管理，無法刪除。 從配置文件將其刪除`,
    deleteDashProText2: `<i>查看<a class="external-link" href="http://docs.grafana.org/administration/provisioning/#dashboards" target="_blank">
        文檔</a>有關配置的更多信息</i>
        </br>
        文件路徑:`,
    deleteDashText: '您要刪除此儀表板嗎？',
    deleteDashText2: `這個儀表板包含 {alerts}告警. 刪除此儀表板也將刪除這些告警信息`,
    dashHasDeleted: '儀表板已刪除',
    hasDeletedText: '{title} 已被刪除',
    tagInfo: '按Enter鍵添加標簽',
    refreshInView: '可見視圖刷新',
    editableTip: '取消選中，然後保存並重新加載以禁用所有儀表板編輯',
    mobileOptions: '移動端配置',
    panelOptions: '面板配置',
    graphUseTip: '使用快捷鍵在選項之間循環：CTRL + O或CMD + O',
    graphTip: 'Graph 提示',
    rowToGroup: '行變組',
    rowToGroupTip: '行面板會自動生成為移動頁面上的組',
    gridColumnLevel: '網格列級別',
    gridColumnLevelTip: '如果從高等級切換到低等級，您需要保存配寘然後重新加載頁面',
  },

  srpFrame: {
    findSrpPlaceholder: '通過名稱查找SRP Frame',
    noSrpFrameInfo: '沒有匹配到查詢的SRP Frame',
    noSrpFrameFound: '沒有匹配到SRP Frame',
    srpHasSameName: '已存在相同名稱的SRP Frame',
    deleteSrpText: '您是否要刪除所選SRP Frame及其所有配置',
    deleteSrpsText: '您是否要刪除所選SRP Frame及其所有配置',
    manageSrpSubTitle: '管理SRP Frame及其權限',
    langManList: '語言管理列表',
    nosrpLangInfo: `<div>您尚未添加任何語言配置。</div>`,
    situationRoom: '戰情室預覽',
    singleDisplay: '單片式預覽',
    titleDes: '標題描述',
    logoLink: '左上角logo連結',
    powerLink: '右上角logo連結',
    menuList: '菜單列表',
    marquee: '跑馬燈',
    notice: '通知',
    alarmDialog: '告警彈框',
    showTime: '顯示時間',
    addAudio: '添加音訊配置',
    showTimeTip: '告警彈框多久后消失，預設一直顯示',
    enableMulti: '開啟多種告警',
    dispaly55: '一片式',
    situation: '三片式',
    deleteMenuTitle: '刪除菜單',
    deleteMenuText: '您確定要刪除此列表嗎？',
    autoplay: '輪播',
    autoPlayIterval: '輪播間隔時間',
    autoPlayUrl: '輪播網址',
    newFirstMenu: '新建第一級菜單',
    noMenuListInfo: `您尚未添加菜單列表。`,
    autoplayTip: `當更新自動播放的時間時，單位有s/m/h/d和never。`,
    fontColorTips: '功能表列文字顏色',
    selectColorTips: '功能表列選中文字顏色',
    selectedBgColor: "功能表列背景顏色",
    bgColorTips: '功能表列背景顏色',
    scrollColorTTips: '功能表列滾動條顏色',
    ScrollBorder: '隐藏滚动条边框',
    ScrollBorderTips: '隐藏滚动条边框，开启代表隐藏滚动条边框线',
    sidebarColorTips: '功能表列右側邊框顏色',
    menHoverTips: '功能表列懸停顏色',
    menuBgImgTips: '功能表列懸停背景圖片',
    menuListImgTips: '功能表列背景圖片',
    menuSideTips: '功能表列右側邊框圖片',
    menuIconOpenTips: '選單打開圖標',
    menuIconCloseTips: '選單關閉圖標',
    menuIconWidthTips: '選單打開圖標寬度，組織是px',
    menuIconHeightTips: '選單關閉圖標高度，組織是px',
    titleShow: '面板支持修改操作，如果需要在srp中支持修改則需要將其打開',
    addMenulist: '添加菜單項',
    editMenulist: '修改菜單項',
    refreshMarquee: `當更新跑馬燈刷新時間時，單位有s/m/h/d和never。`,
    refreshAlertNoticeTip: `當更新刷新時間時，單位有s/m/h/d和never。`,
    authType: '驗證類型',
    headerKey: '請求頭設定',
    ssoUrl: 'sso 地址',
    alertName: '告警名稱',
    alertTimeRange: '告警時間範圍',
    allAsRead: '全部標記為已讀',
    linkEnable: '鏈接啟用',
    rightTitle: '右側標題',
    rightUrl: '右側網址',
    bottomUrl: '底部網址',
    titleDisplay: '標題顯示',
    mainPageTip: '主頁對應於菜單列表的內容。',
    dashboardView: 'dashboard 視圖',
    closeToHome: '關閉跳轉到首頁',
    heightAdjust: '高度自適應',
    dashboardHeader: '儀表板頭部',
    dashboardHeaderAll: '儀表板頭部全選',
    userVisible: '用戶可見',
    userIconVisible: '用戶圖標可見',
    collapseSidemenu: '折疊菜單',
    expandSubmenu: '展開子菜單',
    expandlevel: '展開級數',
    sideWidth: '側邊寬度',
    sideDrag: '側邊可拖拽',
    srpFramesPermissions: 'SRP 權限',
    srpFramePerTip: `什麽是SRP權限?<br>是指使用訪問控制列表（ACL）模型來限制對SRP的訪問,</br>可以向用戶或團隊分配SRP的權限。`,
    srpSetting: 'SRP Frame 設置',
    srpNameExistInfo: 'SRP 名稱已經存在了',
    deleteSrpInfo: `您是否要刪除{srpName}及其所有配置`,
    deleteLanguage: '刪除語言',
    deleteLanguageInfo: '您確定要刪除這種語言？',
    selectUser: '選擇一個用戶',
    ViewallEvent: '查看所有事件',
    Markallasread: '全部標記為已讀',
    MenuLogobackColor: '菜單圖標背景色',
    AudioFrequency: '音訊',
    LogoutUrl: '登出鏈接',
    expandedShow: '顯示展開',
    expandedShowTip: '配置打開到關閉，一級標題中配置有Dashboard及URL會被刪除',
    titleFontSize: '標題字體大小',
    subTitleFontSize: '子標題字體大小',
    menuHeight: 'SRP選單高度',
    threeTitleFontSize: '三級標題大小',
    menuColor: '菜单颜色',
    gradualShow: '漸變',
    gradualStartColor: '漸變開始顏色',
    gradualEndColor: '漸變結束顏色',
    tipsColor: '提示框背景色',
    tipsShow: '提示框显示',
    searchInputShow: '蒐索框顯示',
    menuBgImg: '選單背景圖',
    menuListBgImg: '側邊欄背景圖',
    menuSideBg: '選單側邊背景圖',
    menuIconOpen: '選單開啟圖標',
    menuIconClose: '選單關閉圖標',
    menuIconWidth: '功能表圖示寬度',
    menuIconHeight: '功能表圖示高度',
    PanelTitleShow: '挿件頭部顯示',
    fontSizeTip: '字體單位結尾為px或者vw',
    teamSelected: '選擇團隊',
    clickClose: '點擊關閉',
    expanded: '展開',
    menuPermission: '菜單權限',
    srpVariables: 'SRP 變量',
    bgImg: '背景圖片',
    addBackSetting: '添加返回配置',
    backTitle: '返回標題',
    backUrl: '返回連結',
    backParameter: '返回參數',
  },

  configuration: {
    /* Datasources */
    datasourceEmptyTitle: '尚未定義數據源',
    datasourceProTip: '您可以通過配置文件定義數據源.',
    datasourceProTipLinkTitle: '了解更多',
    proTip: '特別提示',
    tsdb: '時間序列數據庫',
    logging: '日誌、文檔數據庫',
    cloud: '雲端',
    otherType: '其他',
    url: '網址',
    access: '訪問方式',
    line1Entry: '訪問模式控制如何處理對數據源的請求.',
    line2Entry: '如果沒有其他說明，應該是首選方式.',
    line3Entry: '代理訪問為默認模式：',
    line4Entry:
      '所有請求都將從瀏覽器發出到Grafana後端/服務器，後者再將請求轉發到數據源，' +
      '從而避免可能的跨域資源共享（CORS）要求。 如果選擇此訪問方式，則需要可以從grafana後端/服務器訪問該地址',
    line5Entry: '客戶端訪問模式:',
    line6Entry:
      '所有請求都將從瀏覽器直接向數據源發出，並且可能要遵守跨域資源共享（CORS）的要求。' +
      '如果選擇此訪問方式，則需要可以從瀏覽器訪問地址。',
    server: '服務端',
    defaultDatasource: '設置為默認數據源',
    defaultDatasourceTip: '在面板中選擇數據源時使用該名稱，在新面板中預先選擇了默認數據源',
    leftEntry: '你訪問的方式是',
    direct: '客戶端訪問(direct)',
    proxy: '代理訪問(proxy)',
    directRight: '這意味著需要從瀏覽器訪問該地址',
    proxyRight: '這意味著需要從grafana後端/服務器訪問該地址',
    specialTip: '指定完整的超文本傳輸協議地址（例如超文本傳輸協議：//你的服務地址：8080）',
    ssoUrl: '指定SSO地址',
    ssoTip:
      '如果鏈接域名不同於sso域名，是否將sso域名用作鏈接域名？例如，當它是https://xxxxxx.trial.hz.wise-paas.com.cn時，' +
      '您可以將https://api-sso-ensaas.hz.wise-paas.com.cn配置為sso網址 ，或者當它是內部網址時，您可以使用與內部網址對應的sso網址。.',
    ssoTipData: '請配置SSO網址，例如 https://api-sso-ensaas.hz.wise-paas.com.cn.',
    ssoUrlData: 'SSO地址',
    auth: '驗證方式',
    basicAuth: '基礎驗證',
    AdvancedList: '參數配寘',
    AdvancedLabel: '鍵',
    AdvancedValue: '值',
    withCredentials: '憑證驗證',
    credentialsTip: '憑據提示：是否應將跨站點請求發送憑據（例如cookie或auth標頭),即用當前登錄者信息訪問datasource.',
    anonymous: '匿名賬戶驗證',
    basicAuthDetails: '基本身份驗證詳細信息',
    advancedHttp: 'HTTP高級設置',
    advancedTip: '默認情況下，Grafana代理會刪除轉發的Cookie,通過指定名稱，設置轉發到數據源的cookie。',
    whitelistedCookies: '白名單Cookie',
    caCert: 'CA證書驗證',
    tlsAuth: 'TLS客戶端驗證',
    tlsTip: '需用於驗證自簽名TLS證書',
    skipTLS: '跳過TLS驗證',
    allowCleartextPasswords: '允許明文密碼',
    oAuth: '轉發OAuth驗證',
    oAuthTip: '將用戶上遊的身份驗證轉發到數據源(傳遞它們的訪問令牌).',
    tslAuthDetial: 'TLS身份驗證詳細信息',
    tslContent: 'TLS證書已加密並存儲在Grafana數據庫中.',
    caCertContent: 'CA證書',
    clientCert: '客戶端證書',
    clientKey: '客戶端密鑰',
    beginCre: '開始於 -----開始於證書-----',
    beginKey: '開始於---開始於使用RSA私鑰-----',
    handlError: '數據查詢錯誤處理',
    keepLebal: '保留上次正確的數據',
    chooseDataSourceType: '選擇一個數據源類型',
    wantDelete: '確定要刪除此數據源嗎?',
    dupQuery: '復制查詢',
    disAndEn: '禁用/啟用查詢',
    removeQuery: '移除查詢',
    undefinedError: '未定義的錯誤',
    HTTPError: 'HTTP 錯誤',
    HTTPErrorStatus: 'HTTP錯誤狀態',
    /*Users*/
    pendInvite: '待處理的邀請',
    sendInvite: '發送邀請將現有Grafana用戶添加到組織中',
    inviteEntry: '請邀請或添加用戶到該組織中',
    deleteUser: '確定要刪除用戶',
    /*Teams*/
    noHaveTeam: `您尚未創建任何團隊`,
    teamProTip: '將文件夾和儀表板的權限分配給團隊而不是用戶，以簡化管理',
    searchTeams: '搜索團隊',
    newTeam: '新建團隊',
    teamTip: '這是可選的，主要用於允許自定義團隊',
    teamSetting: '團隊設置',
    update: '更新',
    members: '成員',
    addMember: '添加成員',
    addTeamMember: '添加團隊成員',
    addToTeam: '添加到成員',
    subTitle: '管理成員和設置',
    selectTeam: '選擇一個團隊',
    noTeam: '未找到團隊',
    /*Plugins*/
    findMore: '前往Grafana.com上查找更多插件',
    mpTip: '還有插件未註冊，請在MP上重新啟動該應用程序',
    grafanaTip: '還有插件未註冊, 請重啟grafana-server.exe服務',
    uploadTime: '上傳時間',
    isRegister: '是否已註冊',
    pluginTip: '您上傳的文件正在存儲',
    regPlugin: '插件上傳 & 註冊',
    fileName: '文件名稱',
    deleteText: '你確定要刪除 {name} 插件嗎 ?',
    deleteText2: '如果刪除了，與它相關的儀表板將會出錯 !',
    selectZip: '請選擇插件文件（.zip的文件格式）',
    errorType: '文件格式不正確, 請選擇.zip格式文件',
    fileSize: '請選擇小於15M的插件',
    pluginUpload: '插件上傳',
    fileProgress: '上傳進度',
    findCatalog: '了解更多插件請前往WISE-PaaS Catalog',
    purchasedPlugins: '購買的插件',
    customPlugin: '自定義插件',
    /*Images */
    imageUpload: '圖片上傳',
    imageType: '圖片上傳格式錯誤,請上傳bmp, jpg, jpeg, png, gif, svg 格式的圖片.',
    picSize: '請上傳10M以內的圖片',
    imageName: '圖片名稱',
    copySuccess: '復制成功',
    toPage: '跳轉到',
    totalPage: '共',
    page: '頁',
    clickMes: '請單擊選擇按鈕',
    imageNameSame: '圖像名稱相同，是否上傳？',
    deleteConf: '您確定刪除這張圖片嗎?',
    copyDefeated: '復制失敗',
    copyTip: '請復制文件的路徑',
    /* APIKey */
    newAPiKey: '新建Api密鑰',
    apiTip: '您尚未添加任何API密鑰.',
    apiProTip: '請記住，您可以提供對其他應用程序的只讀API訪問。',
    addAPiKey: '添加Api密鑰',
    keyName: '密鑰名稱',
    tooltipText: 'api密鑰有效期。例如，如果密鑰將持續一天，則為1d。 所有受支持的單位是：s，m，h，d，w，M，y',
    liveTime: '有效時間',
    apiKeyCreated: '已創建API密鑰',
    key: '密鑰',
    keyMas1: '您將只能在這裏查看一次該密鑰!它不以這種形式存儲,所以一定要立即復制.',
    keyMas2: ' 您可以使用Authorization HTTP標頭對請求進行身份驗證，例如',
    existKey: '現有密鑰',
    keyExpires: '到期日期',
    configTip: '請在下面設置與當前組織相關的配置.',
    sysTip: '未啟用系統匿名，請聯系系統管理員以在系統配置中將其打開',
    orgAnno: '組織匿名配置',
    WeChat: 'We Chat',
    Sms: 'Sms',
    Smtp: 'Smtp',
    Host: '地址',
    User: '用戶名',
    Password: '密码',
    FromAddress: '創建地址',
    FromName: '創建名稱',
    SkipVerify: '跳過驗證',
    CertFile: '證書檔案',
    KeyFile: '金鑰檔案',
    orgRole: '組織權限',
    configChange: '配置變更',
    localbrowsertime: '本地瀏覽器時間',
  },

  reporting: {
    reporting: '報表',
    reports: '報表',
    tasks: '任務',
    newReport: '新建報表',
    editReport: '编辑报表',
    taskName: '編輯報表',
    reportTitle: '報表標題',
    schedule: '排程',
    selectedSchedule: '排程',
    scheduling: '排程',
    once: '一次性',
    deleteTask: '您確定刪除這個任務嗎?',
    editInfo: '編輯任務，跳轉到PDF列表頁面,可以暫停重啟任務',
    filterByName: '根據名稱查找',
    deleteFile: '您确定删除这个文件嗎?',
    deleteFiles: '您確定刪除這個文件嗎?',
    fileName: '文件名',
    reportBranding: '報表標誌',
    companyLogo: '公司圖標地址',
    docFooterInfo: `這個圖標會出現在報表的頁腳,支持的格式有:jpg,jpeg,bmp,png。</br>png格式的需要在URL的尾部加上fmt=png。`,
    emailBranding: '郵件標誌',
    footerLinkText: '頁腳鍊接文字',
    footerLinkUrl: '頁腳鍊接網址',
    sourceDash: '儀表板',
    sendEmail: '發送電子郵件',
    recipients: '收件者',
    multiEmail: '您可以添加多個郵箱地址,使用;分隔。',
    timeRangeInfo: '在報告中指定數據查詢的時間範圍，默認顯示為在儀表板中設置的時間範圍。',
    frequency: '頻率',
    taskType: '任務類型',
    taskInfo: '如果面板無法導出PDF，此面板位置顯示為空白；如果面板無法導出EXCEL，EXCEL中的不包含此面板的數據',
    layout: '佈局',
    pdfStyle: 'PDF 樣式',
    simpleGird: '單排顯示-每-行顯示一個面板。網格顯示-儀表板上一行可以顯示多個面板',
    simple: '單排',
    gird: '網格',
    messageInfo: '請檢查附件中的報告。如果發現任何問題，請訪問儀表板服務進行檢查。',
    monthly: '每月',
    weekly: '每週',
    daily: '每天',
    hourly: '每小時',
    immediately: '立刻',
    delayTime: '延遲時間',
    signleTaskMaxWaitTime: '最大等待時間',
    deleteType: '您確定刪除選中的類型下的所有文件嗎？',
    deleteTypeAndFile: '您確定刪除選中的類型和文件嗎？',
    deleteTypeDesc: '選中的類型下的文件都將被刪除',
  },

  navTreeConfig: {
    createFolderSubTitle: '創建一個新文件夾來組織您的儀表板',
    createImportSubTitle: '從Json文件導入儀表板',
    srpSubTitle: '管理SRP-Frame',
    dashboardsSubTitle: '管理儀表板和文件夾',
    exploreSubTitle: '探索您的數據',
    alertingSubTitle: '告警規則和通知',
    reportingSubTitle: '創建和管理的PDF和EXCEL報表',
    configurationSubTitle: '組織：',
    datasourcesDes: '添加和配置數據源',
    usersDes: '管理組織成員',
    teamsDes: '管理組織組',
    pluginsDes: '查看和配置插件',
    imagesDes: '查看和配置圖片',
    orgSettingDes: 'Organization preferences',
    apikeysDes: '創建和管理API密鑰',
    currentOrgSettingsDes: '當前組織設置',
    serverAdminSubTitle: '管理所有用戶和組織',
    keyboardShortcuts: '鍵盤快捷鍵',
    superiorPluginsSubTitle: '精品插件展示',
  },
  help: {
    ShortcutsTotal: '快捷鍵',
    mod: '模組',
    modDesc: 'Windows、Linux上的CTRL鍵,Mac上的CMD鍵',
    globalEntry: '總體',
    focusedPanel: '聚焦的面板',
    goHomeDashboard: '跳轉到主頁儀表板',
    goProfile: '跳轉到個人資料',
    openSearch: '打開搜索',
    ExitEntry: '退出編輯或者設置的面板',
    refreshAllPanel: '刷新所有面板',
    toggleEntry: '切換非活動/查看模式',
    kioskMode: '切換kiosk模式 (隱藏頂部導航)',
    expandAllRows: '展開所有行',
    collapseAllRows: '折疊所有行',
    autoFix: '切換自動調整面板（實驗功能）',
    toggleGraph: '切換分享十字準線',
    togglePanelsLegend: '切換所有面板圖例',
    togglePanelEditView: '切換到面板編輯模式',
    togglePanleFullscreen: '切換到面板全屏模式',
    openPanelShareModal: '打開面板共享模式',
    togglePanelLegend: '切換面板圖例',
    zoomOutTimeRange: '縮小時間範圍',
    moveTimeBack: '向後移動時間範圍',
    moveTimeForward: '向前移動時間範圍',
  },

  comparison: {
    function: '功能',
    professional: '專業版',
    standard: '標準版',
    standardEdge: 'Edge標準版',
    professionalEdge: 'Edge專業版',
    advanced: '高階版\n(WebAccess)',
    professionalWA: '專業版-WA\n(WebAccess)',
    enhanced: '增强版\n(iFactory)',
    lite: '精簡版\n(iFactory)',
    professionalDesc: 'Dashboard專業版',
    standardDesc: 'Dahboard標準版',
    standardEdgeDesc: '與IoT Edge綜合的Dahboard標準版',
    professionalEdgeDesc: '與IoT Edge綜合的Dashboard專業版',
    advancedDesc: '與WebAccess綜合的Dashboard高階版',
    professionalWADesc: '與WebAccess綜合的Dashboard專業版',
    enhancedDesc: '與iFactory綜合的Dashboard增强版',
    liteDesc: '與iFactory綜合的Dashboard精簡版',
    dashboardManage: 'Dashboard創建和管理',
    datasourceManage: '數據源創建和管理',
    alertNotification: 'Alert&Notification&Annotation',
    userManage: 'User/Team管理',
    innerPanel: '内置Panel插件',
    innerDatasource: '内置Datasource插件',
    onlyTestDB: '僅支持TestDB Datasource',
    onlyIotEdge: '僅支持IoT Edge Datasource',
    onlyWebAccess: '僅支持WebAccess Datasource',
    outerPanel: '外置Panel插件',
    outerDatasource: '外置Datasource插件',
    changeLogo: '自定義企業logo（Dashboard icon，非powered by WISE-PaaS）',
    SRPManage: 'SRP-Frame管理',
    uploadManage: '圖片、插件上傳管理',
    mobileTypesetting: '移動端排版',
    dashboardExport: 'Dashboard報表導出',
    multilingual: '多語言',
    dataImport: 'Dashboard資料備份導入',
    emailCounsel: '電子郵件咨詢',
    orderCounsel: '工單咨詢',
    onlineVideo: '在綫技術文檔和視頻教程',
    onlineCourse: '綫上專場培訓',
    onlineCustomizedCourse: '綫上定制化培訓',
    onlineRemoteSupport: '在綫遠程技術支持',
    wechatSupport: '微信技術支持',
    weekdaysService: '5*8響應技術問題',
    solution: '解決方案\n(iFactory)',
    solutionDesc: 'EHS或者TPM解決方案搭配的版本',
    restrictDatasource: '僅支持資產和警報中心等資料來源',
  },

  pluginsDesc: {
    function: '功能介紹',
    introduction: '簡介',
    complexDatatable: {
      introduction: 'Complex Table是一款可靈活配寘，滿足複雜多樣的表格，支持表格的反寫功能及各種靈活設定。',
      desc: {
        feature1: '支持表格行修改，添加，删除；',
        feature2: '支持表格整列數據的修改；',
        feature3: '支持各種告警的靈活設定',
        feature4: '支持自定義新增一列；',
      },
    },
    oracle: {
      introduction:
        '支持關聯式資料庫Oracle數據的接入，通過簡單的介面引導配寘，即可快速進行單錶，單視圖，以及多錶，多視圖之間的關聯、査詢。',
      desc: {
        feature1: '支持單錶、單視圖介面引導査詢、SQL語句査詢；',
        feature2: '支持多錶，多視圖之間級聯介面引導査詢、SQL語句査詢；',
        feature3: 'Oracle類型變數査詢支持介面化引導管道',
        feature4: 'Oracle支持動態變數査詢；',
      },
    },
    snowflake: {
      introduction:
        '支持Snowflake彈性資料倉庫數據的接入，通過簡單配寘連接資訊，即可便捷、快速接入其數據在Dashboard上進行呈現。',
      desc: {
        feature1: '支持靈活的連結資訊配寘；',
        feature2: '支持通過SQL査詢，進行數據呈現；',
        feature3: '請求支持動態變數査詢；',
      },
    },
    streetView: {
      introduction:
        'Street View Panel是一款用於顯示地圖詳細資訊的挿件，可詳細到街道的展示。支持對特定經緯度位置進行標記並顯示當前位置的數據，支持實时繪製軌跡圖，支持地圖上顯示熱圖資訊。',
      desc: {
        feature1: '支持世界範圍的地理位置座標；',
        feature2: '支持timeserie和table兩種資料類型；',
        feature3: '提供動態軌跡繪製功能；',
        feature4: '支持地圖疊加熱圖顯示效果；',
        feature5: '支持中心經緯度的設定；',
        feature6: '閾值顏色設定；',
      },
    },
    choropleth: {
      introduction:
        'Choropleth Map Panel是一款用於顯示各省份數據等級或分佈的地圖挿件。 此挿件支持兩種顯示模式，一種是各區域根據不同的資料顯示不同的顏色等級，並可標注氣泡顯示當前的數值。 另一種僅需要展示各區域的數值差异則以更加立體的效果顯示，同樣可標注氣泡顯示當前區域的數值，數據分佈一目了然。',
      desc: {
        feature1: '支持顏色等級和分佈兩種顯示模式；',
        feature2: '顏色等級模式支持顏色區間自定義；',
        feature3: '數據標注氣泡可支持樣式設定；',
      },
    },
    scatterMap: {
      introduction:
        'Scatter Map panel是一款用於顯示地理位置數據的美觀的世界地圖挿件。 可以對特定經緯度位置進行標記並顯示當前位置的數據，支持靈活的區域，邊界線等顏色設定和位置標記樣式的設定。',
      desc: {
        feature1: '支持世界範圍的地理位置座標；',
        feature2: '支持timeserie和table兩種資料類型；',
        feature3: '支持地圖中心經緯度，縮放等級設定，是否可拖拽的設定；',
        feature4: '散射，氣泡等的大小，顏色設定；',
        feature5: '閾值顏色設定；',
        feature6: '提供marker跳動標注顯示；',
        feature7: '提供水域，陸地，邊界，行政名稱的顏色修改；',
      },
    },
    hydrograph: {
      introduction:
        'Hydrograph Panel是一個用來顯示百分比數值的WISE-PaaS/Dashboard挿件，代表當前的占比情况。 該挿件使用動畫形式的波浪來展示百分比，效果炫酷。 支持域值和顏色的自定義，可以讓波浪在不同的數據下展示不同的顏色，搭配數值百分比顯示，直觀易懂。 其使用配寘簡單，效果炫酷。',
      desc: {
        feature1: '支持字體大小和保留小數點個數設定；',
        feature2: '支持自定義計算區間最大值，結合當前數據計算百分比；',
        feature3: '支持多域值和顏色設定，可根據需要添加不同的域值區間展示不同的業務含義',
        feature4: '圖形大小自我調整外部panel大小；',
      },
    },
    thermometer: {
      introduction:
        'Thermometer panel是WISE-PaaS/Dashboard的一個溫度計挿件。 該挿件可直觀的顯示溫度的數值和溫度的狀態，可用於任何需要展示溫度的場景中。',
      desc: {
        feature1: '支持Table和Timeserie資料來源，支持數據的統計值顯示（例如最大值、最小值、平均值、最新值等）；',
        feature2: '靈活的刻度設定支持最大最小刻度值設定，支持刻度區間設定；',
        feature3: '支持溫度的閾值區間自定義；',
        feature4: '支持字體的大小設定和溫度組織的設定；',
        feature5: '溫度計圖形顯示根據panel大小可自我調整調整；',
      },
    },
  },

  admin: {
    editProfile: '編輯個人資料',
    disableLoginTooltip: '登錄信息鎖定 - 在另一個系統中管理.',
    perferenceTooltip: '找不到想要的儀表板? 首先把儀表板收藏, 然後它應該就出現在這個選擇框中.',
    homeSrpFrameTooltip: '選擇SRP Frame的名稱和語言，然後就可以進入SRP Frame主頁',
    switchOrganization: '切換組織',
    changeYourPassword: '修改你的密碼',
    oldPassword: '舊密碼',
    newPassword: '新密碼',
    confirmPassword: '確認密碼',
    changePassword: '修改密碼',
    ldapEnabled: `當啟用ldap或auth代理身份驗證時，您無法更改密碼。`,
    chooseDefaultDashboard: 'Choose default dashboard',
    chooseDefaultSRPFrame: '選擇默認的SRP Frame',
  },
  alerting: {
    states: '狀態',
    howToAdd: '如何添加告警',
    pauseTitle: '暫停告警規則將阻止其執行',
    editAlertRule: '編輯告警規則',
    addingAlert: '添加一個警告',
    alertText1: '告警是可以在任何儀表板的圖形面板中的告警標簽中添加和配置，讓您使用現有查詢構建和可視化告警。',
    alertText2: '要持久保存警報規則更改，請記住保存儀表板。',
    okText: '正常',
    keepState: '保持最後狀態',
    alertText: '告警',
    forTextStatus: '状態',
    no_dataText: '無數據',
    pausedText: '暫停',
    pendingText: '等待',
    unknownText: '未知',
    forText: '持續了',
    newNoticeChannel: '新建通知方式',
    notificationMes: '通知消息詳細信息...',
    editNoticeChannel: '編輯通知方式',
    defaultSend: '默認(發送所有告警)',
    defaultSendTip: '對所有告警使用此通知',
    includeImage: '包括圖像',
    includeImageTip: '捕獲圖像並將其包含在通知中',
    disableMessage: '禁用解析消息',
    disableMessageTip: '禁用當告警狀態返回false時發送的解析消息[OK]',
    sendReminders: '發送提醒',
    sendRemindersTip: '為觸發的告警發送額外通知',
    sendReminderEvery: '發送每一個提醒',
    sendReminderEveryTip: '指明發出提醒的頻率。例如每隔30秒、1分鐘、10分鐘、30分鐘或1小時等。',
    sendReminderText: '在計算規則之後會發送警告提醒。因此，一個提醒永遠不會比一個配置的警報規則評估間隔更頻繁地發送。',
    removeAlertText2: `面板包括一個告警規則，刪除面板也將刪除告警規則`,
    toConfirm: '以確認',
    searchAlerts: '搜索告警',
    noHasAlert: '尚未定義任何通知規則.',
    addChannel: '添加規則',
    proTip: '您可以在告警通知中包括圖像.',
    errorTip: '該數據源不支持告警查詢',
    errorTip1: '警報查詢中不支持模板變量',
    errorTip2: '找不到任何指標查詢',
  },
  create: {
    convertToRow: '轉換為行',
    pasteCopiedPanel: '粘貼復制的面板',
    chooseVisualization: '選擇可視化',
    cycleViewMode: '視圖模式切換',
    timeRangeZoomOut: '時間範圍縮小',
    saveNameText: '在選定的文件夾中已經存在同名的儀表板。',
    saveNameText2: '您仍然想保存這個儀表板嗎?',
    saveVersionText: '有人更新了這個儀表板。',
    newDashboardFolder: '新建儀表板文件夾',
    startPlaylist: '開始播放列表',
    playlistsaved: '播放列表已保存',
    unableSavePlaylist: '無法保存播放列表',
    playlistDeleted: '播放列表已刪除',
    unableDeletePlaylist: '無法刪除播放列表',
    previousDashboard: '去上一個儀表板',
    stopPlaylist: '停止播放列表',
    nextDashboard: '去下一個儀表板',
    inNormalMode: '正常模式',
    inTVMode: 'TV 模式',
    withAutoFitPanels: '自動配合面板',
    inKioskMode: 'Kiosk 模式',
    playlistDescription: `播放列表會在儀表板的預選列表中循環顯示。 播放列表可能是建立情景意識的好方法，或者只是向團隊或訪問者展示您的指標。`,
    playlistEmpty: '播放列表為空，請在下面添加儀表板。',
    findDashboardsByName: '按名稱查找儀表板',
    addToPlaylist: '添加到播放列表',
    snapshotUrl: '快照路徑',
    external: '外部的',
    uploadJsonFile: '上傳. json文件',
    grafanaComDashboard: '儀表板',
    pasteGrafanaComDashboardUrlId: '粘貼儀表板url或id',
    couldNotFindDashboard: '找不到儀表板',
    orPasteJSON: '或者粘貼JSON',
    markAsFavorite: '標記為最喜愛的',
    addNoteDescribeChanges: '添加註釋來描述您的更改...',
    openOriginalDashboard: '打開原本的儀表板',
    openMobilePage: '打開手機頁面',
    shareLinkInfo: '創建到這個儀表板或面板的直接鏈接，使用下面的選項進行定制。',
    currentTimeRange: '當前時間範圍',
    templateVariables: '模板變量',
    snapshotDeleteText: '您確認想要刪除快照',
    shareSnapshotInfo: `快照是一種即時共享交互式儀表板的方式。
        創建後，我們<strong>剝離敏感數據</strong>，如查詢(度量、模板和註釋)和面板鏈接，
        只在儀表板中嵌入可見的度量數據和系列名稱。`,
    shareSnapshotInfo1: `請記住，你的<strong>快照可以被任何有鏈接並能到達URL的人</strong>查看。
        明智的分享。`,
    snapshotName: '快照名稱',
    expire: '到期',
    shareSnapshotInfo2: `如果收集儀表板指標需要很長時間，則可能需要配置超時值。`,
    localSnapshot: '本地的快照',
    copyLink: '復制鏈接',
    makeMistake: '你出現錯誤了嗎?',
    deleteSnapshot: '刪除快照。',
    exportsharingExternally: '導出用於外部共享',
    exportsharingTooltip: `對於在grafana.com上公開分享儀表板非常有用。將模板化數據源名稱。然後只能與特定的儀表板導入API一起使用。`,
    saveToFile: '保存到文件',
    viewJSON: '查看 JSON',
    clickButtonGenerateReport: '單擊按鈕生成報告',
    saveToPdf: '保存為pdf',
    sharePanel: '分享面板',
    directLinkRenderedImage: '直接鏈接渲染圖像',
    shareModalInfoText: `下面的html代碼可以粘貼在另一個網頁中。除非啟用了匿名訪問，否則查看該頁面的用戶需要被簽名到WISE-PaaS/Dashboard中以加載圖表。`,
    selectA: '選擇一個',
    dataSource: '數據源',
    uidValidationError: `在{folderTitle}文件中名稱為{dashboardTitle}的Dashboard有相同uid`,
    importUidValidationError: '在{folderTitle}文件中名稱為{dashboardTitle}的Dashboard有相同uid',
  },
  dashboards: {
    /*Home*/
    installGrafana: '安裝 WISE-IoTSuite/Dashboard',
    creatDatasource: '創建第一個數據源',
    addDatasource: '添加數據源',
    createDashboard: '創建第一個儀表板',
    newDashboard: '新建儀表板',
    inviteTeam: '邀請您的團對',
    addUsers: '添加用戶',
    installApp: '安裝應用程序 & 插件',
    explorePlugin: '探索插件庫',
    starredDashboard: '已加星標的儀表板',
    recentlyView: '最近瀏覽的儀表板',
    installedApp: '已安裝的應用程序',
    installedPanel: '已安裝的面板',
    installedDatasource: '已安裝的數據源',
    clearCurrentQuery: '清除當前搜索查詢和過濾',
    noDashFound: '沒有儀表板發現',
    noMatch: '未找到與您的查詢匹配的儀表板.',
    findByName: '按名稱查找儀表板',
    starred: '星標',
    filterByTag: '按標簽過濾',
    filterByStar: '按星標篩選',
    deleteText: '你想要刪除',
    deleteText1: '選定的文件夾和儀表板',
    deleteText2: '選定文件夾下的儀表板都將被刪除',
    deleteText3: '選定的文件夾和其下的儀表板',
    deleteText4: '選擇的儀表板',
    chooseDashboard: '選擇儀表板文件夾',
    moveMessage: '移動',
    moveToDash: '選定的儀表板到以下文件夾',
    updateOn: '更新於',
    uniqueMas: '唯一標識符(uid)',
    uniqueTip: ` 儀表板的唯一標識符（uid）可用於在多個已安裝WISE-PaaS/Dashboard之間唯一標識儀表板,uid允許使用一致的網址來訪問儀表板，
        因此更改儀表板的標題不會破壞任何指向該儀表板的書簽鏈接。`,
    sameName: '已有同名儀表板存在於此文件夾中',
    sameFolder: '具有相同名稱的文件夾或儀表板已在常規文件夾中存在',
    requiredName: '名稱是必須的',
    folderMas: '這是保留名稱，不能用於文件夾.',
    subTitleDashboard: '管理文件夾的儀表板和權限',
    forderSetting: '文件夾設置',
    /*Playlist */
    noPlayList: '尚未創建播放列表.',
    playTip: '您可以使用播放列表在電視上循環顯示面板，而無需用戶控制',
    createPlay: '創建播放列表',
    deletePlay: `確定要刪除播放列表{name}?`,
    editPlay: '編輯播放列表',
    creDashboard: '創建儀表板',
    manDashboard: '管理儀表板',
    moveTo: '將儀表板添加/移動到您的文件夾中',
    hasNoDashboard: '這個文件夾還沒有任何儀表板',
  },
  treeMenu: {
    openleftMenu: '打開左側功能表列',
    dataConfig: '資料配置',
    headersConfig: 'Headers 配置',
    generalConfig: '通用配置',
    defaultExpandedWidth: '默認展開寬度',
    initialGroup: '初始資產組',
    groupVariableAssociation: '資產組變量關聯',
    objectVariableAssociation: '資產變數關聯',
    selectAsset: '選中資產組',
    selectAssetObj: '選中資產',
    refreshVisible: '刷新可見',
    area: '區域',
    pleaseInputObjectGroupName: '請輸入資產組名稱',
    titleColor: '標題顏色',
    inputBgColor: '背景色',
    inputTxtColor: "文字顏色",
    inputBorderColor: "邊框顏色",
    backgroundColor: '背景顏色',
    fontColor: '字體顏色',
    menuActiveBgColor: '選中顏色',
    menuActiveFontColor: '選中文字顏色',
    menuScrollColor: '滾動條顏色',
    menuIconUrl: '功能表圖示地址',
    menuIconOpenUrl: '打開圖標地址',
    menuFontSize: '文字大小',
    menuFontSpacing: '文字間距',
    menuFontTips: '需要添加px組織',
    menuIconCloseUrl: '關閉圖標地址',
    treeMenuProperty: '査詢資產',
    treeMenuTagMultiple: '資產開啟多選',
    menuAll: '選擇所有',
    searchStyles: "蒐索框樣式",
    menuStyles: "選單樣式"
  },
  annotations: {
    emptyListCtaTitle: '未添加自定義註釋查詢',
    buttonTitle: '添加註釋查詢',
    infoBoxTitle: '什麽是註釋?',
    infoBoxHTML1: `註釋提供了一種將事件數據集成到你的graphs面板的方法。它們在所有graph面板中顯示為垂直線
        和圖標。當您把鼠標懸停在一個註釋圖標上時，可以看到這個事件的事件文本和標記。您可以通過按住CTRL或CMD +點擊graph(或拖拽區域)直接在儀表板裏添加註釋事件。
        這些將存儲在儀表板的註釋數據庫中。`,
    infoBoxHTML2: '查看',
    infoBoxHTML3: '註釋文檔',
    infoBoxHTML4: '獲取更多信息。',
    builtIn: '(內置)',
    hiddenTooltip: '隱藏註釋查詢切換控制是否顯示在儀表板的頂部',
    annotationQueryFailed: '註釋查詢失敗',
  },
  dashboardStyle: {
    styleSetting: '儀表板樣式設定',
    background: '儀表板背景',
    color: '背景色',
    image: '背景圖片',
    panelStyle: '面板樣式設定',
    preStyle: '預設樣式',
    border: '面板邊框',
    borderColor: '邊框顏色',
    borderStyle: '邊框樣式',
    borderWidth: '邊框寬度',
    borderWidthTip: '請輸入數字作為邊框的寬度',
    panelRadius: '面板圓角設置',
    radius: '圓角模式',
    radiusColor: '圓角顏色',
    borderShadow: '邊框陰影',
    borderGradient: '邊框漸變',
    gradientMode: '漸變模式',
    gradientColor: '漸變顏色',
    panelTitle: '面板標題',
    startColor: '漸變開始顏色',
    endColor: '漸變結束顏色',
    pillarColor: '柱子顏色',
    shadowShow: '陰影顯示',
    reduceTopMargin: '縮小上邊距',
  },
  dashboardLinks: {
    links: '儀表板鏈接',
    linkTitle: '尚未添加儀表板鏈接',
    addLink: '添加儀表板鏈接',
    pTip: '儀表板鏈接允許您將指向其他儀表板和網站的鏈接直接放置在儀表板標題下方.',
    whatLink: '儀表板鏈接是什麽?',
    withTag: '標簽',
    include: '包括',
    asDrop: '作為下拉菜單',
    varValue: '變量值',
    oneLine: '啟用一行顯示',
  },
  orgsImport: {
    datalog: '導入的數據日誌.',
    closeDataLog: '導入完成.',
    wait: '等待...',
    sameStructImport: '相同結構導入',
    importSpecifiedOrg: '導入到指定組織',
    selectFile: '請選擇exportedOrgs.xxx.zip文件.',
    startImport: '開始打印相關日誌信息 . . .',
    waitOverwrite: '請等待片刻，正在覆蓋您剛選擇的項.',
    callOverwrite: '開始調用覆蓋的方法.',
    annoInfoSuccess: '所選{name}數據源的匿名信息已成功更新.',
    annoInfoError: '{org}組織中的{name}數據源匿名信息更新失敗.',
    dataUpSuccess: '所選{name}數據源更新成功.',
    dataUpFailed: '所選數據源更新失敗.',
    dashOverSuccess: '所選{name}儀表板信息已成功更新.',
    dashOverFaild: '{orgId}組織中儀表板覆蓋失敗.',
    srpUpSuccess: '所選{name} SRPFrame已更新成功.',
    srpUpFailed: '"{orgId}組織下SRPFrame覆蓋失敗."',
    startGet: '開始獲取每個文件的內容.',
    tip: '提示',
    importMoreOne: '當導入組織超過一個時,僅為您導入第一個({name})組織的數據.',
    importText2: '您是否仍想導入{name} 組織數據?',
    dashExist: '{orgName}組織,{folder}文件夾下的{slug}儀表板已存在.',
    dashImportSucc: '{orgName}組織,{folder}文件夾下的儀表板{slug}導入成功.',
    dashImportFalied: '{org}組織下儀表板導入失敗.',
    folderResult: '{folder}文件夾下儀表板已成功返回.',
    getOrgFailed: '{orgName} 組織下{folder}文件夾獲取失敗.',
    getFrameFailed: '獲取SRP-Frame失敗.',
    srpImportSuccess: '{orgName}組織下的SRP-Frame 導入成功.',
    srpImportFailed: '{currentId}組織下的SRP-Frame導入失敗.',
    srpExist: '{orgName}組織下的{srpName} {type} 已經存在.',
    datasourceError: '導入數據源的時候發生了錯誤.',
    dataImportSuccess: '{paasOrgName} 組織下 {datasourceName} 數據源導入成功.',
    dataImportFailed: '{currentId}組織下數據源導入失敗.',
    annoImportSuccess: '{paasOrgName}組織下數據源匿名信息導入成功.',
    annoImportFalied: '{currentId} 組織下數據源匿名信息導入失敗.',
    creNewOrg: '創建新組織 {orgName} 並導入數據.',
    creOrgFailed: '創建組織失敗.',
    nowImportSRPFrame: '開始導入SRP-Frame...',
    dashsImportFalied: '儀表板導入失敗.',
    createFolderFalied: '創建文件夾失敗.',
    preferenceError: '導入組織偏好的時候發生了錯誤.',
    imgUploadSuccess: '{orgName}組織下的圖片{imageName}導入成功',
    imgUploadError: '{orgName}組織下的圖片{imageName}導入失敗',
  },
  versions: {
    showMoreVersions: '展示更多的版本',
    compareVersions: '比較版本',
    restoreToVersion: '恢復版本到',
    viewJSONDiff: '查看 JSON 差異',
    canCompareText: '您一次只能比較兩個版本',
  },
  mobile: {
    groups: '分組',
    recover: '恢復',
    addGroup: '添加分組',
    noDashboardGroupAddedYet: '還沒有添加儀表板分組',
    whatAreDashboardGroup: '什麽是儀表板分組?',
    whatAreDashboardGroupInfo: `我們建議通過建立分組，將大量數據以分組方式呈現在移動設備的小屏幕上`,
    movePanel: '移動面板',
    moveOut: '移出',
    moveToRecover: '移動到回收站',
  },
  graph: {
    drawModes: '繪制模式',
    bars: '柱形',
    lines: '線形',
    points: '點',
    modeOptions: '模式選擇',
    fillGradient: '填充漸變',
    lineWidth: '線寬',
    staircase: '階梯',
    pointRadius: '點徑',
    plotSelected: 'Plot 可選',
    plotDblclick: 'Plot 雙擊',
    hoverTooltip: '懸停提示',
    stackedValue: '堆疊值',
    stackTotal: '堆疊總數',
    stackingNullValue: '堆疊和空值',
    stack: '堆疊',
    percent: '百分比',
    nullValue: '空值',
    stackPanel: '面板堆疊',
    drilldownDetailLink: '鉆取詳細鏈接',
    includeTimeRange: '包含時間範圍',
    includeCurrentTime: '包含當前時間',
    urlParams: 'Url 參數',
    urlParamsTips: '此處勾選變數後，在Url中使用[變數]，可在新連結中將此變數傳遞至新頁面',
    XAxis: 'X軸',
    precisionFormat: '精度格式',
    adjustableTimeRange: '可調整時間範圍',
    numberOfBuckets: '周期值',
    XMin: 'X軸最小值',
    XMax: 'X軸最大值',
    YAxes: 'Y軸',
    YAxis: 'Y軸',
    alignLeftAndRightYaxes: '對齊左右y軸',
    AlignmentYaxesTooltip: 'Y軸對齊是基於這個值，從Y=0開始',
    decimalPrecision: '覆蓋y軸的自動小數位數精度',
    asTable: '表格格式',
    toTheRight: '靠右',
    widthTooltip: '設置圖例表格/塊的最小寬度',
    hideSeries: '隱藏系列',
    withOnlyNulls: '僅有空值',
    withOnlyZeros: '僅有零值',
    seriesOverrides: '系列覆蓋',
    aliasOrRegex: '別名或正則表達式',
    addSeriesOverride: '添加系列覆蓋',
    addSeriesOverrideTip: '正則表達式匹配的例子: /server[0-3]/i',
    thresholdsTimeRegions: '閾值和時間區域',
    addThreshold: '添加閾值',
    thresholdsDisabled: `<strong>禁用</strong>可視化閾值選項。訪問Alert選項卡更新閾值。
        <br>為了重新啟用閾值，必須從該面板刪除告警規則。`,
    fillColor: '填充顏色',
    line: '線',
    lineColor: '線顏色',
    addTimeRegion: '添加時間區域',
    addTimeRegionTip: '所有配置的時間區域都是UTC時間',
    statistics: '統計數據',
    UCL: '上控制限',
    CL: '中心線',
    LCL: '下控制限',
    showDetails: '顯示詳細信息',
    infoTextLink: `使用數據鏈接，您可以引用數據變量，如系列名稱、標簽和值。鍵入CMD + 空格鍵，
        CTRL+空格，或$來打開變量建議。`,
    addLink: '添加鏈接',
    customScale: '刻度',
    customScaleEnable: '自定義刻度',
    markingArea: '標記區域',
    startTime: '開始時間',
    endTime: '結束時間',
    linkageSettings: '聯動設置',
    addALinkage: '添加一組聯動',
    lineFill: '線填充',
    Linewidth: '線寬',
    nullPointMode: '空點方式',
    fillBelowTo: '填寫低於',
    staircaseLine: '階梯線',
    Dashes: '破折號',
    HiddenSeries: '隱藏的系列',
    DashLength: '破折線長度',
    DashSpace: '破折線間距',
    Discrete: '離散',
    PointsRadius: '點徑',
    Yaxis: 'Y-軸',
    Zindex: 'Z層級',
    Transform: '轉換',
    Hideintooltip: '隱藏工具提示',
    DiscreteDataType: '離散數據類型',
    DiscreteDayShift: '離散日後退',
    showModes: '顯示繪製管道',
    showXSlider: '顯示X軸滑塊',
    graphMode: '影像管道',
    showMaxPoint: '顯示最大值点',
    Spline: '平滑',
    markingMaxPoint: '標記最大值点',
    dateFormatAsX: '日期格式和X軸一致',
    hideValue: '隱藏值',
    metricNameColor: '文字顔色',
    metricNameSize: '文字大小',
    metricNamePositionUp: '名稱上移',
    showValue: '顯示值',
  },
  math: {
    math: '數學公式',
    calculate: '計算',
    expression: '表達式',
    expressionTip: `A,B,C,D 代表數據源,<br>支持的操作符有 +, -, *, /, ().`,
    inputTip: '請輸入正確的表達式',
    addMetric: '增加指標',
  },
  singlestat: {
    thresholdsTip: `定義兩個閾值<br>50,80將會產生: 值 < 50 = 綠色, 50 < = 值 < 80
        = 黃色, 值 > = 80 = 紅色.注意：閾值支持填寫也支持配置query返回，若同時填寫了
        閾值和配置了一筆query時，query返回閾值的優先級高`,
    sparkLines: 'Spark線',
    fullHeight: '完整的高度',
    gauge: '計量器',
    minValueText: '最小值大於最大值。',
    thresFontSize: '閾值字體大小',
    thresholdLabels: '閾值標簽',
    thresholdMarkers: '閾值標記',
    setValueMappings: '設置值映射',
    addValueMapping: '添加一個值映射',
    setRangeMappings: '設置範圍映射',
    addRangeMapping: '添加範圍映射',
  },
  text: {
    autoplayInterval: '自動播放間隔',
    autoplayUrl: '播放網址',
    addUrl: '增加網址',
  },
  heatmap: {
    bucketBound: '周期邊界',
    bucketBoundTip: '使用系列標簽作為上或下周期的邊界。',
    bucketsTip: 'Y軸上的周期數。',
    sizeYTip: '周期的大小。優先於周期選項。',
    splitFactor: '分割因子',
    splitFactorTooltip: `僅適用於對數尺度。默認情況下，Y值被以(1,2,4,8,16，…)為底的整數冪所分割)。該選項允許將每個默認周期拆分為指定數量的周期。`,
    bucketsXTip: 'X軸上的周期數。',
    sizeXTip: '周期的大小。數值或間隔(10s、5m、1h等)。支持的時間間隔:ms, s, m, h, d, w, m, y。優先於周期選項。',
    dataFormatTip: `時間序列:規律時間序列創建熱圖。<br> 時間序列周期:使用從數據源返回的直方圖數據。每個系列表示周期的上下限是一個系列標簽。`,
    reverseOrder: '倒序',
    yBucketBoundTip: '使用系列標簽作為上或下周期的邊界。',
    exponent: '指數',
    colorScale: '色階',
    showLegend: '顯示圖例',
    hideZero: '隱藏零值',
    showTooltip: '顯示提示',
  },
  pluginlist: {
    recentlyViewed: '警告:當清除瀏覽器緩存時，此列表將被清除.',
    searchOptions: '搜索選項',
    limitNumberTo: '限制數量',
  },
  dashlist: {
    showHeadings: '顯示標題',
  },
  alertlist: {
    alertsFromDashboard: '來自此儀表板的警報',
    alertName: '告警名稱',
    alertNameQuery: '告警名稱查詢',
    dashboardTitle: '儀表板的標題',
    dashboardTitleQuery: '儀表板標題查詢',
    dashboardTags: '儀表板標簽',
    stateFilter: '狀態過濾',
    ok: '正常',
    paused: '暫停',
    noData: '無數據',
    executionError: '執行錯誤',
    pending: '等待',
  },
  table: {
    tableTransform: '表轉換',
    paging: '分頁',
    rowsPerPage: '每頁行數',
    columnStyles: '列樣式',
    applyColumnsNamed: '應用於列名稱為',
    patternTip: '指定正則表達式使用/my.*regex/語法',
    columnHeader: '列標題',
    renderValueLink: '渲染值為鏈接',
    nameOrRegex: '名稱或正則表達式',
    overrideHeaderLabel: '覆蓋標題標簽',
    sanitizeHTML: '處理HTML',
    preserveFormatting: '保存格式',
    commaSeparatedValues: '逗號分隔值',
    urlInfo1: '指定一個網址(相對或絕對)',
    urlInfo2: '使用特殊變量來指定單元格的值:',
    urlInfo3: '指當前單元格值',
    urlInfo4: '指當前行的第n列值。列索引從0開始。例如,',
    urlInfo5: '指第二列的值。',
    urlInfo6: '語法。缺省值是URI編碼的。如果該值是一個完整的URL，您可以禁用使用的所有編碼',
    tooltipInfo1: '指定鏈接工具提示的文本。',
    tooltipInfo2: '當用戶將指針懸停在帶有link的單元格上時，將顯示此標題。使用與網址相同的變量。',
    removeRule: '刪除規則',
    addColumnStyle: '添加列樣式',
  },
  bargauge: {
    calc: '計算',
    orientation: '方向',
    templateVariables: '模板變量:',
  },
  checkLicense: {
    checkLicense: '檢查License',
    welcome: '歡迎使用WISE-PaaS/Dashboard',
    nolicenseKey: '沒有許可密鑰或非法許可密鑰',
    recheck: '重新檢查',
    subscribeText: '請點擊下面的按鈕訂閱',
    toSubscribe: '訂閱',
    toLogin: '登錄',
    subscribeText1: '成功訂閱?登錄',
    productInformation: '產品信息',
    productName: '產品名稱',
    partNumber: '零件號',
    subscribedSpace: '訂閱空間',
    datacenter: '數據中心',
    cluster: '集群',
    workspace: '工作空間',
    namespace: '名稱空間',
  },
  testdata: {
    optional: '可選擇的',
    lines: '線',
    step: '步長',
    stepInfo: '數據點之間的秒數。',
    csvValueInfo: `逗號分隔值。每個值可以是int、float或null，但不能是
        是空的。刪除空格和尾隨逗號。`,
    onCount: '數量',
    onCountInfo: `一個循環中值的個數。在周期的開始應該有on值。`,
    offCount: '數量',
    offCountInfo: '周期內的off值個數。',
    onValue: '值',
    onValueInfo: 'on的值可以是int、float或null。',
    offValue: '值',
    offValueInfo: 'off的值可以是int、float或null。',
    speed: '速度',
    spread: '擴散',
    noise: '噪波',
    bands: 'Bands',
    fetchURL: '獲取URL',
    annotationScenario: '註釋的場景',
    setup: '設置',
    setupText: '有關設置可重復測試環境的更多信息,請參閱github。',
    seriesCount: '序列個數',
    Address: '地址',
    Value: '值',
    Longitude: '經度',
    Latitude: '緯度',
    startValue: '開始的值',
  },
  stackdriver: {
    Authentication1: `<h4>Stackdriver身份驗證</h4>
        <p>有兩種方法來驗證Stackdriver插件-要麽通過上傳服務帳戶密鑰文件,
        要麽通過自動從谷歌元數據服務器檢索憑據。後一種選項僅在GCE虛擬機上運行Grafana時可用。</p>

        <h5>上傳服務帳戶密鑰文件</h5>
        <p>首先您需要創建一個谷歌雲平臺(GCP)服務帳號
        獲取您想要顯示數據的項目。一個Grafana數據源與一個GCP項目集成。如果你想要可視化來自多個GCP項目的數據那麽你需要為每個GCP項目創建一個數據源。
        </p>
        <p>
          <strong>監控查看器</strong> 角色提供了Grafana需要的所有權限。 下面的API需要在GCP上
          啟用數據源才能工作 <a class="external-link" target="_blank" href="https://console.cloud.google.com/apis/library/monitoring.googleapis.com">
          監控API</a>
        </p>

        <h5>GCE默認的服務帳戶</h5>
        <p>如果Grafana運行在谷歌計算引擎(GCE)虛擬機上，那麽Grafana可以
        從元數據服務器自動檢索默認的項目id和身份驗證令牌。為了讓其生效，您需要確保您有一個服務帳戶，該帳戶被設置為虛擬機的默認帳戶
        機器，並且服務帳戶已被授予對Stackdriver監視API的讀訪問權。
        </p>

        <p>關於如何創建服務帳戶的詳細說明可以在 <a class="external-link" target="_blank"
            href="http://docs.grafana.org/datasources/stackdriver/">
            在這個文檔</a>找到。
        </p>`,
    authentication: '身份認證',
    authenticationInfo: `上傳您的服務帳戶密鑰文件或粘貼文件內容。該文件內容將被加密並保存在Grafana數據庫中。`,
    authenticationType: '認證類型',
    uploadServiceAccount: '上傳服務帳戶密鑰文件',
    pasteServiceAccount: '或粘貼服務帳戶密鑰JSON',
    uploadedKeyDetails: '上傳關鍵細節',
    project: '工程',
    clientEmail: '客戶電子郵件',
    tokenURI: 'Token URI',
    privateKey: '私鑰',
    resetServiceAccountKey: '重置服務帳戶密鑰',
    resetInfo: '重置清除上傳的密鑰，並上傳新的文件。',
    saveChanges: '不要忘記在上傳文件後保存您的更改。',
    verifyTest: '通過單擊保存 &測試驗證GCE默認的服務帳戶',
    service: '服務',
    selectServices: '選擇服務',
    selectMetric: '選擇指標',
    groupBy: '分組依據',
    aggregation: '聚合',
    selectReducer: '選擇 Reducer',
    advancedOptions: '高級選項',
    aligner: '調整器',
    selectAlignment: '選擇調整方式',
    alignmentPeriod: '校準周期',
    aliasBy: '別名',
    aliasPatterns: `<h5>別名模式</h5>通過使用別名模式，以任何方式格式化圖例鍵。
        <br /> <br />舉例:`,
    aliasPatterns1: `結果: &nbsp;&nbsp;<code>cpu/usage_time - server1-europe-west-1</code><br />
        <br /><strong>模式</strong>`,
    aliasPatterns2:
      `<ul><li><code>{${'{{metricDescriptor.type}}'}}</code> = 指標類型 e.g.compute.googleapis.com/instance/cpu/usage_time</li>` +
      `<li><code>{${'{{metricDescriptor.name}}'}}</code> = 指標的名稱部分 e.g. instance/cpu/usage_time</li>` +
      `<li><code>{${'{{metricDescriptor.service}}'}}</code>= 指標的服務部分 e.g. compute</li>` +
      `<li><code>{${'{{metricDescriptor.label.label_name}}'}}</code> = 指標元數據標簽 e.g.metricDescriptor.label.instance_name</li>` +
      `<li><code>{${'{{resource.label.label_name}}'}}</code> = 資源元數據標簽 e.g. resource.label.zone</li>` +
      `<li><code>{${'{{bucket}}'}}</code> = 在Dashboard中使用熱圖時，用於分配指標的周期邊界</li></ul>`,
    annotationInfo1: `註釋查詢格式`,
    annotationInfo2: `註釋是一個覆蓋在圖表上的事件。註釋渲染的開銷很大，所以限制返回的行數很重要。`,
    annotationInfo3: `標題和文本字段支持模板，並可以使用查詢返回的數據。例如，標題字段可以有以下文本:`,
    annotationInfo4: `有值:`,
    annotationInfo5: `舉例結果:`,
    annotationInfo6: `metric/point的值`,
    annotationInfo7: `類型 例如`,
    annotationInfo8: `metric的名稱部分 例如.`,
    annotationInfo9: `metric的服務部分 例如.`,
    annotationInfo10: `Metric標簽元數據 例如.`,
    annotationInfo11: `標簽元數據 例如.`,
  },
  prometheus: {
    scrapeInterval: 'Scrape間隔',
    scrapeTooltip: `將其設置為Prometheus配置文件中定義的全局scrape間隔。這將用作Prometheus步驟查詢參數的下限。`,
    queryTimeout: '查詢超時',
    queryTimeoutTip: '設置Prometheus查詢超時時間。',
    HTTPMethod: 'HTTP方法',
    HTTPMethodTip: '指定查詢Prometheus的HTTP方法。(POST僅在Prometheus>= v2.1.0中可用)',
    misc: '其他項',
    customQueryParameters: '自定義查詢參數',
    validation: '值無效，您可以使用帶有時間單位說明符的數值: y, M, w, d, h, M, s',
    customQueryTip: '向parameters或Thanos查詢添加自定義參數。',
    customQueryPlace: `舉例: max_source_resolution=5m&timeout=10`,
    noMetricsFound: '(沒有發現指標)',
    loadingMetrics: '加載指標...',
    promQLCheatSheet: 'PromQL備忘單',
    enterPromQLQuery: '輸入一個PromQL查詢',
    legendTip: `使用名稱或模式控制時間序列的名稱。例如，{{hostname}}將被替換為標簽主機名的標簽值。`,
    legendFormat: '圖例格式',
    minStep: '最小步長',
    minStepTip: `根據時間範圍和面板寬度為自動處理留出空白。註意，查詢中使用的實際日期將被調整為間隔步長的倍數。`,
    instant: '即時',
    linkGraphInPrometheus: '鏈接到Prometheus的圖表',
    CHEATTitle1: '請求速率',
    CHEATLabel1: `給定一個HTTP請求計數器，該查詢計算過去5分鐘內每秒的平均請求速率。`,
    CHEATTitle2: `請求延遲的95%`,
    CHEATLabel2: `計算5分鐘窗口中HTTP請求速率的第95個百分比。`,
    CHEATTitle3: `告警發射`,
    CHEATLabel3: `總結了過去24小時內發出的警報。`,
    searchExpression: '搜索表達式',
    step: '步',
    fieldFormats: '字段格式',
    otherOptions: '其他選項',
    ALERTS: '告警',
    alertname: '告警名稱',
    tagLabel: '標簽1,標簽2',
    instance: '實例',
    otherOptionsTip: `時間戳的單位為毫秒。如果序列值的單位是秒，則將其範圍向量乘以1000。`,
    seriesValueTimestamp: '序列值作為時間戳',
  },
  postgres: {
    schema: '模式',
    schema_: '模式',
    SSLMode: 'SSL模式',
    SSLModeInfo: '這個選項決定一個安全的SSL TCP/IP連接是否或以什麽優先級與服務器協商。',
    configured: '配置的',
    versionInfo: `這個選項控制PostgreSQL查詢構建器中可用的函數。`,
    timescaleDB: '時間量程DB',
    Help: `<a href="https://github.com/timescale/timescaledb" class="pointer" target="_blank">時間量程DB</a>
        是作為PostgreSQL擴展構建的時間序列數據庫。如果啟用，WISE-PaaS/Dashboard將使用<code>time_bucket</code>
        在<code>$__timeGroup</code>宏指令並在查詢生成器中顯示TimescaleDB特定的聚合函數。`,
    minTimeIntervalInfo: `時間間隔設置自動組的下限。建議設置為寫頻率，
        例如<code>1m</code> 如果你的數據每分鐘都被寫入。`,
    userPermission: `<h5>用戶權限</h5>
		<p>數據庫用戶應該只被授予要查詢的指定數據庫和表上的SELECT權限。
        WISE-PaaS/Dashboard不驗證查詢是否安全，因此查詢可以包含任何SQL語句。例如，這樣的語句<code>DELETE FROM user;</code>和
        <code>DROP TABLE user;</code>將被執行。為了防止這種情況發生，我們<strong>強烈</strong>建議您創建一個特定的PostgreSQL用戶，並限制其權限。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">時間序列:\n` +
      `- 返回列名為<i>time</i> (UTC時間，單位為秒或時間戳)\n` +
      `- 返回以數字類型作為值的列(s)\n` +
      `可選:\n` +
      `  - 返回列名為<i>metric</i>來表示系列名稱。\n` +
      `  - 如果返回多個值列，metric列作為前綴。\n` +
      `  - 如果沒有metric列，則使用值列的列名作為系列名\n\n` +
      `時間序列查詢的結果集需要按時間排序。\n\n` +
      `表:\n` +
      `- 返回任意一組列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; “time”列\n` +
      `- $__timeEpoch -&gt; 提取(從列中)作為“time”列\n` +
      `- $__timeFilter(column) -&gt; 在時間'2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'之間的列\n` +
      `- $__unixEpochFilter(column) -&gt;  列 &gt;= 1492750877 並且列 &lt;= 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 並且列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column,'5m'[, fillvalue]) -&gt; (提取(從列中)/300)::bigint*300\n` +
      `     通過設置fillvalue, WISE-PaaS/Dashboard將根據間隔填充缺失的值\n` +
      `     fillvalue可以是一個文字值，NULL或previous;previous將填充之前看到的值，如果還沒有看到，則為NULL\n` +
      `- $__timeGroupAlias(column,'5m') -&gt; (提取(從列中)/300)::bigint*300 作為 "time"\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; floor(column/300)*300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; floor(column/300)*300 作為 "time"\n\n` +
      `使用$__timeGroup分組和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroup(date_time_col, '1h'),\n` +
      `  sum(value) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY time\n` +
      `ORDER BY time\n\n` +
      `或者使用這些指令構建你自己的條件語句，它們只返回值:\n` +
      `- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__unixEpochFrom() -&gt;  1492750877\n` +
      `- $__unixEpochTo() -&gt;  1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp:
      `
        <pre class="gf-form-pre alert alert-info"><h6>註釋查詢格式</h6>
註釋是一個覆蓋在圖表上的事件。 查詢每行最多可以有三列，` +
      `時間列是強制性的。 註釋渲染的開銷很大，所以限制返回的行數很重要。

- 列的別名: <b>time</b> 獲取註釋事件時間。 使用epoch time或任何本機日期數據類型。
- 列的別名: <b>text</b> 獲取註釋文本
- 列的別名: <b>tags</b> 獲取註釋文本標簽。 這是一個逗號分隔的標記字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; "time" 列
- $__timeEpoch -&gt; 提取(從列中)作為 "time"列
- $__timeFilter(column) -&gt; 在時間 '2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'之間的列
- $__unixEpochFilter(column) -&gt;  列 &gt;= 1492750877 並且列 &lt;= 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 並且列 &lt;= 1494497183142514872

或者使用這些指令構建你自己的條件語句，它們只返回值:
- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'
- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'
- $__unixEpochFrom() -&gt;  1492750877
- $__unixEpochTo() -&gt;  1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
		</pre>`,
  },
  cloudDatasource: {
    nameDetail: 'CloudWatch 詳細信息',
    authPro: '驗證提供者身份',
    tip: '提示:憑據配置文件名稱，如〜/.aws/credentials中所指定，默認保留空白.',
    creName: '憑證配置文件名稱',
    keyId: '訪問密鑰的身份標識號',
    secretKey: '秘密訪問密鑰',
    ranTip: '承擔角色的ARN',
    defaultRegion: '默認區域',
    customMet: '自定義指標',
    regTip: '指定區域,例如對於美國西部(俄勒岡州),請使用“ us-west-2”作為區域.',
    customTip: '自定義指標的命名空間.',
    annotationProfile: '前綴匹配',
    annotationAction: '行動',
    alarmName: '警報名稱',
    region: '地區',
    dimensions: '尺寸',
    info: 'Id可以包含數字，字母和下劃線，並且必須以小寫字母開頭.',
    expression: '表達式',
    minPro: '最小時間',
    minTime: '點之間的最小間隔（以秒為單位）',
    aliasVar: '別名替換變量:',
    selectReg: '選擇地區',
    nameSpace: '名稱空間',
    selectName: '選擇名稱空間',
    metricName: '指標名稱',
    selectMetricName: '選擇指標名稱',
    idTip: 'Id可以包含數字，字母和下劃線，並且必須以小寫字母開頭.',
    expressionTip:
      '(可選）您可以在此處添加表達式。 請註意，如果正在使用引用其他查詢的數學表達式，則將無法基於該查詢創建警報規則',
    aliasTip:
      '別名替換變量:{{metric}}, {{stat}}, {{namespace}}, {{region}}, {{period}}, {{label}}, {{YOUR_DIMENSION_NAME}}',
    match: '完全匹配',
    matchTip: '僅顯示與所有定義的維度名稱完全匹配的指標',
    period: '期間',
    periodTip: '點之間的最小間隔以秒為單位',
    queryPro: '查詢預覽',
    dataId: '指標數據查詢ID',
    dataQuery: '指標數據查詢表達式',
  },
  elaDatasource: {
    elaDetail: 'Elasticsearch 詳細信息',
    indexName: '索引名稱',
    indexPlace: 'es-索引-名稱',
    pattern: '模式',
    timeField: '時間字段名稱',
    maxDatapoint: '最大並發請求數',
    minInter: '最小時間間隔',
    intervalTip: '值無效，您可以將數字與時間單位說明符一起使用: y, M, w, d, h, m, s',
    tipBefore: '按時間間隔自動分組的下限,建議設置為寫入頻率，例如',
    tipEnd: '如果您的數據每分鐘寫入一次.',
    massName: '消息字段名稱',
    levelName: '級別字段名稱',
    log: '日誌',
    fieldMap: '字段映射',
    minCount: '最小文件數',
    timEdge: '修剪邊緣',
    trmTip: '修剪時間序列數據點上的邊緣',
    offSet: '偏移',
    offTip: '將每個存儲桶的起始值更改為指定的正（+）或負偏移（-）持續時間，例如1h表示一個小時，或1d表示一天',
    orderBy: '訂購依據',
    mis: '缺失',
    misMas: '缺失參數定義了應如何處理缺失值的文檔。 默認情況下，它們將被忽略，但也可以將它們視為具有值',
    lucQuery: 'Lucene查詢',
    pre: '精度',
    preTip: 'Elasticsearch v5.0及更高版本:腳本語言不難,采用',
    preTip2: 'Elasticsearch v5.0之前版本：如果未更改，默認情況下腳本語言為Groovy。 供Groovy使用',
    preEnd: '引用變量',
    predict: '預測',
    pres: '百分比',
    precisTh: '閾值精確度',
    elaTip: '單擊以切換顯示/隱藏指標',
    filterQueries: '過濾查詢',
  },
  grafanaDatasource: {
    filterBy: '篩選依據',
    dashboardType: '儀表盤:這將獲取整個儀表盤的註釋和警報狀態更改，並僅在事件源面板上顯示它們.',
    tagType: '標簽:這將獲取與標簽過濾器匹配的所有註釋事件.',
    maxLimit: '最大限制',
    annoTip:
      '默認情況下,WISE-PaaS/Dashboard僅顯示與查詢中所有標簽匹配的註釋,啟用此選項將返回與查詢中的任何標簽匹配的註釋',
    aTag: '在此處輸入為"foo"的標簽將匹配',
    fooTag: '註釋標簽"foo"',
    annoKey: '格式為"foo:bar"的註釋鍵值標簽',
    queryName: '測試數據:隨機數',
  },
  azureDatasource: {
    azureDetial: 'Azure監視器詳細信息',
    azureCloud: 'Azure雲',
    cloudTip: '選擇Azure雲.',
    directId: '目錄（租戶）編號',
    clientId: '應用程序（客戶端)編號',
    clientSert: '客戶機密',
    defaultDesc: '默認訂閱',
    loadSub: '加載訂閱',
    appDetail: '應用程序見解詳細信息',
    apiKey: 'API密鑰',
    appId: '應用程序編號',
    logDetail: 'Azure日誌分析API詳細信息',
    logTip: '與Azure Monitor API相同的詳細信息',
    defaultWork: '默認工作區',
    loadWork: '加載工作區',
    defaultTip: '為Azure日誌分析查詢選擇默認/首選工作區.',
    workTip: '工作區是從上面選擇的默認訂閱中提取的.',
    metricName: '度量標準命名空間',
    timeGra: '時間粒度',
    autoInterval: '自動間隔',
    dimen: '規模',
    eq: '等於',
    legendFormat: '圖例格式化',
    aliasPatterns: '別名模式(有關更多信息，請參見幫助)',
    shortCut: '(運行查詢: Shift+Enter, 觸發建議: Ctrl+Space)',
    formatAs: '格式',
    rowQuery: '原始查詢',
    helpMas: `表格類型格式:
      --返回任何一組列
      格式為時間序列:
      -需要類型為datetime的列
      -返回具有數字數據類型作為值的第一列
      -(可選：返回具有字符串類型的第一列以表示系列名稱。如果未找到任何列，則將value列的列名稱用作系列名稱)
      時間序列查詢示例:
      Azure活動
      | 其中$__timeFilter()
      | 按類別匯總bin()，bin(TimeGenerated，60分鐘)
      | 按TimeGenerated升序排序
      巨集:
       -$__timeFilter()->datetime>=(2018-06-05T18:09:58.907Z)和TimeGenerated <= datetime(2018-06-05T20:09:58.907Z）
       -$__timeFilter(datetimeColumn) -> datetimeColumn >= datetime(2018-06-05T18:09:58.907Z)和datetimeColumn <= datetime(2018-06-05T20:09:58.907Z)
       -$__escapeMulti($myTemplateVar) -> $myTemplateVar應該是包含非法字符的多值模板變量
       -$__contains(aColumn,$myTemplateVar) -> ($myTemplateVar)中的aColumn
         如果使用“全部”選項，則選中“包括所有選項”復選框,然後在"自定義所有值"字段中鍵入:全部,如果選擇全部1==1
       或者使用這些僅返回值的內置變量來構建自己的條件:
       -$__timeFrom -> datetime(2018-06-05T18:09:58.907Z)
       -$__timeTo -> datetime(2018-06-05T20:09:58.907Z)
       -$__interval -> 5m
       例子:
       -| $__timeFilter
       -| TimeGenerated >= $__timeFrom和TimeGenerated <= $__timeTo
       -|按類別,bin(TimeGenerated,$__interval)匯總count()`,
    splitOn: '分裂',
    notSupport: '沒有註釋支持',
    annotationFormat: '註釋查詢格式',
    annotationTip: `註釋是覆蓋在圖形上方的事件。查詢每行最多可以有三列，datetime列是必需的。註釋渲染很昂貴，因此限制返回的行數很重要。
       -具有日期時間類型的列。
       -別名為Text或text的列，用於註釋文本
       -具有別名的列:標簽用於註釋標簽.這應該返回逗號分隔的標簽字符串，例如'標簽1,標簽2'
       巨集:
           -$__timeFilter() -> 時間生成 >= datetime(2018-06-05T18"09:58.907Z)和TimeGenerated <= datetime(2018-06-05T20:09:58.907Z)
           -$__timeFilter(datetimeColumn)-> datetimeColumn >= datetime(2018-06-05T18:09:58.907Z)和datetimeColumn <= datetime(2018-06-05T20:09:58.907Z）
           或者使用這些僅返回值的內置變量來構建自己的條件:
           -$__timeFrom -> datetime(2018-06-05T18:09:58.907Z)
           -$__timeTo -> datetime(2018-06-05T20:09:58.907Z)
           -$__interval -> 5m`,
    matchAny: '任意匹配',
  },
  graphDatasource: {
    graphDetail: 'Graphite 細節',
    topTip: '此選項控制Graphite查詢編輯器中可用的功能.',
    mas1: '有不同類型的Graphite兼容後端.您可以在此處指定使用的類型.如果使用的是',
    mas2:
      '然後在此處選擇.這將啟用Metrictank特定的功能，例如查詢處理元數據。Metrictank是針對Graphite和朋友的多租戶時間序列引擎.',
    graphQuery: 'Graphite查詢',
    graphEvent: 'Graphite事件標簽',
    series: '系列',
    tagKey: '標簽鍵',
    tagValue: '標簽值',
    and: '和',
    function: '函數',
    or: '或者',
  },
  dashboardDatasource: {
    tipMas: '該儀表板沒有其他面板。向其他面板添加查詢，然後重試',
    resultMas: '使用面板結果',
  },
  influxdbDatasource: {
    influxdbDetial: 'InfluxDB詳細信息',
    httpTip: `您可以使用GET或POST HTTP方法來查詢您的InfluxDB數據庫.POS方法允許您執行繁重的請求(帶有大量WHERE子句),而GET方法將限制您，如果查詢太大,則會返回錯誤.`,
    access: '數據庫訪問',
    accessTip: `為此數據源設置數據庫不會拒絕對其他數據庫的訪問.InfluxDB查詢語法允許在查詢中切換數據庫.例如在_internal或SELECT * FROM " _internal" .."database" LIMIT 10 中顯示測量值`,
    accessMas: '為了支持數據隔離和安全性，請確保在InfluxDB中配置了適當的權限.',
    minInter: '最小時間間隔',
    intervalTip: `自動分組時間間隔的下限.建議設置為寫入頻率,例如,如果每分鐘寫入一次數據,則為1m.`,
    where: 'WHERE',
    select: '選擇',
    slimit: '沒有限制',
    place: '通過$timeFilter限制事件中選擇文本個數為1000',
    filedMap: '字段映射',
    filedTip: '如果您的influxdb查詢返回多個字段,則需要在下面指定列名.註釋事件由標題、標簽和附加文本字段組成.',
  },
  inputDatasource: {
    shareData: '共享數據:',
    enterCsv: '輸入 CSV',
    infoBox: `此數據存儲在數據源json中，並在對任何數據源的初始請求中返回給每個用戶.這是輸入一些值的合適位置.大型數據集將在其他數據源中表現更好.`,
    noteMas: '對此數據的更改將僅在刷新瀏覽器後反映出來.',
  },
  lokiDatasource: {
    maxLine: '最大行數',
    tip: `Loki查詢必須包含返回的最大行數限制（默認值：1000）。增加此限制可為臨時分析提供更大的結果集。如果顯示日誌結果時瀏覽器變慢，請減小此限制.`,
    deviceField: '派生字段',
    fieldTip: '派生字段可用於從日誌消息中提取新字段並根據其值創建鏈接',
    hideMas: '隱藏示例日誌消息',
    showMas: '顯示示例日誌消息',
    debugLog: '調試日誌消息',
    placeholderMas: '在此處粘貼示例日誌行以測試派生字段的正則表達式',
    tooltip: '用於解析和捕獲日誌消息的某些部分,您可以在模板中使用捕獲的組.',
    enterQuery: '輸入Loki查詢',
    noLabel: '(未找到標簽)',
    loadLabel: '加載標簽...',
    logLabel: '日誌標簽',
  },
  datasource: {
    connectionLimits: '連接限制',
    maxOpen: '最大開放連接數',
    unlimited: '無限制的',
    maxOpeInfo1: `開放的數據庫連接的最大數目。如果`,
    maxOpeInfo2: '最大空閑連接數',
    maxOpeInfo3: '大於0並且',
    maxOpeInfo4: '最大開放連接數',
    maxOpeInfo5: '小於',
    maxOpeInfo6: '那麽',
    maxOpeInfo7: '會減少到匹配',
    maxOpeInfo8: '限制。如果設置為0，則對開放的連接數沒有限制。',
    maxOpeInfo9: '如果數據庫是共享類型，最大開放連接數不能超過100。',
    maxIdle: '最大閑置連接數',
    maxIdleInfo1: `空閑連接池中的最大連接數。如果`,
    maxIdleInfo2: `大於0，但小於`,
    maxIdleInfo3: `限制。如果設置為0，表示不保留空閑連接。`,
    maxIdleInfo4: '那麽',
    maxLifetime: '最大使用期',
    maxLifetime1: '一個連接可以被重用的最大時間(以秒為單位)。如果設置為0，連接將永遠被重用。',
    maxLifetime2: '這個值應該總是低於配置值',
    maxLifetime3: 'wait_timeout',
    maxLifetime4: '在MySQL.',
    minTimeInterval: `最小時間間隔`,
    minInfo1: `自動組按時間間隔設置的下限。例如，建議設置為寫頻率`,
    minInfo2: `如果你的數據每分鐘都被寫入`,
    FROM: '從',
    timeColumn: '時間列',
    metricColumn: '指標列',
    metricColumnInfo: `列用作值列的度量名稱。`,
    SELECT: '選擇',
    WHERE: `WHERE`,
    GROUPBY: '分組',
    ORDERBY: '排序',
    JOIN: '結合',
    ON: 'ON',
    formatAs: '格式',
    editSQL: '編輯SQL',
    queryBuilder: `查詢生成器`,
    generatedSQL: '生成SQL',
    warning: '警告',
    warnText: `切換到查詢生成器可能會覆蓋原始SQL。`,
    dataSourceError: '數據源錯誤',
  },
  opentsdb: {
    aggregator: '聚合',
    aliasInfo: `使用像$tag_tagname替換標記值的部分別名`,
    metricName: '指標名稱',
    seriesAlias: '系列別名',
    downSample: '下采樣',
    downSampleInfo: `空白為自動，或例如 `,
    disableDownsampling: '禁用下采樣',
    filtersInfo: `過濾器不能與標簽一起使用, 兩者都可以單獨使用，但不能同時使用。`,
    key: '鍵',
    addFilter: '添加過濾器',
    tagsInfo: '請使用過濾器，標簽在opentsdb 2.2中已棄用',
    addTag: '添加標簽',
    rate: '比率',
    counter: '計數',
    counterMax: '最大計數',
    maxValue: '極最值',
    resetValue: '重置值',
    resetvalue: '重置值',
    explicitTags: '顯式標簽',
    metricsQuery: '指標查詢',
    eventname: '事件.事件名',
    showGlobalAnnotations: '展示總體的查詢?',
  },
  mysql: {
    userPermission: `<h5>用戶權限</h5>
		<p>
            數據庫用戶應該只被授予要查詢的指定數據庫和表上的SELECT權限。
            WISE-PaaS/Dashboard不驗證查詢是否安全，因此查詢可以包含任何SQL語句。例如，這樣的語句<code>USE otherdb;</code>和
            <code>DROP TABLE user;</code>將被執行。為了防止這種情況發生，我們
			<strong>強烈</strong>建議您創建一個特定MySQL用戶，並限制其權限。
			查閱<a class="external-link" target="_blank" href="http://docs.grafana.org/features/datasources/mysql/">MySQL數據源文檔</a>獲取更多的信息。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">時間序列:\n` +
      `- 返回列名為time或者time_sec(UTC時間), unix時間戳或任何sql原生日期數據類型。您可以使用下面的指令。\n` +
      `- 返回以數字類型作為值的列(s)\n` +
      `可選:\n` +
      `  - 返回列名為<i>metric</i>來表示系列名稱。\n` +
      `  - 如果返回多個值列，metric列作為前綴。\n` +
      `  - 如果沒有metric列，則使用值列的列名作為系列名\n\n` +
      `時間序列查詢的結果集需要按時間排序。\n\n` +
      `表:\n` +
      `- 返回任意一組列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; UNIX_TIMESTAMP(列)作為time_sec\n` +
      `- $__timeEpoch(column) -&gt; UNIX_TIMESTAMP(列)作為time_sec\n` +
      `- $__timeFilter(column) -&gt; FROM_UNIXTIME(1492750877)和FROM_UNIXTIME(1492750877)之間的列\n` +
      `- $__unixEpochFilter(column) -&gt;  time_unix_epoch &gt; 1492750877 和 time_unix_epoch &lt; 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt; 列 &gt;= 1494410783152415214 和 列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column,'5m'[, fillvalue]) -&gt; cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed)\n` +
      `     通過設置fillvalue, WISE-PaaS/Dashboard將根據間隔填充缺失的值\n` +
      `     fillvalue可以是一個文字值，NULL或previous;previous將填充之前看到的值，如果還沒有看到，則為NULL\n` +
      `- $__timeGroupAlias(column,'5m') -&gt; cast(cast(UNIX_TIMESTAMP(column)/(300) as signed)*300 as signed) 作為 "time\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; 列 DIV 300 * 300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; 列 DIV 300 * 300 作為 "time"\n\n` +
      `使用$__timeGroup進行分組和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroupAlias(timestamp_col, '1h'),\n` +
      `  sum(value_double) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY 1\n` +
      `ORDER BY 1\n\n` +
      `或者使用這些指令構建你自己的條件語句，它們只返回值:\n` +
      `- $__timeFrom() -&gt; FROM_UNIXTIME(1492750877)\n` +
      `- $__timeTo() -&gt;  FROM_UNIXTIME(1492750877)\n` +
      `- $__unixEpochFrom() -&gt;  1492750877\n` +
      `- $__unixEpochTo() -&gt;  1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp: `
        <pre class="gf-form-pre alert alert-info"><h6>註釋查詢格式</h6>
註釋是一個覆蓋在圖表上的事件。詢每行最多可以有三列，<i>time</i> 或者 <i>time_sec</i>列是強制性的.
註釋渲染的開銷很大，所以限制返回的行數很重要。

- 列的別名: <b>time</b> 或者 <i>time_sec</i> 獲取註釋事件時間。使用epoch time或任何本機日期數據類型。
- 列的別名: <b>text</b> 獲取註釋文本
- 列的別名: <b>tags</b> 獲取註釋文本標簽。 這是一個逗號分隔的標記字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; UNIX_TIMESTAMP(列) 作為 time (或者作為time_sec)
- $__timeEpoch(column) -&gt; UNIX_TIMESTAMP(列) 作為 time (或者作為time_sec)
- $__timeFilter(column) -&gt; FROM_UNIXTIME(1492750877) 到 FROM_UNIXTIME(1492750877)的列
- $__unixEpochFilter(column) -&gt;  time_unix_epoch &gt; 1492750877 並且 time_unix_epoch &lt; 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 並且列 &lt;= 1494497183142514872

或者使用這些指令構建你自己的條件語句，它們只返回值:
- $__timeFrom() -&gt; FROM_UNIXTIME(1492750877)
- $__timeTo() -&gt;  FROM_UNIXTIME(1492750877)
- $__unixEpochFrom() -&gt;  1492750877
- $__unixEpochTo() -&gt;  1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
		</pre>`,
  },
  mssql: {
    encrypt: '加密',
    encryptInfo: '確定安全的SSL TCP/IP連接是否或在何種程度上要與服務器協商。',
    encryptInfo1: `客戶端和服務器之間發送的數據未加密。`,
    encryptInfo2: `客戶端和服務器之間發送的數據在登錄包之外不會被加密。(默認)`,
    encryptInfo3: `客戶端和服務器之間發送的數據是加密的。`,
    encryptInfo4: `如果你使用的是舊版本的Microsoft SQL Server，比如2008和2008R2，你可能需要禁用加密才能連接。`,
    userPermission: `<h5>用戶權限</h5>
		<p>
			數據庫用戶應該只被授予要查詢的指定數據庫和表上的SELECT權限。
			WISE-PaaS/Dashboard不驗證查詢是否安全，因此查詢可以包含任何SQL語句。例如，這樣的語句
			<code>USE otherdb;</code>和<code>DROP TABLE user;</code>將被執行。為了防止這種情況發生，我們
			<strong>強烈</strong>建議您創建一個特定MSSQL用戶，並限制其權限。
        </p>`,
    helpContent:
      `<pre class="gf-form-pre alert alert-info">時間序列:\n` +
      `- 返回列名為time(UTC時間), unix時間戳或任何sql原生日期數據類型。您可以使用下面的指令。\n` +
      `- 返回的任何其他列都是時間點值。\n` +
      `可選:\n` +
      `  - 返回列名為<i>metric</i>來表示系列名稱。\n` +
      `  - 如果返回多個值列，metric列用作前綴。\n` +
      `  如果沒有找到名為metric的列，則使用值列的列名作為系列名稱\n\n` +
      `時間序列查詢的結果集需要按時間排序。\n\n` +
      `表:\n` +
      `- 返回任意一組列\n\n` +
      `指令:\n` +
      `- $__time(column) -&gt; 列作為time\n` +
      `- $__timeEpoch(column) -&gt; DATEDIFF(second, '1970-01-01', column)作為time\n` +
      `- $__timeFilter(column) -&gt; 在'2017-04-21T05:01:17Z' 和 '2017-04-21T05:01:17Z'之間的列\n` +
      `- $__unixEpochFilter(column) -&gt; 列 &gt;= 1492750877 並且列 &lt;= 1492750877\n` +
      `- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 並且列 &lt;= 1494497183142514872\n` +
      `- $__timeGroup(column, '5m'[, fillvalue]) -&gt; CAST(ROUND(DATEDIFF(second, '1970-01-01', column)/300.0, 0) as bigint)*300.\n` +
      `     通過設置fillvalue, WISE-PaaS/Dashboard將根據間隔填充缺失的值\n` +
      `     fillvalue可以是一個文字值,NULL或previous; previous將填充之前看到的值，如果還沒有看到，則為NULL\n` +
      `- $__timeGroupAlias(column, '5m'[, fillvalue]) -&gt; CAST(ROUND(DATEDIFF(second, '1970-01-01', column)/300.0, 0) as bigint)*300 AS [time]\n` +
      `- $__unixEpochGroup(column,'5m') -&gt; FLOOR(column/300)*300\n` +
      `- $__unixEpochGroupAlias(column,'5m') -&gt; FLOOR(column/300)*300 AS [time]\n\n` +
      `使用$__timeGroup進行分組和排序的示例:\n` +
      `SELECT\n` +
      `  $__timeGroup(date_time_col, '1h') AS time,\n` +
      `  sum(value) as value\n` +
      `FROM yourtable\n` +
      `GROUP BY $__timeGroup(date_time_col, '1h')\n` +
      `ORDER BY 1\n\n` +
      `或者使用這些指令構建你自己的條件語句，它們只返回值:\n` +
      `- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'\n` +
      `- $__unixEpochFrom() -&gt; 1492750877\n` +
      `- $__unixEpochTo() -&gt; 1492750877\n` +
      `- $__unixEpochNanoFrom() -&gt;  1494410783152415214\n` +
      `- $__unixEpochNanoTo() -&gt;  1494497183142514872\n` +
      `</pre>`,
    annotationHelp: `<pre class="gf-form-pre alert alert-info"><h6>註釋查詢格式</h6>
註釋是一個覆蓋在圖表上的事件。查詢每行最多可以有三列，<b>time</b>列是強制性的.註釋渲染的開銷很大，所以限制返回的行數很重要。

- 列的別名: <b>time</b> 獲取註釋事件時間。使用epoch time或任何本機日期數據類型。
- 列的別名: <b>text</b> 獲取註釋文本
- 列的別名: <b>tags</b> 獲取註釋文本標簽。 這是一個逗號分隔的標記字符串，例如： 'tag1,tag2'


指令:
- $__time(column) -&gt; 列 作為 time
- $__timeEpoch(column) -&gt; DATEDIFF(second, '1970-01-01', column) 作為 time
- $__timeFilter(column) -&gt; '2017-04-21T05:01:17Z' 到 '2017-04-21T05:01:17Z'的列
- $__unixEpochFilter(column) -&gt; 列 &gt;= 1492750877 並且列 &lt;= 1492750877
- $__unixEpochNanoFilter(column) -&gt;  列 &gt;= 1494410783152415214 並且列 &lt;= 1494497183142514872

或者使用這些指令構建你自己的條件語句，它們只返回值:
- $__timeFrom() -&gt;  '2017-04-21T05:01:17Z'
- $__timeTo() -&gt;  '2017-04-21T05:01:17Z'
- $__unixEpochFrom() -&gt; 1492750877
- $__unixEpochTo() -&gt; 1492750877
- $__unixEpochNanoFrom() -&gt;  1494410783152415214
- $__unixEpochNanoTo() -&gt;  1494497183142514872
        </pre>`,
  },
  logoSetting: {
    orgName: '組織名稱',
    srpFramePBLogo: '右上角出品方圖標',
    srpFramePBLogoConf: '右上角出品方圖標',
    loginPageBgConf: '登錄頁背景圖配置',
    loginTopLogoConf: '登錄框頂部logo配置',
    loginTopLogo: '登錄框頂部logo',
    copyrightInfoConf: '登錄頁版權信息配置',
    copyrightInfo: '版權信息',
    copyrightTips: '此處填寫登入頁的版權資訊文字內容，不填寫則顯示默認版權資訊，填寫為"null"則不顯示版權資訊',
    loginPageConf: '登錄頁配置',
    activateDes: '點擊右側啟動按鈕，即可刷新頁面並啟動logo設定功能進行保存。'
  },
};

export default zhTW;
