const zh_TW = {
  /** dis-A */
  account: '帳號',
  add_group_first: '請先從資料集頁面新增分組。',
  add_source_first: '請先從資料來源頁面新增資料來源。',
  add_data_source: '新增資料來源',
  add_organization: '新增組織',
  add_user_dis: '新增使用者',
  add_tasks_desc: '從左側面板新增或選擇資料集。',
  add_task: '新增任務',
  add_udf_function: '新增 UDF',
  add_udaf_function: '新增 UDAF',
  add_child_group: '新增子分組',
  another_name: '別名',
  assign_task: '任務狀態',
  add_dataset: '新增資料集',
  about: '關於',
  add_new_task: '新增任務',
  access: '存取權限',
  auth_database: '身份驗證資料庫',
  add_job: '新增作業',
  add_task_limit_desc: '最多只能新增十個任務。',
  all_setting_will_be_changed: '與該資料集相關的所有設定都將被更改。',
  application_list: '應用程式列表',
  application_name: '應用程式名稱',
  as_least_one_app: '至少需要保留一個應用程式。',
  aggregate: '聚合',
  alter_columns: '修改欄位',
  add_columns: '新增欄位',
  and: '與',
  /** dis-B */
  basic: '基本資訊',
  basic_only: '基本資訊',
  basicPassword: 'Basic password',
  basicUser: 'Basic username',
  business_intelligence: '商業智慧',
  boundary_time_tips: '遞增欄位的起始時間。若留空，則系統會自動撈取欄位的最近的時間作為起始時間。',
  boundary_integer_tips: '遞增欄位的起始值。若留空，則系統會自動撈取欄位的最大值作為起始值。',
  blank_table: '空白表',
  bigDataStorage: '大數據存儲',
  batch: 'Batch',
  batch_selection_cannot_edit_dataset: '在批量選擇模式下無法編輯資料集。',
  /** dis-C */
  charset: '字元集',
  create_group_limit: '分組只能建立到第三層。',
  cdc: 'CDC',
  create_new: '新建',
  // click_add: '按一下上面的「+」以新增{name}。',
  click_add: '點選「+」按鈕以新增{name}。',
  click_add_select_dataset: '從左側面板新增或選擇要預覽的資料集。',
  click_select_data_source: '從左側面板中選擇要預覽的資料。',
  click_add_group: '請先按上面的「+」以新增分組。',
  click_join_org: '請按上面的「+」將使用者加入組織。',
  click_select_function: '從左側面板中選擇一個函式。',
  configuration_management: '組態管理',
  create_new_dataset: '建立新資料集',
  create_revision: 'create_revision',
  custom_schema: '自定義綱要',
  custom_schema_max_length: '不得超過63個字元。',
  custom_schema_col_name: '欄位名稱',
  custom_schema_data_type: '資料型別',
  column: '欄位',
  columns: '欄位',
  column_sort: '排序欄位',
  column_set: '欄位設定',
  column_name: '欄位名稱',
  columns_list: '欄位清單',
  change: '修改',
  change_password: '修改密碼',
  physical_table: '實體表',
  physical_table_tooltips: '用來儲存從資料來源提取的資料，可以自定義查詢的 SQL 語句。',
  custom: '自訂',
  cron_expression: 'Cron 表示式',
  cron_expression_custom: '自定義 Cron 表示式',
  cron_expression_example: 'Cron 表示式範例',
  cron_expression_desc: 'Cron 表示式由五個子表示式組成，每個子表示式可填入以下數值。',
  completion_time: '完成時間',
  collection: 'Collection',
  click_edit_to_modify: '點擊編輯按鈕以更改此參數值。',
  custom_partition: '自定義分區',
  copy_new_dataset: '複製資料集',
  // column_name_repeat: '列名{val}已重複',
  column_name_repeat: '欄位名稱不得重複。',
  column_setting_name_repeat: '欄位設定不得重複。',
  index_name_repeat: 'Index 名稱不得重複。',
  compare_s_t_and_e_t_error: '結束時間不能早於開始時間',
  confirm: '確認',
  click_lock_make_change: '點擊鎖圖示進行更改。',
  click_lock_save_change: '點擊鎖圖示以保存更改。',
  copy_to_clipboard: '已複製到剪貼簿。',
  combine: '合併',
  confirm_switch_to_graphic_flow_mode: '確定切換至圖形化流程模式',
  confirm_switch_to_sql_mode: '確定切換至 SQL 模式',
  custom_table: '自定義表',
  custom_table_tooltips: '用來儲存透過資料填報功能或 INSERT 語句寫入的資料，可以自定義資料集的 Schema。也可儲存從資料來源提取的資料。',
  column_data_type_error: '以下單元格的值與欄位資料型別不符：{val}',
  cell_data_type_error: '單元格的值與欄位資料型別不符。',
  current_version: '當前版本',
  /** dis-D */
  database_name: '資料庫名稱',
  database_dis: '資料庫',
  database_tips: '對應到資料儲存體的資料庫名稱。',
  dataset: '資料集',
  datasets: '資料集',
  dataset_alias: '資料集別名',
  data_preview: '資料預覽',
  dataset_group: '分組',
  dataset_preview: '資料集預覽',
  data_detect: '數據檢測',
  dataset_lower: '資料集',
  data_sets: '資料集',
  data_source_alias: '資料來源別名',
  data_source_disconnected: '無法連接資料來源。',
  data_source_name: '資料來源名稱',
  data_source_lower: '資料來源',
  data_sources: '資料來源',
  data_sources_list: '資料來源列表',
  data_sources_overview: '資料來源總覽',
  data_source_type: '資料來源類型',
  data_source_config: '設定資料來源',
  data_insight_sign_out: '登出',
  data_integration: '資料整合',
  date_type: '資料型別',
  date_time: 'Datetime',
  data_virtualization: 'Data Integration Service (DIS)',
  dataset_name: '資料集名稱',
  dataset_running_tooltip: '資料集正在建立中，請稍候。{val1}您會於資料集建立完成後收到通知。',
  dataset_fail_tooltip: '資料集建立失敗，可將此資料集進行刪除，或重新嘗試建立。',
  dataset_column: '資料集欄位名稱',
  dataset_list: '資料集列表',
  day_of_week: '週',
  disconnected: '資料來源已斷開連接。',
  dis_select: '- 請選擇 -',
  dis_input: '- 請輸入 -',
  dis_sure_to_save_dataset: '資料集將使用新設定重新建立，且資料會被清空。確定要保存此修改嗎？',
  dis_minute_desc: '* (0 - 59)',
  dis_hour_desc: '* (0 - 23)',
  dis_day_of_month_desc: '* (1 - 31)',
  dis_month_desc: '* (Jan - Dec)',
  dis_day_of_week_desc: '* (Mon - Sun)',
  destination: '位置',
  dis_function: '方法',
  dis_required: '必填',
  dis_host: '地址',
  dis_port: '通訊埠',
  dis_user_name: '使用者名稱（信箱）',
  dis_enable: '啟用',
  dis_disable: '停用',
  dis_url: 'URL',
  dis_method: 'Method',
  dis_creating: '建立中…',
  dis_loading: '讀取中…',
  dis_row: '列',
  dis_user: '使用者名稱',
  dis_action_success: '{action}成功！',
  dis_not_dataset_text_regexp: '不能包含 dataset/datasets，無論大小寫。',
  dis_first_byte_not_num_underline_regexp: '開頭不能使用數字或底線(_)。',
  dis_dataset_name_regexp: '只允許 a-z、A-Z、0-9 和 _。',
  dis_data_source_name_regexp: '只允許 a-z、A-Z、0-9 和 _。',
  dis_group_name: '分組名稱',
  dis_dataset_name: '資料集名稱',
  data_source_btn: '資料來源',
  dis_header: '指定第一列作為表頭',
  dis_header_label: '表頭',
  dis_sep: '分隔字元',
  dis_quote: '引用字元',
  dis_header_desc: '指定CSV文件中的第一列作為欄位名稱。',
  dis_quote_desc: '用於將欄位的值括起來，以確保在解析和處理 CSV 資料時能夠準確地處理包含分隔字元的欄位值。引用字元必須是單一字元。',
  dis_service_name: '服務名稱',
  dis_start_time: '開始時間',
  dis_end_time: '結束時間',
  dis_minutes: '分',
  dis_hours: '時',
  dis_days: '日',
  dis_minute: '分',
  dis_hour: '時',
  day_of_month: '日',
  dis_month: '月',
  dis_select_all: '選擇全部',
  dis_enabled: '啟用中',
  dis_examples: '範例',
  dis_info: '資訊',
  dis_json: '不合法的 JSON 字串。',
  dis_advanced_setting: '進階設定',
  dis_version: '版本',
  dis_task_cron_example_every_minute: '每一分鐘。',
  dis_task_cron_example_every_hour: '每小時5分。',
  dis_task_cron_example_every_day: '每天上午10:15。',
  dis_task_cron_example_only_monday: '每個星期一下午14:00。',
  dis_task_cron_example_every_Nov: '每年11月11日上午11:11。',
  dis_every_times: '每 {frequency} {interval}',
  dis_data: '資料',
  dis_search_root_group: '分組名稱（僅限根目錄中的分組）',
  datasets_destination: '存放位置',
  dis_number: '數值',
  dis_date_time: '日期與時間',
  disable_job: '停用作業',
  dis_time_period: '時間間隔',
  dis_cron_expression_desc: 'Cron表示式由五個子表示式組成，每個子表示式可填入以下數值。',
  dataset_create_success: '資料集建立完成',
  dataset_create_fail: '資料集建立{value}',
  dataset_create_processing: '資料集建立中',
  dataset_edit_success: '資料集編輯完成',
  dataset_edit_fail: '資料集編輯{value}',
  dataset_edit_processing: '資料集編輯中',
  dataset_create_success_msg: `資料集 {value} 建立完成。`,
  dataset_create_fail_msg: `資料集 {value} 建立失敗。`,
  dataset_create_processing_msg: `資料集 {value} 正在建立中。`,
  dataset_edit_success_msg: `資料集 {value} 已編輯完成。`,
  dataset_edit_fail_msg: `資料集 {value} 編輯失敗。`,
  dataset_edit_processing_msg: `資料集 {value} 正在編輯中。`,
  dataset_insert_success: '插入資料完成',
  dataset_insert_fail: '插入資料{value}',
  dataset_insert_processing: '插入資料中',
  dataset_insert_success_msg: `資料集 {value} 插入資料已完成。`,
  dataset_insert_fail_msg: `資料集 {value} 插入資料失敗。`,
  dataset_insert_processing_msg: `資料集 {value} 正在插入資料中。`,
  dataset_insert_tips: '資料正在插入中，請稍候。您會於資料插入完成後收到通知。',
  dis_on: '啟用',
  dis_off: '停用',
  dis_on_or_off: '啟用／停用',
  dashboard: '視覺化大屏',
  drop_file_to_upload: '將檔案拖曳至此，或{value}並上傳檔案。',
  drop_file_here: '請將檔案拖曳至此',
  dis_upload_file: '上傳檔案',
  dis_failed: '失敗',
  dis_length_error: '僅限正整數',
  dis_blank_table_length_required: '資料型別若為 DECIMAL 時，長度為必填項目。',
  dis_column_name_rules: '欄位名稱必須為 [a-zA-Z0-9_]，且不能以數字或底線(_)開頭。',
  dis_at_least_one_column: '至少要有一個自定義綱要或自定義分區。',
  dis_dataset_name_rule: '僅允許 [a-zA-Z0-9_] 且不能以數字或(_)開頭。',
  datasource_access: '資料來源權限',
  dataset_access: '資料集權限',
  datasource_name: '資料來源名稱',
  dis_source_id: '資料來源 ID',
  dis_dataset_id: '資料集 ID',
  dis_source_name: '資料來源名稱',
  dis_created_by: '建立者',
  dis_created_at: '建立時間',
  dis_updated_by: '更新者',
  dis_updated_at: '更新時間',
  dis_none: '無',
  dis_apply: '套用',
  dis_clear_all: '清空',
  dis_time_filter: '時間篩選',
  dis_time_range: '時間範圍',
  dis_last_seven_days: '過去 7 天',
  dis_from_to: '自訂時間範圍',
  detail: '詳細資訊',
  dis_start_date: '開始日期',
  dis_end_date: '結束日期',
  dis_cdc: 'CDC',
  dis_primary_key: '主鍵',
  dis_incremental_update_tips: '在執行增量更新任務之前，請先進行增量更新設定。',
  default_database: '資料庫',
  default_database_tips: '要從中讀取資料的資料庫名稱。如果與身份驗證資料庫相同，則將此欄位留空。',
  dis_type: '類型',
  dis_inferSchema: '自動推斷 Schema',
  dis_inferSchema_desc: '從資料中自動推斷 schema。',
  dis_application: '應用程式',
  dis_close: '關閉',
  development_mode: '開發模式',
  data_assets: '資料資產',
  double_click_or_drag_tips: '連點兩下或以拖曳的方式將 {name} 加入到 SQL 中。',
  drag_tips_only: '以拖曳的方式將 {name} 加入到 SQL 中。',
  dis_group_list: '分組列表',
  document_api: 'API 文件',
  data_development: '數據開發',
  drag_node_to_create: '請從左側面板拖曳節點來建立流程圖。',
  duplicate: '複製',
  dis_excludeAttribute: '排除屬性',
  dis_excludeAttribute_tips: '是否要排除元素中的屬性。',
  download_template_to_learn: '下載{template}可以幫助您填報資料。',
  data_input: '資料填報',
  delete_all_resources_of_group: '請先刪除分組內的所有資源。',
  /** dis-E */
  edit_name: '編輯 “{name}”',
  edit_job: '編輯作業',
  edit_dataset: '編輯資料集',
  edit_data_source: '編輯資料來源',
  edit_udf_function: '編輯 UDF',
  edit_udaf_function: '編輯 UDAF',
  enable_job: '啟用作業',
  execution_frequency: '執行頻率',
  execution_once: '只執行一次',
  everyday: '每天執行一次',
  every: '每',
  excution_time: '執行時間',
  edit_task: '編輯任務',
  extension_functions: '擴充函式',
  end_by: '結束於',
  epoch: 'Epoch',
  extension_service: '外部服務',
  extension_function_access: '擴充函式權限',
  encoding: '編碼',
  error_msg: '錯誤訊息：',
  email: '信箱',
  end_time_setting: '結束時間設定',
  execute: '執行',
  e_t_need_later_then_s_t_error: '結束時間需晚於開始時間',
  exit_development_mode: '離開開發模式',
  excel_insert_col_before: '向左方插入欄',
  excel_insert_col_after: '向右方插入欄',
  excel_insert_row_before: '向上方插入列',
  excel_insert_row_after: '向下方插入列',
  excel_insert_rows_before: '向上插入多列',
  excel_insert_rows_after: '向下插入多列',
  excel_insert_rows_end: '插入列',
  excel_insert_more_rows_end: '插多列',
  excel_delete_selected_cols: '刪除所選欄位',
  excel_rename_column: '重新命名所選欄位',
  excel_order_ascending: '從小到大排序',
  excel_order_descending: '從大到小排序',
  excel_delete_selected_rows: '刪除列資料',
  excel_copy: '複製',
  excel_paste: '貼上',
  excel_save_as: '另存',
  /** dis-F */
  fail: '失敗',
  function_alias: '函式别名',
  function_dis: '函式',
  function_lower: '函式',
  functions: '函式',
  functions_list: '函式列表',
  function_name: '函式名稱',
  full_update: '完整更新',
  file_upload_row_limit: '接受的檔案格式：{type}。最多上傳資料筆數：{size}。',
  file_upload_format: '接受的檔案格式：{type}。最大上傳檔案大小：{size}。',
  file_upload_fail: '此檔案無法上傳。請重新嘗試。',
  file_uploading: '請等待檔案上傳完畢。',
  file_upload_success: '檔案已上傳成功。',
  failure_notification: '更新失敗通知',
  fail_upload_fail_check_format: '無法上傳檔案，請檢查檔案格式是否為 {type}，然後再試一次。',
  fail_upload_fail_check_row_limit: '無法上傳檔案，請檢查檔案内資料筆數是否超出了 10000 筆，然後再試一次。',
  fail_upload_fail_check_size: '無法上傳檔案，請檢查檔案大小是否不大於 100 MB，然後再試一次。',
  fail_upload_fail_content: '上傳的檔案不合法，請檢查檔案的格式和內容後再試一次。',
  fail_upload_fail_check_length: '系統只允許上傳一個文件。',
  failure_notification_error: '取得通知群組失敗。請設定正確的 NOTIFICATION_URL 參數，且使用者需有 WISE-IoTSuite/Notification 的使用權限。',
  failure_notification_no_exist: '指定的通知群組已不存在，請選擇其他的通知群組。',
  failure_notification_no_permission: '取得通知群組失敗。請設定正確的 NOTIFICATION_URL 參數，且使用者需有 WISE-IoTSuite/Notification 的使用權限。',
  failure_notification_not_found: '找不到通知群組。至少要有一個通知群組建立於 WISE-IoTSuite/Notification。',
  full_access: '完整權限',
  finish: '完成',
  function_name_or_alias: '函式名稱或別名',
  filter: '過濾',
  filter_setting: '過濾設定',
  filter_row: '列過濾',
  /** dis-G */
  general: '一般',
  group_repeat: '指定的分組下已存在相同名稱的分組。',
  graphic_flow: '圖形化流程',
  group_by: '分組',
  /** dis-H */
  host_role: '此欄位的格式為{tag1}host{tag2}:{tag1}port{tag2}，若有多組，每組請以逗號（,）分隔',
  home_lower: '首頁',
  import: '匯入',
  import_data: '匯入資料',
  information: '資訊',
  instanceName: '個體名稱',
  item: '項目',
  incremental_update_now: '增量更新設定',
  input_regexp_1: '僅允許 [a-zA-Z0-9.-]',
  input_regexp_2: '. 和 - 不允許出現在開頭與結尾',
  input_regexp_3: '僅允許數字',
  input_regexp_4: '僅允許 [0-9a-f-]',
  input_regexp_5: '僅允許 [a-zA-Z0-9:-.,]',
  input_regexp_6: '僅允許 [a-z0-9.-]',
  input_regexp_7: '僅允許 [a-zA-Z0-9._-] 和空格',
  input_regexp_8: '僅允許 [a-zA-Z0-9._-]',
  input_regexp_9: '不允許空格',
  input_regexp_10: '僅允許 [a-zA-Z0-9_-.+]',
  input_regexp_11: '僅允許 [a-zA-Z0-9_-./@:]',
  input_regexp_12: '此名稱為保留名稱，請使用其他名稱。',
  input_regexp_13: '不合法的名稱，請使用其他名稱。',
  input_regexp_14: '僅允許 a-z A-Z 0-9 . 和 - 且必須以小寫字母開頭。',
  input_regexp_15: '僅允許數字和小數點，且小數點不允許出現在開頭與結尾',
  input_regexp_16: '僅允許 [a-z0-9_-.]',
  input_regexp_17: '僅允許正整數和-1',
  input_regexp_18: '僅允許正數和-1',
  input_regexp_19: '空格不允許出現在開頭或結尾。',
  input_regexp_20: '僅允許 [a-zA-Z0-9_] 且不能以數字開頭',
  input_regexp_21: '此欄位必須為正整數，且介於 {min} 到 {max} 之間。',
  input_regexp_22: '不得超過 {length} 個字元。',
  input_regexp_23: '格式不正確',
  input_regexp_24: '僅允許 [a-z0-9_]，且不能以數字開頭。',
  input_regexp_25: '只限定用英文及數字。',
  input_regexp_26: '僅允許 [a-z0-9_]',
  input_regexp_27: '此欄位必須為整數，且介於 {min} 到 {max} 之間。',
  input_regexp_28: '僅允許 [a-z0-9_]，且只允許以小寫英文字母開頭。',
  input_regexp_int: '此欄位必須為整數。',
  input_regexp_int_min: '此欄位必須為正整數，且最小值是 {min}。',
  input_regexp_decimal: '兩個數字必須皆為介於0到38之間的正整數，且第一個數字必須大於或等於第二個數字。',
  input_regexp_no_comma: '此欄位不允許出現","',
  input_regexp_no_double_quotes: '欄位名稱不能包含雙引號。',
  input_regexp_min_count: '最小值是 {minCount}。',
  input: '輸入',
  input_insert_row_counts: '請輸入需要插入的列數。',
  insert_row_count_s: '插入列數',
  insert_row_success: '插入成功！',
  /** dis-J */
  job_management: '作業管理',
  job_id: '作業ID',
  job_name: '作業名稱',
  job_mgmt_lowercase: '作業管理',
  jump_to_job_mgmt: '前往{name}建立任務。',
  jobs_lower: '作業',
  jobs: '作業',
  jump_to_application_mgmt: '前往{name}建立應用程式。',
  joint_data: '聯合資料',
  /** dis-L */
  lease: 'lease',
  less: '較少',
  last_execution_time: '最後執行時間',
  last_completion_time: '最後完成時間',
  last_version: '最後版本',
  /** dis-M */
  marks_title: '“{val}”',
  mark_all_as_read: '全部標為已讀',
  mark_as_read: '標為已讀',
  measurement: 'Measurement',
  message: '訊息',
  move_dataset_to_new_group: '從下面的清單中選擇一個分組。',
  move_to: '移動至…',
  move_to_short: '移動至…',
  move_to_root: '移動至根目錄',
  move: '移動',
  manage_application: '管理應用程式',
  manage_applications: '管理應用程式',
  manage_applicaiton_config: '為資料集設定應用程式。',
  more: '更多',
  more_detail: '詳情',
  mine_datasets: '我的資料集',
  /** dis-N */
  next_execution: '下一次執行時間',
  no_application: '尚未有應用程式。',
  no_data_yet: '還沒有資料。',
  no_dataset: '尚未選擇資料集。',
  no_dataset_preparing: '沒有正在建立中的資料集',
  no_data_source_selected: '尚未選擇資料來源。',
  no_data_selected: '尚未選擇任何資料。',
  no_function_selected: '尚未選擇函式。',
  no_job_selected: '尚未選擇作業。',
  no_data_group: '尚未建立分組。',
  no_data_sources: '尚未建立資料來源。',
  no_join_org: '尚未加入組織',
  no_user: '尚未加入任何使用者。',
  no_permission: '授權驗證失敗',
  no_permission_page: '請回到{home}再試一次。如果再次發生這種情況，請與我們聯繫。',
  no_task: '尚未選擇任何任務。',
  no_task_update_strategy: '尚未有任何任務。',
  no_end_time: '無結束時間',
  notification_alarm: '警報通知',
  num_item: '{num} 項',
  num_item_selected: '已選擇 {num} 項：',
  num_organization: '{num} 個組織',
  num_users: '{num} 個使用者',
  num_teams: '{num} 個團隊',
  num_roles: '{num} 個角色',
  num_datasets: '{num} 個資料集',
  not_selected_no_need_fill_in: '尚未選中，不需要填入。',
  number_of_entries: '更新數量',
  no_group_to_select: '沒有可選擇的分組。',
  no_dataset_to_select: '沒有可選擇的資料集。',
  no_source_to_select: '沒有可選擇的資料來源。',
  no_status: '無狀態',
  noSQL: 'NoSQL 資料庫',
  no_group: '尚未選擇分組。',
  notification_group: '通知群組',
  no_matching_column: '在資料集中找不到符合該參數類型的欄位。',
  'No.': '編號',
  no_extension_function: '沒有可選擇的擴充函式。',
  new_dataset: '新資料集',
  no_node: '尚未有節點',
  no_columns: '尚未有欄位',
  no_columns_add_new: 'Click the " {btn} " button to add columns!',
  no_columns_drag_new: 'Please drag columns to here.',
  no_rules: '尚未有過濾規則',
  no_rules_add_new: 'Click the " {btn} " button to add rules!',
  /** dis-O */
  oauthToken: 'OAuth token',
  organized_by_groups: '資料集是隸屬於分組之下。',
  organized_by_groups_for_function: '函式將存放於分組之下。',
  organization_dis: '組織',
  organization_dis_lower: '組織',
  organizations_dis: '組織',
  organization_name_dis: '組織名稱',
  organization_list: '組織名稱',
  organizations_number: '組織數',
  org_user: '組織使用者',
  organization_setting: '組織設定',
  org_user_list: '組織使用者列表',
  or: '或',
  /** dis-P */
  page: '頁',
  prev_revision: 'prev_revision',
  preview_timeout_try_again: '預覽逾時，請再次嘗試',
  previewVariables_tooltip: 'Raw request body 中的變數。例如：變數 {val1} 的鍵請填 {val2}。',
  properties: '屬性',
  partition: 'Partition',
  progress_header: '{value} 個資料集正在處理中',
  previewVariables: 'Preview variables',
  profile: '個人檔案',
  p_i_pwd: '請輸入您的密碼。',
  pipeline_tips: '在將資料發送到 Spark 之前將自定義聚合管道應用於Collection，例如：{val}',
  pending: '待執行',
  publish: '發佈',
  publish_api: '發佈 API',
  /** dis-Q */
  query_stopped: '査詢已停止',
  /** dis-R */
  return_to: '返回',
  rawReqBody_tooltip: '在完整或增量更新時，可以透過變數替換 Raw request body 的內容。變數請用 {val1} 包裝，例如：{val2}。',
  relational: '關聯式資料庫',
  redo: '重試',
  reqBody: 'Request body',
  request_threads: '請求執行緒數量',
  request_threads_desc: '同時執行請求的執行緒數量。',
  request_timeout_try_again: '請求逾時，請再次嘗試',
  retention_policy: '資料保留策略',
  retry_interval: '重試間隔時間 (ms)',
  retry_interval_desc: '重試間隔時間。如果回應的 HTTP 狀態碼不是 20X，系統會重試。',
  retry_times: '重試次數',
  retry_times_desc: '重試次數。如果回應的 HTTP 狀態碼不是 20X，系統會重試。',
  regexp_dis_task_increment_integer_and_zero: '僅允許正整數和零',
  rawReqBody: 'Raw request body',
  row_per_page: '每頁列數',
  rowTag: 'Row tag',
  read_timeout: '讀取逾時時間 (ms)',
  require_should_not_blank: '必填欄位不得為空。',
  reference: '參考來源',
  remove_duplicates: '刪除重複',
  rule: '規則',
  rule_list: '規則清單',
  /** dis-S */
  save_exit: '儲存並退出',
  save_dataset: '儲存資料集',
  save_return_develop: '儲存並返回數據開發',
  same_name_error: '已存在相同名稱的{name}。',
  same_name_error_use_an: '已存在相同名稱的{name}。',
  same_dataset_name: '已存在相同名稱的資料集。',
  same_group_name: '已存在相同名稱的分組。',
  same_source_name: '已存在相同名稱的資料來源。',
  same_task_name: '已存在相同名稱的任務。',
  same_func_name: '已存在相同名稱的函式。',
  same_org_name: '已存在相同名稱的組織。',
  same_application_name_error_use_an: '已存在相同名稱的應用程式。',
  save_as: '另存為',
  save_new_dataset: '另存為新資料集',
  save_new_dataset_name_where: '設定資料集名稱以及儲存位置。',
  save_new_udf: '另存為新方法',
  save_new_name_where: '設定{name}名稱以及儲存位置。',
  schema: '綱要',
  schema_information: '綱要資訊',
  select_data_source: '選擇資料來源類型',
  select_database_connect: '選擇要新增的資料來源類型',
  select_org: '請選擇組織',
  select_user: '請選使用者',
  socket_timeout: 'Socket 逾時時間 (ms)',
  srp_frame: 'SRP框架',
  sure_to_save_dataset: '確定要儲存資料集嗎？資料集的內容將被替換為當前的查詢結果。',
  sure_to_delete_name: '確定要刪除此{name}嗎？所有設定都會被刪除。',
  sure_to_delete_group: '確定要刪除此分組嗎？',
  group_can_not_delete: '當分組下沒有資料時才能進行刪除。',
  role_can_not_delete: '只有在没有使用者被分配為此角色時才能刪除角色。請先將相關的使用者分配為其他角色，再嘗試刪除此角色。',
  sure_to_delete_dataset: '確定要刪除此資料集嗎？',
  sure_to_delete_datasets: '確定要刪除已選擇的資料集嗎？',
  sure_to_delete_job: '確定要刪除此作業嗎？相關的更新日誌也會一併被刪除。',
  sure_to_delete_function: '確定要刪除此函式嗎？',
  sure_to_disable_name: '確定要停用「{name}」嗎？',
  sure_to_enable_name: '確定要啟用「{name}」嗎？',
  sure_to_delete_org: '確定要刪除此組織嗎？所有設定都會被刪除。',
  sure_to_delete_driver: '確定要刪除此驅動程式嗎？刪除驅動程式後，建議重新啟動 DataInsight，以防止系統出現異常。',
  sure_to_delete_user: '確定要刪除此使用者嗎？',
  sure_to_delete_orgs: '確定要刪除已選擇的組織嗎？所有設定都會被刪除。',
  sure_to_delete_drivers: '確定要刪除已選擇的驅動程式嗎？刪除驅動程式後，建議重新啟動 DataInsight，以防止系統出現異常。',
  sure_to_delete_users: '確定要刪除已選擇的使用者嗎？',
  sure_to_delete_roles: '確定要刪除已選擇的角色嗎？',
  sure_to_delete_teams: '確定要刪除已選擇的團隊嗎？',
  sure_to_delete_application: '確定要刪除此應用程式嗎？',
  application_can_not_delete: '當應用程式下沒有資料時才能進行刪除。',
  sure_to_delete_node: '確定要刪除此節點嗎？',
  sure_to_delete_nodes: '確定要刪除已選擇的節點嗎？',
  sure_to_delete_selected_data: '確定要刪除已選擇的資源嗎？',
  sure_to_exit_development_mode: '確定要離開開發模式嗎？尚未儲存的查詢將會遺失。',
  sure_to_create_new_one: '即將進行新的數據開發，尚未儲存的查詢將被捨棄，您確定嗎？',
  sure_save_dataset: '確定要儲存此資料集嗎？',
  sure_to_switch_mode: '切換模式將會刪除目前模式所有資料設定且不可復原，您確定要切換嗎？',
  stop_other_tasks: '其他啟用中的任務將會被停用。',
  switch_org_subTitle: '當前組織：{orgName}。請選擇要切換的組織。',
  switch_org: '切換組織',
  system_admin_dis: '系統管理員',
  system_settings: '系統設定',
  show_table_rows: '最多可預覽 {value} 列資料。',
  show_table_rows_log: '最多可查看 {value} 列日誌。',
  show_table_rows_query: '最多可預覽 {value} 列資料。',
  soapVersion: 'SOAP版本',
  sure_to_stop_processing_datasets: '您確定要停止處理這些資料集嗎？',
  semiStructured: '結構化文件',
  s3_only: '僅限本地 S3',
  select_data: '選擇資料',
  set_dataset_name: '設定資料集名稱',
  set_where_it_is_saved_to: '設定保存位置。',
  select_destination: '選擇位置',
  select_folder_to_move: '請選擇一個分組以完成移動。',
  set_dataset: '設定資料集',
  schema_setting: '綱要設定',
  sign_in_sub: '登入到 WISE-IoTSuite/DataInsight',
  set_task: '設定任務',
  status: '狀態',
  select_data_sources: '選擇資料來源',
  sample_size: '樣本大小',
  sample_size_tips: 'DataInsight 會從資料來源獲取指定的資料量作為樣本池，再從樣本池中採樣指定的資料量用來分析資料表的綱要。樣本大小為從樣本池採樣的資料量。',
  sample_pool_size: '樣本池大小',
  sample_pool_size_tips: 'DataInsight 會從資料來源獲取指定的資料量作為樣本池，再從樣本池中採樣指定的資料量用來分析資料表的綱要。樣本池大小為從資料來源獲取的資料量。',
  set_job: '設定作業',
  select_table_type: '選擇表格類型',
  sql: 'SQL',
  sort: '排序',
  switch: '切換',
  sure_clear_all_sheet: '確定要清空所有填報資料嗎？',
  sure_clear_all_query_data_sheet: '按下確定按鈕後會從資料集刪除目前顯示的 {length} 筆資料，確定要刪除嗎？',
  /** dis-T */
  Table: '資料表',
  task: '任務',
  total_data: '資料總數',
  task_list: '任務列表',
  task_name: '任務名稱',
  task_status: '任務狀態',
  task_setting: '任務設定',
  timeSeries: '時序型資料庫',
  technical_document_info: '點擊任何一個函式後，此處會顯示編寫說明。',
  team: '團隊',
  teams: '團隊',
  team_list: '團隊列表',
  team_name: '團隊名稱',
  table_type: '表格類型',
  tool: '工具',
  table_not_empty: '填報資料不能為空。',
  /** dis-U */
  update_type: '更新方式',
  update_log: '更新日誌',
  update_now: '立即執行',
  update_strategy: '更新策略',
  update_setting: '更新設定',
  update_in_progress: '立即更新進行中。',
  update_type_tips: '完整更新：更新時會重新擷取SQL語句指定的資料，並重建整個資料集。',
  // update_type_tips: '完整更新：更新時會重新擷取SQL語句指定的資料，並重建整個資料集。 \n增量更新：只更新於前次更新之後新增的部分，不影響原始資料集中的資料。',
  user_lower: '使用者',
  user_list: '使用者列表',
  user_name_email: '使用者名稱（信箱）',
  uploading: '上傳中',
  /** dis-V */
  variable_reference_column: '變數參考欄位',
  variable_reference_column_desc: '用來取代 Raw request body 中的變數。',
  variable_reference_table: '變數參考表',
  variable_reference_table_desc: '這個表格的欄位用來取代 Raw request body 中的變數，若搭配增量更新使用，表格中的每一列資料都是獨立的一次 HTTP 請求，所有請求的返回結果都會被儲存下來。',
  visulization: '視覺化多維度分析',
  visualization_analysis: '視覺化分析',
  v_group: '分組',
  v_dataset: '資料集',
  view_sql: '查看 SQL',
  view_table: '視圖表',
  view_table_tooltips: '用來直接查詢資料來源的資料，本身不儲存任何資料。',
  view_table_disabled_tooltips: '由於 SQL 涉及資料集，所以不支援儲存成視圖表。',
  view_current_version: '查看當前版本',
  /** dis-X */
  xsdContent: 'XSD content',
  /** dis-iFactory-menu */
  connector: '資料來源管理',
  data_setting: '數據設定',
  data_retrieval: '數據治理',
  data_analysis: '資料分析',
  iFactory_data_fabric: '智慧工廠數據經緯',
  general_fun: '通用功能',
  organizer: '組織數據',

  /** Parameters */
  preview_row_limit_tips: '資料預覽的列數限制。',
  parameter_name: '參數名稱',
  parameter_value: '參數值',
  parameter_setting: '參數設定',
  internal_parameters: '內部參數',
  internal_jdbc_endpoint_tips: 'JDBC 介面的私有 endpoint。{val1} 和 {val2} 是您的 SSO 使用者名稱和密碼。',
  external_jdbc_endpoint_tips: 'JDBC 介面的公開 endpoint。{val1} 和 {val2} 是您的 SSO 使用者名稱和密碼，而 {val3} 是 JDBC 介面的公開 IP。',
  service_plan_tips: '服務方案。',
  srpframe_url_tips: 'WISE-IoTSuite/SRPFrame 的 URL 設定。',
  twin_space_enabled_tips: '與 Desk 服務整合。',
  query_row_limit_tips: '資料查詢的列數限制。',
  notification_url_tips: 'WISE-IoTSuite/Notification 的 URL 設定。',
  log_row_limit_tips: '更新日誌的列數顯示限制。',
  dashboard_url_tips: 'WISE-IoTSuite/Dashboard 的 URL 設定。',
  bi_url_tips: 'WISE-IoTSuite/BI 的 URL 設定。',
  api_limitation: 'API限制',
  api_url_tips: 'DataInsight API 的公開 URL。',
  allowed_client_token_service_whitelist_tips: '允許使用 Client Token 呼叫 DataInsight API 的服務名稱白名單。 (允許多個服務的話使用 ; 作為分隔符號)',
  license_expiration_time: '授權到期時間。',
  sql_history_records: 'SQL 歷史紀錄',
  retention_policy_days: 'SQL 歷史記錄的保留天數。',
  vacuum_start_time: '每天刪除 SQL 歷史記錄的開始時間。',
  execution_time_second_threshold: '若 SQL 執行時間（秒）大於此閥值，此 SQL 才會被記錄下來。0 代表所有的 SQL 都會被記錄。',

  /** Org role */
  system_default_role_cannot_modified: '此為系統預設角色，無法進行變更。',
  resource_permissions: '資源權限',
  createSource: '新建資料來源',
  createDataset: '新建資料集',
  userManagement: '管理使用者',
  roleManagement: '管理角色',
  teamManagement: '管理團隊',
  role_list: '角色列表',
  applications_groups_datasets: '應用程式/分組/資料集',
  dataset_action_view_permission_lang: '查看應用程式/分組/資料集',
  dataset_action_manage_permission_lang: '新增、編輯、刪除應用程式/分組/資料集',
  source_action_view_permission_lang: '查看資料來源',
  source_action_manage_permission_lang: '新增、編輯、刪除資料來源',
  groups_extension_functions: '分組/擴充函式',
  udf_action_view_permission_lang: '查看分組/擴充函式',
  udf_action_manage_permission_lang: '新增、編輯、刪除分組/擴充函式',
  user_action_manage_permission_lang: '新增、編輯、刪除使用者',
  role_action_manage_permission_lang: '新增、編輯、刪除角色',
  team_action_manage_permission_lang: '新增、編輯、刪除團隊',
  add_edit_delete: '新增、編輯、刪除',

  /** Org team */
  team_lower: '團隊',
  team_add: '新增團隊',
  team_members: '團隊成員',
  members: '成員數',
  no_add_members: '新增成員',
  click_add_member: '請按上面的「+」將成員加入團隊。',
  member_list: '成員列表',

  /** Change password */
  old_new_password_can_not_same: '新密碼不能與舊密碼相同。',
  new_password_no_same: '與新密碼不一致。',
  password_not_comply_rules: '密碼不符合規則',
  password_rules: '密碼規則',
  password_rules_info_1: '至少 8 個字元，最多 20 個字元',
  password_rules_info_2: '至少 1 個數字',
  password_rules_info_3: '至少 1 個小寫字母',
  password_rules_info_4: '至少 1 個大寫字母',
  password_rules_info_5: '至少 1 個特殊字元',
  password_rules_info_6: '不包含空格（）、反斜線（\\）或雙引號（"）',
  password_rules_info_7: '不能與最近三次的密碼相同',

  /** Dataset sort */
  click_sort_asc: '點擊以升冪排序',
  click_sort_desc: '點擊以降冪排序',
  index: '索引',
  index_name: '索引名稱',
  index_setting: '索引設定',
  order_by: '排序',
  data_freshness_policy: '資料新鮮度方針',
  query_cache: '查詢快取',
  query_cache_tips: '是否要啟用查詢快取。當查詢到此資料集的資料時，會建立一個有存活時間（TTL）的快取，下次查詢一樣的資料時，會直接使用快取。若查詢同時涵蓋多個資料集時，則快取的存活時間（TTL）會以最小的為準。請注意，查詢快取不適用於預覽。',
  time_to_live_minutes: '存活時間（分鐘）',

  /** Login page */
  email_address: '使用者名稱',
  username_email: '使用者名稱',

  /** HTTP source */
  parameters_en: 'Parameters',
  query_parameters: '査詢參數',
  authorization_en: 'Authorization',
  authorization_type: '授權類型',
  access_token_url: 'Access token URL',
  request_body: 'Request body',
  content_type: 'Content type',
  "application/json": 'application/json',
  json_data_request_body: 'JSON data (Request body)',
  json_data_request_body_tips: '獲取 token 的 JSON 格式 request body。',
  response_body: 'Response body',
  json_path_of_token_response_body: 'JSONPath of token (Response body)',
  json_path_of_token_response_body_tips: '定義從 response body 中取得 token 的 JSONPath。',
  auto_refresh_token: '自動更新 token',
  every_hour: '每小時',
  auto_refresh_token_interval_minute: '自動更新 token 間隔（分鐘）',
  headers_en: 'Headers',
  body_en: 'Body',
  key_not_repeat: '鍵不可重複。',
  default_variables: '預設變數',
  default_variables_tips: '變數的預設值。當有設定變數時，會作為變數的預設值用來推斷 schema 。',
  bearer_token_en: 'Bearer token',
  grant_type: '授予類型',
  add_auth_data_to: '將授權數據添加到',
  header_prefix: 'Header prefix',
  client_id: '用戶端 ID',
  client_secret: '用戶端機密',
  scope: 'Scope',
  client_authorization: '用戶端授權',
  'form-data_en': 'form-data',
  'x-www-form-urlencoded_en': 'x-www-form-urlencoded',
  number: '數值',
  data_type: '資料類型',
  row_json_path: 'Row JSONPath',
  row_json_path_tips: '從 Response body 中用來提取列資料的 JSONPath。',
  pagination_setting: '分頁設定',
  page_type: 'Page type',
  page_field: 'Page field',
  page_field_tips: '頁碼或偏移量欄位名稱。',
  starting_value: 'Starting value',
  start_value_tips: '頁碼或偏移量的起始值。',
  page_number: '頁碼',
  dis_offset: '偏移量',
  page_size_field: 'Page size field',
  page_size_field_tips: '每頁筆數的欄位名稱。',
  page_size: 'Page size',
  page_size_tips: '每頁筆數。',
  total_count_json_path: 'Total count JSONPath',
  total_count_json_path_tips: 'Response body 中資料總數欄位的 JSONPath。',
  concurrent_request_threads: '請求執行緒數量',
  concurrent_request_threads_tips: '並發執行請求的執行緒數，1 代表依序執行請求。',
  auto_refresh_header_key_of_token: 'Header key of token',
  auto_refresh_header_key_of_token_tips: 'Token 的 header 名稱。',
  auto_refresh_token_prefix_key: 'Header prefix of token',
  auto_refresh_token_prefix_key_tips: '會被加在 header 值中，放在 token 之前。',
  auto_infer_number: '自動推斷數值型別',
  auto_infer_number_tips: '從資料中自動推斷 schema 中數值的資料型別。停用時，資料型別始終為 Double。',

  /** JDBC source */
  delimited_identifier: '分隔識別碼',
  delimited_identifier_tips: '分隔識別碼是將識別碼 (例如欄位名稱、表名稱、索引名稱等) 括在特定的引號或字元中。這種做法允許在識別碼中使用保留字、特殊字元或空格，而不會與 SQL 語法發生衝突。',

  /** SAP RFC source */
  sap_version: 'SAP 版本',
  ashost: 'ASHOST',
  ashost_tips: '特定 SAP 應用程式伺服器的主機名稱。',
  sysnr: 'SYSNR',
  sysnr_tips: 'SAP 系統號碼。',
  client_no: '客戶端編號',
  client_no_tips: '三位數的 ABAP 客戶端編號。定義目標 ABAP 系統的客戶端。',
  rfc_table_name: 'RFC 表格名稱',
  rfc_function_name: 'RFC 函式名稱',
  import_parameters: '導入參數',
  default_value: '預設值',

  //Organization export import
  export_setting: '匯出設定',
  export_all: '匯出全部',
  override: '覆蓋',
  override_tips: '當遇到相同名稱的資料集時，決定要覆蓋還是忽略。',
  export_successfully: '匯出成功！',
  import_setting: '匯入設定',
  place_select_import_resources: '請選擇至少一個要匯出的資源。',

  /** increment/full update */
  time_increment_interval: '時間增量間隔',
  minute_s: '分鐘',
  hour_s: '小時',
  day_s: '天',
  failure_retry_strategy: '失敗重試策略',
  time_interval_seconds: '時間間隔（秒）',
  condition: '條件',
  condition_type: '條件型別',
  condition_value: '條件值',
  connection_timeout: '連線逾時時間 (ms)',
  dis_start_number: '起始值',
  parameter_type: '參數類型',
  immediate_update: '立即更新',
  incremental_update: '增量更新',
  incremental_update_setting: '增量更新設定',
  full_update_setting: '完整更新設定',
  preview_incremental_SQL: '預覽增量更新 SQL 語法',
  preview_full_SQL: '預覽完整更新 SQL 語法',
  last_n_days: 'Last N days',
  save_incremental_update_first: '請鎖上增量更新設定後再送出。',
  save_full_update_first: '請鎖上完整更新設定後再送出。',

  /** Driver management */
  driver: '驅動程式',
  driver_lower: '驅動程式',
  driver_management: '驅動程式管理',
  driver_list: '驅動程式列表',
  class_name: 'Class name',
  file_name: '檔案名稱',
  driver_name: '驅動程式名稱',
  add_driver: '新增驅動程式',
  action: '操作',
  num_drivers: '{num} 個驅動程式',

  /** tenant change notification */
  current_tenant_changed: '當前租戶已改變',
  current_tenant_changed_reload_page: '當前租戶已改變，頁面將於 {time} 秒後自動重新整理。如果您不想等待，請點選重新整理按鈕。',

  /** Copilot */
  enter_message: 'Enter message',
  new_chat: 'New chat',
  dis_copilot: 'DataInsight Copilot',
  sure_to_delete_chat_message: '確定要删除此條記錄嗎？',
  ai_first_message: 'Hi! I\'m DataInsight Copilot, Nice to meet you!',
  'updated:': '更新時間：',

  /** Monitoring */
  history: '歷史紀錄',
  monitoring: '監控',
  sql_monitoring: 'SQL 監控',
  sql_analysis: 'SQL 分析',
  search_sql_statements: '搜尋 SQL 語法',
  sql_slow_counts: 'SQL 慢查詢總數量',
  sql_slow_counts_chart: 'SQL 慢查詢趨勢',
  sql_slow_time: '最慢 SQL 查詢時間',
  sql_slow_time_chart: '最慢 SQL 查詢趨勢',
  'execution_time(sec)': '執行時間（秒）',
  start_time: '開始時間',
  end_time: '結束時間',
  start_date: '開始日期',
  end_date: '結束日期',
  sql_statements: 'SQL 語法',
  times: '次',
  space_times: ' 次',
  sec: '秒',
  space_sec: ' 秒',
  sql_query_count: 'SQL 慢查詢次數',
  sql_query_time: 'SQL 查詢時間',
  real_time_analysis: '即時分析',

  /** Custom dataset share */
  public_link: '公開連結',
  anyone_with_link_can: '知道連結的任何人',
  can_only_view: '只能查看',
  can_only_add_data: '只能新增資料',
  can_edit: '可以編輯',

  // Built-in functions
  built_in_functions: '內建函式',
  "example:": '範例：',
  "result:": '結果：',

  /** Data filling */
  filter_rows: '過濾資料',
  filter_rule_list: '過濾規則列表',
  value1: '值1',
  value2: '值2',
  value1_not_greater_value2: '第一個值必須小於第二個值',
  no_filling_permission: '資料集不存在或資料集未開啟共享。',
  back_to_home: '回到{home}。',
  add_data: '新增資料',

  /** Data lineage */
  data_lineage: '資料血緣',
  table_view: '表格檢視',
  column_view: '欄位檢視',
  script_view: 'SQL 檢視',
  split: '分割畫面',

  /** Data dictionary */
  data_dictionary: '資料字典',
  data_list: '資料列表',
  schema_length: '綱要 ({length})',
  dataset_path: '資料集路徑',
  dataset_name_type_description: '資料集名稱、類型、描述',

  /** Levels */
  data_security: '資料安全',
  security_levels: '安全級別',
  security_level: '安全級別',
  security_level_list: '安全級別列表',
  num_security_levels: '{num} 個安全級別',
  security_level_name: '安全級別名稱',
  security_level_name_lower: '安全級別名稱',
  sure_to_delete_level: '確定要刪除此級別嗎？',
  sure_to_delete_levels: '確定要刪除已選擇的級別嗎？',
  max_level_allow: '最多只可新增 5 個級別',
  connected_dataset: '關聯的資料集',

  /** Job management */
  dis_pending: '待執行',
  running: '執行中',
  finished: '完成',
  error: '錯誤',
  abort: '中斷',

  /** New */
  nothing: '無',
  update: '更新',
  insert_on_conflict_strategy: '插入衝突策略',
  conflict_columns: '衝突欄位',
  constraint_setting: '限制設定',
  constraint: '限制',
  constraint_name_repeat: '限制名稱不得重複。',
  constraint_name: '限制名稱',
  constraint_type: '限制類型',
  unique_constraint: '唯一限制',
  level_info: '級別資訊',
  executor: '執行者',
  no_constraint_add_first: '找不到 UNIQUE 限制類型的欄位。請先編輯資料集，於限制設定新增 UNIQUE 限制類型的欄位，再於此處進行選擇。',
  task_no: '任務編號',
  sepOption_1: '逗號 (,)',
  sepOption_2: '分號 (;)',
  sepOption_3: '空白 ( )',
  sepOption_4: 'Tab 鍵 (\\t)',
  sepOption_5: '其它',
  other_sep: '其它分隔符號',
  dis_sep_desc: '每個欄位和值的分隔符號。此分隔符號可以是一個或多個字元。',
  log_user: '使用者',
  log_driver: '驅動程式',
  log_parameter: '參數',
  log_org: '組織',
  log_role: '角色',
  log_team: '團隊',
  log_securityLevel: '安全級別',
  log_application: '應用程式',
  log_group: '分組',
  log_dataset: '資料集',
  'log_dataset/message': '資料集/資訊',
  'log_dataset/updateType': '資料集/更新策略',
  'log_dataset/alarm': '資料集/警報',
  log_udf: '擴充函式',
  log_source: '資料來源',
  log_job: '作業',
  log_insert: 'Insert',
  log_edit: 'Edit',
  log_delete: 'Delete',
  operation_time: '操作時間',
  operation_type: '操作類型',
  target: '目標',
  target_name: '目標名稱',
  operational_logs: '操作紀錄',
  logs: '紀錄',
  format_sql: '格式化 SQL',
  dis_full_update_tips: '資料集將依照更新設定裡的設定值進行更新。',
  server_selection_timeout: '伺服器選擇逾時時間 (ms)',
  server_selection_timeout_tips: '客戶端嘗試與 MongoDB 伺服器建立連線時，如果在指定的時間內無法選擇到可用的伺服器，則會觸發逾時錯誤。',
  operator: '操作者',
  fixed_survival_time: '固定存活時間',
  api_url: 'API 網址',
  tenant_id: '租戶 ID',
  search_executor: '搜尋執行者',
  interface: '接口',
  source: '來源',
  table_name: '資料表名稱',
  export_table: '匯出資料表',
  export_schema: '匯出綱要',
  import_schema: '匯入綱要',
  data_counts: '資料筆數',
  data_timezone: '資料時區',
  json: 'JSON',
  incremental_setting_start_time_tips: '開始時間不包含時區。如果該欄位在來源資料庫中有時區設置，請將值轉換為 UTC+0 時區的時間。',
  policy_everyday_tips: '第一次刷新快取的時間，之後每天的相同時間會刷新快取。',
  fail_upload_fail_datatype: '無法上傳檔案，檔案中包含不支持的欄位型別。',
  last_completed_time: '最後成功執行時間',
  api_token: 'API token',
  bucket: 'Bucket',
  influx_v2_org_tips: '組織是一組使用者的工作空間。',
  influx_v2_bucket_tips: '時間序列資料的儲存位置。',
  agent_builder: 'AI 智慧助理',
  ai_chat_bot: '與資料對話',
  stop_sec: '停止（{time} 秒）',
  ai_assistant: 'AI 助手',
  ai_explain: '解釋',
  ai_rewrite: '重寫',
  ai_rewrite_ask: '提問並重寫',
  ai_result: 'AI 結果',
  ai_assistant_placeholder: '請輸入問題',
  try_again: '再次嘗試',
  discard: '忽略',
  accept: '接受',
  ai_mirror_placeholder: '請輸入 SQL，或按空白鍵開啟 AI 助手',
  copilot_enabled_tips: '啟用 Copilot',
  alarm_event: '警報事件',
  no_events: '還沒有事件。',
  no_events_tips: '點選「規則設定」按鈕添加規則！',
  rule_setting: '規則設定',
  event_id: '事件 ID',
  last_update_time: '上次更新時間',
  first_triggered_time: '首次觸發時間',
  released_time: '解除時間',
  trigger_data: '觸發數據',
  no_trigger_data_tips: '請選擇上面的一行。',
  time: '時間',
  rule_information: '規則資訊',
  trigger_rule: '觸發規則',
  trigger_rule_lower: '觸發規則',
  trigger_rule_list: '觸發規則列表',
  add_rule_tips: '點選「+」按鈕在此處添加一些規則！',
  trigger_rule_name: '觸發規則名稱',
  trigger_notification: '觸發通知',
  trigger_notification_group: '通知群組（觸發）',
  release_notification: '解除通知',
  release_notification_group: '通知群組（解除）',
  add_trigger_rule: '添加觸發規則',
  trigger_rule_information: '觸發規則資訊',
  input_mode: '設定模式',
  input_mode_tips: '使用高級設定後，如果您希望使用基本模式，則已設定的規則將被清除。',
  sql_editor: 'SQL 編輯器',
  notification_setting: '通知設定',
  check_frequency: '檢查頻率',
  check_type: '檢查類型',
  same_as_update_strategy: '與更新策略相同',
  customized: '自定義',
  basic_: '基本',
  value: '值',
  preview_execution_sql: '預覽執行 SQL',
  execution_sql: '執行 SQL',
  last_updated_time: '上次更新時間',
  event_logs: '事件日誌',
  triggered: '已觸發',
  released: '已釋放',
  current_event: '當前事件',
  history_event: '歷史事件',
  switch_input_mode: '切換輸入模式',
  sure_switch_basic: '切換到基本模式將清除所有輸入的內容。 你確定嗎？',
  sure_switch_sql: '切換到 SQL 編輯器模式將清除所有輸入的內容。 你確定嗎？',
  partition_setting: '分區設定',
  portal_url_tips: 'DataInsight portal 的公開 URL。',
  alarm_log_records: '警報歷史紀錄',
  alarmlog_retention_policy_days: '警報歷史紀錄的保留天數。',
  alarmlog_vacuum_start_time: '每天刪除警報歷史紀錄的開始時間。',
  event_center_enabled_tips: '與 Event Center 整合以發出警報通知。',
  quota_management: '配額管理',
  quota_overview: 'Quota overview',
  quota_settings: 'Quota settings',
  resource_group: '資源組',
  log_resourcegroup: '資源組',
  resource_group_lower: '資源組',
  resource_info: '資源資訊',
  resource_group_list: '資源組列表',
  resource_group_name: '資源組名稱',
  sure_to_delete_resource_group: '確定要刪除此資源組嗎？所有設定都會被刪除。',
  sure_to_delete_resource_groups: '確定要刪除已選擇的資源組嗎？所有設定都會被刪除。',
  num_resource_group: '{num} 個資源組',
  add_resource_group: '新增資源組',
  resource_monitor: '資源監控',
  driver_memory_unit: '驅動器記憶體 (GiB)',
  driver_memory: '驅動器記憶體',
  resource_list: '資源列表',
  sec_lower: '秒',
  gib: 'GiB',
  cores: 'Cores',
  space_gib: ' GiB',
  space_cores: ' cores',
  cores_lower: 'cores',
  'cpu:': 'CPU: ',
  'memory:': '記憶體: ',
  'cpu': 'CPU',
  'memory': '記憶體',
  resource_total: '資源總數量',
  driver_resource_total: '驅動器資源總數量',
  executor_resource_total: '執行器資源總數量',
  resource_chart: '資源趨勢',
  executor_counts: '執行器個數',
  executor_cpu_unit: '執行器 CPU (Cores)',
  executor_memory_unit: '執行器記憶體 (GiB)',
  executor_cpu: '執行器 CPU',
  executor_memory: '執行器記憶體',
  binding_org: '綁定組織',
  resource_driver: '驅動器',
  resource_executor: '執行器',
  metric_management: '指標管理',
  metric_develop: '指標開發',
  metric_catalog: '指標目錄',
  metric_name: '指標名稱',
  metric_code: '指標標識',
  metric_definition: '業務口徑',
  no_metric_list: '還沒有指標。',
  select_add_group_first: '從左側面板新增或選擇分組。',
  atomic_metric: '原子指標',
  derived_metric: '派生指標',
  composite_metric: '複合指標',
  add_atomic_metric: '添加原子指標',
  add_derived_metric: '添加派生指標',
  add_composite_metric: '添加複合指標',
  save_destination: '存儲位置',
  business_properties: '業務屬性',
  computational_attributes: '計算屬性',
  metric_column: '指標欄位',
  aggregation_method: '聚合方式',
  dimension_management: '唯獨管理',
  data_scope: '資料範圍',
  full_data: '完整資料',
  incremental_data: '增量資料',
  unsupported_data_scope_full: '不能使用完整資料檢查，請修改！',
  unsupported_data_scope_incremental: '不能使用增量資料檢查，請修改！',
  request_table_size: '請求資料分片大小',
  request_table_size_tips: '該值設定的越小，產生的分區就越多。這樣會增加 Spark 端的並行度，但同時會對 Doris 造成更大的壓力。',
  batch_size: '批量大小',
  batch_size_tips: '一次從 BE 讀取資料的最大行數。增加該值可以減少Spark與Doris之間的連接數。從而減少因網路延遲而帶來的額外時間開銷。',
  query_memory_limit: '查詢記憶體上限 (MB)',
  query_memory_limit_tips: '單一查詢的記憶體限制。（以位元組為單位）',
  query_timeout: '査詢逾時時間 (s)',
  dataset_no_enabled_job: '此資料集沒有啟用中的作業',
  function_group_name_string_and_binary_functions: "字串和二進制函式",
  function_group_name_numeric_scalar_functions: "數值純量函數",
  function_group_name_aggregate_functions: "聚合函式",
  function_group_name_ranking_window_functions: "排名視窗函式",
  function_group_name_analytic_window_functions: "分析視窗函式",
  function_group_name_array_functions: "陣列函式",
  function_group_name_map_functions: "映射函式",
  function_group_name_date_timestamp_and_interval_functions: "日期、時間戳記和間隔函式",
  function_group_name_cast_functions_and_constructors: "轉換函式和建構函式",
  function_group_name_csv_functions: "CSV 函式",
  function_group_name_json_functions: "JSON 函式",
  function_group_name_xpath_functions: "XPath 函式",
  function_group_name_miscellaneous_functions: "其他函式",
  function_des_aes_decrypt: "解密使用 AES 加密產生的二進位檔。",
  function_des_aes_encrypt: "使用 AES 加密來加密二進位檔。",
  function_des_ascii: "回傳 str 中第一個字元的 ASCII 碼點。",
  function_des_base64: "將 expr 轉換為 base 64 字串。",
  function_des_bin: "回傳 expr 的二進制值。",
  function_des_binary: "將 expr 值強制轉為二進制。",
  function_des_bit_length: "回傳字串資料的位元長度或二進制資料的位元數。",
  function_des_btrim: "移除字串開頭與結尾的空白字元或其他指定的字元。",
  function_des_char: "回傳具有與 expr 對應的二進制值的 ASCII 字元。如果 n 大於 256，則結果等於 chr(n%256)。",
  function_des_char_length: "回傳字串資料的字元長度或二進制資料的位元組數。",
  function_des_character_length: "回傳字串數據的字元長度或二進位數據的位元組數。",
  function_des_chr: "回傳與 expr 對應的二進位值的 ASCII 字元。如果 n 大於 256，則結果等於 chr(n%256)。",
  function_des_concat: "回傳參數的串接字串。",
  function_des_concat_ws: "回傳由 sep 分隔的串接字串。",
  function_des_contains: "回傳一個布林值。如果在 left 找到 right，則回傳 true。如果任一個輸入表示式為 NULL，則回傳 NULL。否則，回傳 false。left 或 right 必須為 STRING 或 BINARY 類型。",
  function_des_crc32: "回傳 expr 的循環冗餘檢查值。",
  function_des_decode: "使用字元集編碼 charset 將二進制 expr 轉換為字串。",
  function_des_encode: "使用字元集編碼 charset 將字串 expr 轉換為二進制。",
  function_des_endswith: "回傳一個布林值。如果 expr 以 endExpr 作為結尾，則回傳 true。如果任一個輸入表示式為 NULL，則回傳 NULL。否則，回傳 False。expr 或 endExpr 必須為 STRING 或 BINARY 類型。",
  function_des_find_in_set: "回傳字串在逗號分隔的字串清單中的位置。",
  function_des_format_number: "設定 expr 的格式（如#,###,###.##），四捨五入到指定的小數位數（scale）。",
  function_des_format_string: "從 printf 樣式的格式字串回傳一個格式化的字串。",
  function_des_hex: "將 expr 轉換為十六進制。",
  function_des_initcap: "將 expr 中每個單字的第一個字母轉換為大寫字母。",
  function_des_instr: "回傳 substr 在 str 中首次出現的索引（從 1 開始計數）。",
  function_des_lcase: "將 expr 中的所有字元轉換為小寫字母。",
  function_des_left: "回傳 str 最左邊的 len 個字元。",
  function_des_len: "回傳字串資料的字元長度，或者二進制資料的位元組數。字串資料的長度包括結尾的空格，而二進制的長度包括二進制零。",
  function_des_length: "回傳字串資料的字元長度或二進制資料的位元組數。",
  function_des_levenshtein: "回傳字串 str1 和 str2 之間的萊文斯坦距離，也就是由一個字串轉成另一個字串所需的最少編輯次數。",
  function_des_locate: "回傳 substr 在 pos 位置之後的 str 中首次出現的索引位置。",
  function_des_lower: "將 expr 中的所有字元轉換為小寫字母。",
  function_des_lpad: "回傳 expr，左側以 pad 填充，使其填充後的長度為 len。",
  function_des_ltrim: "回傳 str，其中移除了 trimstr 內的前導字元。",
  function_des_mask: "對給定的字串進行遮罩。此函式將字元替換為 'X' 或 'x'，將數字替換為 'n'。這對於建立已刪除敏感資訊的資料表的副本可能很有用。",
  function_des_md5: "將 expr 轉換成 128 位 MD5 校驗碼，並以十六進制字串表示。",
  function_des_octet_length: "回傳字串資料的位元組長度或二進制資料的位元組數。",
  function_des_overlay: "將起始於位置 pos 且長度為 len 的 input 替換為 replace。",
  function_des_parse_url: "從 url 中擷取指定的部分。",
  function_des_position: "回傳 substr 在 pos 位置之後第一次出現在 str 中的位置。",
  function_des_printf: "回傳一個使用 printf-style 格式的格式化字串。",
  function_des_regexp_count: "回傳正規表示式模式 regexp 在 str 中相符的次數。",
  function_des_regexp_extract: "擷取 str 中與正規表示式相符並對應到正規表示式群組索引的第一個字串。",
  function_des_regexp_extract_all: "擷取 str 中符合 regexp 運算式的所有字串，並對應至 regex 群組索引。",
  function_des_regexp_instr: "在字串中搜尋正規表示式，並傳回一個指出相符子字串的開始位置的整數。位置從 1 開始計數，而非從 0 開始計數。如果找不到相符項目，則回傳 0。",
  function_des_regexp_replace: "將 str 中與 regexp 相符的所有子字串替換為 rep。",
  function_des_regexp_substr: "回傳與 str 中符合 regexp 的第一個子字串。如果未找到，則回傳 NULL。",
  function_des_repeat: "回傳將 expr 重複 n 次的字串。",
  function_des_replace: "將 str 中所有出現的 search 都替換為 replace。",
  function_des_reverse: "回傳一個反向字串或一個元素順序相反的陣列。",
  function_des_right: "回傳字串 str 中最右邊的 len 個字元。",
  function_des_rpad: "回傳 expr，右側以 pad 填充，使其填充後的長度為 len。",
  function_des_rtrim: "移除字串結尾的空白字元或其他指定的字元。",
  function_des_sentences: "將 str 分割為一個包含單字陣列的陣列。",
  function_des_sha: "將 expr 的 SHA1 雜湊值作為十六進制字串回傳。",
  function_des_sha1: "將 expr 的 SHA1 雜湊值作為十六進制字串回傳。",
  function_des_sha2: "將 expr 的 SHA-2 家族的校驗碼作為十六進制字串回傳。",
  function_des_soundex: "回傳字串的 soundex 碼。",
  function_des_space: "回傳由 n 個空格組成的字串。",
  function_des_split: "將 str 依照與正規表示式相符之處進行拆分，並回傳長度最多為 limit 的陣列。",
  function_des_split_part: "根據 delimiter 拆分 str，並回傳拆分後的第 partNum 部分（從 1 開始計數）。",
  function_des_startswith: "回傳一個布林值。如果 expr 以 startExpr 作為開頭，則回傳 true。如果任一個輸入表示式為 NULL，則回傳 NULL。否則，回傳 false。expr 和 startExpr 都必須是 STRING 或 BINARY 類型。",
  function_des_string: "將 expr 強制轉換為 STRING。",
  function_des_substr: "回傳 expr 的子字串（從 pos 開始，並且長度為 len）。",
  function_des_substring: "回傳 expr 的子字串（從 pos 開始，並且長度為 len）。",
  function_des_substring_index: "回傳在分隔符號（delim）出現的次數（count）之前的字串部分。",
  function_des_to_binary: "根據提供的 fmt，將輸入的 str 轉換為二進制值。fmt 可以是不區分大小寫的字串，可以是 hex、utf-8、utf8 或 base64。如果省略 fmt，則轉換的二進制格式預設為 hex。如果輸入參數中至少有一個為 NULL，則此函式將回傳 NULL。",
  function_des_to_char: "根據 formatExpr，將 numberExpr 轉換為字串。",
  function_des_to_number: "根據字串格式 fmt，將字串 expr 轉換為數字。",
  function_des_translate: "回傳一個 expr，其中 from 內的所有字元都被替換為 to 中的字元。",
  function_des_trim: "移除字串開頭和結尾的所有空白字元。",
  function_des_try_to_binary: "此函式為 to_binary 的特殊版本，會執行相同的操作，但如果無法進行轉換，則回傳 NULL 值而非引發錯誤。",
  function_des_ucase: "將 expr 中的所有字元轉換為大寫字母。",
  function_des_unbase64: "以二進制形式回傳已解碼的 base64 字串。",
  function_des_unhex: "將十六進制 expr 轉換為二進制。",
  function_des_upper: "將 expr 中的所有字元轉換為大寫字母。",
  function_des_url_decode: "解碼以特定編碼方案編碼的 application/x-www-form-urlencoded 格式的字串。",
  function_des_url_encode: "使用特定編碼方案將字串轉換為 application/x-www-form-urlencoded 格式。",
  function_des_abs: "回傳 expr 的絕對值。",
  function_des_acos: "回傳 expr 的反餘弦值（arccosine）。",
  function_des_acosh: "回傳 expr 的反雙曲餘弦值。",
  function_des_asin: "回傳 expr 的反正弦值（arcsine）。",
  function_des_asinh: "回傳 expr 的反雙曲正弦值。",
  function_des_atan: "回傳 expr 的反正切值（arctangent）。",
  function_des_atan2: "回傳在一個平面上，正 x 軸和由座標 (exprX, exprY) 指定的點之間的弧度角。",
  function_des_atanh: "回傳expr的反雙曲正切值。",
  function_des_bigint: "將 expr 強制轉換為 BIGINT。",
  function_des_bit_count: "回傳 expr 的位數。",
  function_des_bit_get: "回傳指定位置的位元值（0 或 1）。位元位置從右到左編號，從零開始計算。",
  function_des_bround: "回傳使用銀行家捨入法 (HALF_EVEN) 運算後的 expr。",
  function_des_cbrt: "回傳 expr 的立方根。",
  function_des_ceil: "回傳不小於 expr 的最小值。",
  function_des_ceiling: "回傳不小於 expr 的最小值。",
  function_des_conv: "將 num 從 fromBase 轉換為 toBase。",
  function_des_convert_timezone: "將來源時區 sourceTs 的時間戳記轉換為目標時區 targetTz。",
  function_des_cos: "回傳 expr 的餘弦值。",
  function_des_cosh: "回傳 expr 的雙曲餘弦。",
  function_des_cot: "回傳 expr 的餘切值。",
  function_des_csc: "回傳 expr 的餘割，計算如同 1/java.lang.Math.sin。",
  function_des_degrees: "將弧度轉換為角度。",
  function_des_double: "將 expr 強制轉換為 DOUBLE。",
  function_des_e: "回傳常數 e。",
  function_des_exp: "回傳 e ^ expr。",
  function_des_expm1: "回傳 e ^ expr - 1。",
  function_des_factorial: "回傳 expr 的階乘。",
  function_des_float: "將 expr 值強制轉換為 FLOAT。",
  function_des_floor: "回傳不大於 expr 的最大值。",
  function_des_getbit: "回傳指定位置的位元值（0 或 1）。位置從右到左編號，從零開始。位置參數不能為負數。",
  function_des_hypot: "回傳 sqrt（expr1 * expr1 + expr2 * expr2）。",
  function_des_int: "將 expr 強制轉換為 INTEGER。",
  function_des_isnan: "若 expr 為 NaN，則回傳 true。",
  function_des_ln: "回傳 expr 的自然對數（以 e 為底）。",
  function_des_log: "回傳 expr 的對數（以 base 為底）。",
  function_des_log10: "回傳 expr 的對數（以 10 為底）。",
  function_des_log1p: "回傳 log（1 + expr）。",
  function_des_log2: "回傳 expr 的對數（以 2 為底）。",
  function_des_mod: "回傳進行 dividend / divisor 運算後的餘數。",
  function_des_nanvl: "如果不是 NaN 則回傳 expr1，否則回傳 expr2。",
  function_des_negative: "回傳 expr 的否定值。",
  function_des_pi: "回傳 pi。",
  function_des_pmod: "回傳進行 dividend / divisor 運算後的正餘數。",
  function_des_positive: "回傳 expr 的值。",
  function_des_pow: "將 expr1 的次方提高到 expr2 的幂。",
  function_des_power: "將 expr1 的次方提高到 expr2 的幂。",
  function_des_radians: "將角度轉換為弧度。",
  function_des_rand: "回傳介於 0 和 1 之間的隨機值。",
  function_des_randn: "從標準常態分布回傳一個隨機值。",
  function_des_random: "回傳介於 0 和 1 之間的隨機值。",
  function_des_rint: "回傳將 expr 四捨五入為整數的 DOUBLE 值。",
  function_des_round: "回傳將 expr 四捨五入運算後的結果。",
  function_des_shiftleft: "回傳一個左移 n 位的位元運算後的值。",
  function_des_shiftright: "回傳一個帶符號整數右移 n 位的位元運算後的值。",
  function_des_shiftrightunsigned: "回傳一個位元無符號整數右移 n 位的位元運算後的值。",
  function_des_sign: "當 expr 為負數、0 或正數時回傳 -1、0 或 1。",
  function_des_signum: "當 expr 為負數、0 或正數時回傳 -1、0 或 1。",
  function_des_sec: "回傳 expr 的正割值，計算如同 1/java.lang.Math.cos。",
  function_des_sin: "回傳 expr 的正弦值。",
  function_des_sinh: "回傳 expr 的雙曲正弦。",
  function_des_sqrt: "回傳 expr 的平方根。",
  function_des_tan: "回傳 expr 的正切。",
  function_des_tanh: "回傳 expr 的雙曲正切。",
  function_des_try_add: "回傳 expr1 和 expr2 的總和，若溢出，則結果為 NULL。可接受的輸入類型與 + 運算元相同。",
  function_des_try_divide: "回傳 dividend/divisor 的結果。如果 divisor 為 0，則結果始終為 NULL。dividend 必須是數值或間隔。divisor 必須是數值。",
  function_des_try_multiply: "回傳 expr1*expr2，若溢出，則結果為 NULL。可接受的輸入類型與 * 運算元相同。",
  function_des_try_subtract: "回傳 expr1-expr2，若溢出，則結果為 NULL。可接受的輸入類型與 - 運算元相同。",
  function_des_try_to_number: "使用格式化的 fmt 將 expr 轉換為十進制，如果 expr 與格式不相符則回傳 NULL。",
  function_des_width_bucket: "回傳在最小值 min_value 到最大值 max_value 範圍內，將 value 分配到具有 num_bucket 個 bucket 的等寬直方圖中的 bucket 號碼。",
  function_des_any: "如果 expr 群組中至少有一個值為 true，則回傳 true。",
  function_des_any_value: "回傳 expr 中的單個非確定值。",
  function_des_approx_count_distinct: "回傳在群組 expr 中估計的不同值的數量。",
  function_des_approx_percentile: "回傳 expr 在群組內的近似百分位數。",
  function_des_array_agg: "收集並回傳一個包含非唯一元素的清單。",
  function_des_avg: "將群組中的值計算出平均值。",
  function_des_bit_and: "回傳群組中所有輸入值位元運算 AND 的結果。",
  function_des_bit_or: "回傳群組中所有輸入值位元運算 OR 的結果。",
  function_des_bit_xor: "回傳群組中所有輸入值位元運算 XOR 的結果。",
  function_des_bool_and: "如果群組內所有值都為 true，則回傳 true。",
  function_des_bool_or: "如果群組內至少一個值為 true，則回傳 true。",
  function_des_collect_list: "回傳一個陣列，該陣列由 expr 中的所有值組成。",
  function_des_collect_set: "回傳一個陣列，該陣列由 expr 中的所有唯一值組成。",
  function_des_corr: "回傳一個數字對群組之間的皮爾森相關係數。",
  function_des_count: "回傳在一個群組中檢索到的總行數，包括包含 NULL 的行。",
  function_des_count_if: "回傳 expr 中的 true 值數量。",
  function_des_count_min_sketch: "使用 epsilon、confidence、seed，回傳 expr 群組中所有值的 count-min sketch。",
  function_des_covar_pop: "回傳群組中數值對的母體共變異數。",
  function_des_covar_samp: "回傳群組中數值對的樣本共變異數。",
  function_des_every: "如果群組中的所有值均為 true，則回傳 true。",
  function_des_first: "回傳群組中的第一個值。",
  function_des_first_value: "回傳群組中的第一個值。",
  function_des_kurtosis: "計算群組的 kurtosis 值。",
  function_des_last: "回傳群組中的最後一個值。",
  function_des_last_value: "回傳群組中的最後一個值。",
  function_des_max: "回傳群組中的最大值。",
  function_des_max_by: "回傳在群組中，與 expr2 最大值相關的 expr1。",
  function_des_mean: "計算群組的平均值。",
  function_des_median: "回傳數字或 ANSI 區間欄 col 的中位數。",
  function_des_min: "回傳 expr 中的最小值。",
  function_des_min_by: "回傳在群組中，與 expr2 最小值相關的 expr1。",
  function_des_mode: "回傳 col 中最頻繁的值。NULL 值將被忽略。如果所有值都是 NULL，或者行數為 0，則回傳 NULL。",
  function_des_percentile: "回傳指定百分比的 expr 的精確百分位數。",
  function_des_percentile_approx: "回傳 expr 在群組內的近似百分位數。",
  function_des_regr_avgx: "回傳群組中非空值對的自變量的平均值，其中 y 是因變量，x 是自變量。",
  function_des_regr_avgy: "回傳群組中非空值對的因變量的平均值，其中 y 是因變量，x 是自變量。",
  function_des_regr_count: "回傳群組中非空數字對的數量，其中 y 是因變量，x 是自變量。",
  function_des_regr_intercept: "回傳群組中非空值對的單變量線性回歸線的截距，其中 y 是因變量，x 是自變量。",
  function_des_regr_r2: "回傳群組中非空值對的決定係數，其中 y 是因變量，x 是自變量。 ",
  function_des_regr_slope: "回傳群組中非空值對的線性回歸線的斜率，其中 y 是因變量，x 是自變量。",
  function_des_regr_sxx: "對於群組中的非空值對，回傳 REGR_COUNT(y, x) * VAR_POP(x)，其中 y 是因變量，x 是自變量。",
  function_des_regr_sxy: "對於群組中的非空值對，回傳 REGR_COUNT(y, x) * COVAR_POP(y, x)，其中 y 是因變量，x 是自變量。",
  function_des_regr_syy: "對於群組中的非空值對，回傳 REGR_COUNT(y, x) * VAR_POP(y)，其中 y 是因變量，x 是自變量。",
  function_des_skewness: "計算群組的偏差值。",
  function_des_some: "如果 expr 中至少有一個值為 true，則回傳 true。",
  function_des_std: "計算群組的樣本標準差。",
  function_des_stddev: "計算群組的樣本標準差。",
  function_des_stddev_pop: "計算群組的母體標準差。",
  function_des_stddev_samp: "計算群組的樣本標準差。",
  function_des_sum: "計算群組中的值的總和。",
  function_des_try_avg: "回傳根據一組值計算的平均值，若溢出則結果為 NULL。",
  function_des_try_sum: "回傳根據一組值計算得出的總和，若溢出則結果為 NULL。",
  function_des_var_pop: "計算群組的母體變異數。",
  function_des_var_samp: "計算群組的樣本變異數。",
  function_des_variance: "計算群組的樣本變異數。",
  function_des_dense_rank: "回傳一個值在分區中相對於所有值的排名。",
  function_des_ntile: "將每個視窗分區的列分割為從 1 到最多 n 個的 bucket。",
  function_des_percent_rank: "計算分區中某個值的百分比排名。",
  function_des_rank: "回傳某個值相對於分區中所有值的排名。",
  function_des_row_number: "按照視窗分區內的列順序，為每列分配一個唯一的連續編號（從 1 開始）。",
  function_des_cume_dist: "回傳某個值相對於分區中所有值的位置。",
  function_des_lag: "回傳 expr 的分區內前一列中的值。",
  function_des_lead: "回傳 expr 的分區內後一列中的值。",
  function_des_nth_value: "回傳距視窗框架開頭第 offset 行的輸入值。Offset從 1 開始。如果 ignoreNulls = true，則在查找 offsetth 行時將跳過 NULL。否則，每一行都會計算偏移量。如果不存在這樣的第 offset 行（例如，當 offset 為 10 時，視窗框架的大小小於 10），則回傳 NULL。",
  function_des_aggregate: "使用自定義聚合器聚合陣列中的元素。",
  function_des_array: "回傳一個陣列，其中包含 expr 中的元素。",
  function_des_array_append: "回傳一個在其最後追加了指定元素的陣列。",
  function_des_array_compact: "移除陣列中所有的 NULL 值。",
  function_des_array_contains: "如果 array 中包含 value，則回傳 true。",
  function_des_array_distinct: "從 array 中刪除重複值。",
  function_des_array_except: "找出在 array1 中，但不在 array2 中的元素，在去掉重複的元素後回傳新的陣列。",
  function_des_array_insert: "回傳一個擴展的陣列 array，在該陣列的指定索引位置 index 插入元素 elem。",
  function_des_array_intersect: "回傳在 array1 中存在，但不存在於 array2 中的元素。",
  function_des_array_join: "串接 array 的元素。",
  function_des_array_max: "回傳 array 中的最大值。",
  function_des_array_min: "回傳 array 中的最小值。",
  function_des_array_position: "回傳 array 中第一次出現 element 的位置。",
  function_des_array_remove: "從 array 中刪除所有出現的 element。",
  function_des_array_repeat: "回傳包含 element count 次的陣列。",
  function_des_array_size: "回傳陣列的大小。",
  function_des_array_sort: "回傳根據 func 排序的 array。",
  function_des_array_union: "回傳一個由 array1 和 array2 的元素組成的陣列，並且去除重複的元素。",
  function_des_arrays_overlap: "如果 array1 和 array2 的交集不為空，則回傳 true。",
  function_des_arrays_zip: "回傳一個合併的結構陣列，其中第 n 個結構包含所有輸入陣列的第 n 個值。",
  function_des_cardinality: "回傳 expr 的大小。",
  function_des_element_at: "回傳 arrayExpr 的元素中索引為 index 的值。",
  function_des_exists: "如果 expr 中的任何元素對 pred 為真，則回傳 true。",
  function_des_explode: "將字串按照指定的分隔符號拆分成陣列。",
  function_des_explode_outer: "使用外部語義將字串拆分成陣列。",
  function_des_filter: "將 expr 中的陣列使用函式 func 進行篩選。",
  function_des_flatten: "將陣列的陣列轉為單一陣列。",
  function_des_forall: "測試 func 是否對陣列中的所有元素都有效。",
  function_des_get: "回傳陣列在給定（以0為基礎的）索引處的元素。如果索引超出陣列範圍，則此函式回傳 NULL。",
  function_des_inline: "將結構陣列分解為一個表格。",
  function_des_inline_outer: "將結構陣列分解為一個具有外部語義的表格。",
  function_des_posexplode: "透過位置編號取消陣列的嵌套。",
  function_des_posexplode_outer: "使用外部語義，透過位置編號取消陣列的嵌套。",
  function_des_reduce: "對初始狀態和陣列中的所有元素應用二進制運算元，並將其減少為單一狀態。最終狀態會藉由使用完成函數轉換為最終結果。",
  function_des_sequence: "產生一個陣列，其中包含從 start 到 stop（含）的元素，這些元素按 step 遞增。",
  function_des_shuffle: "將陣列中的元素隨機排列。",
  function_des_size: "回傳 expr 的基數。",
  function_des_slice: "回傳陣列的子集合。",
  function_des_sort_array: "回傳排序後的陣列。",
  function_des_transform: "使用函式 func 轉換 expr 中的陣列元素。",
  function_des_try_element_at: "回傳陣列在給定（以1為基礎的）索引處的元素。",
  function_des_zip_with: "按照函式 func，將 expr1 和 expr2 中的陣列元素合併為單一陣列。",
  function_des_map: "建立一個包含指定鍵-值對的映射。",
  function_des_map_concat: "回傳所有 expr 映射表示式的聯集。",
  function_des_map_contains_key: "如果映射包含該鍵，則回傳 true。",
  function_des_map_entries: "回傳 map 中所有條目的無序陣列。",
  function_des_map_filter: "使用 func 函式在 expr 中篩選映射中的條目。",
  function_des_map_from_arrays: "使用鍵對和值陣列建立映射。",
  function_des_map_from_entries: "建立一個從指定的條目陣列建立的映射。",
  function_des_map_keys: "回傳包含映射鍵的無序陣列。",
  function_des_map_values: "回傳包含映射值的無序陣列。",
  function_des_map_zip_with: "將 map1 和 map2 合併到一個映射中。",
  function_des_str_to_map: "使用分隔符號將表示式拆分成鍵-值對後回傳一個映射。",
  function_des_transform_keys: "使用 func 函式在 expr 中轉換映射中的鍵。",
  function_des_transform_values: "使用 func 函式在 expr 中轉換映射中的值。",
  function_des_add_months: "回傳距離 startDate 後 numMonths 個月的日期。",
  function_des_curdate: "回傳查詢評估開始時的當前日期。同一查詢中的所有 curdate 呼叫將回傳相同的值。",
  function_des_current_date: "回傳當前日期。",
  function_des_current_timestamp: "回傳當前的時間戳記。",
  function_des_current_timezone: "回傳當前會話的本地時區。",
  function_des_date: "將 expr 值強制轉換為 DATE。",
  function_des_date_add: "回傳距離 startDate 後 numDays 天的日期。",
  function_des_dateadd: "新增時間 value 至 expr，時間的單位為 unit。",
  function_des_date_diff: "回傳從 startDate 到 endDate 的天數。",
  function_des_date_from_unix_date: "回傳自 1970-01-01 以來過了指定天數的日期。",
  function_des_date_format: "將時間戳記轉換為 fmt 格式的字串。",
  function_des_date_part: "擷取日期、時間戳記或間隔的一部分。",
  function_des_date_sub: "回傳距離 startDate 前 numDays 天的日期。",
  function_des_date_trunc: "回傳按指定的單位截斷的時間戳記。",
  function_des_datediff: "回傳從 startDate 到 endDate 的天數。",
  function_des_day: "回傳日期或時間戳記的月份日期。",
  function_des_dayofmonth: "回傳日期或時間戳記是一個月中的第幾天。",
  function_des_dayofweek: "回傳日期或時間戳記是一星期中的第幾天。",
  function_des_dayofyear: "回傳日期或時間戳記是一年中的第幾天。",
  function_des_extract: "回傳 source 的 field。",
  function_des_from_unixtime: "回傳 fmt 中的 unixTime。",
  function_des_from_utc_timestamp: "在時區 timeZone 中以 UTC 指定的方式回傳 expr 的時間戳記。",
  function_des_hour: "回傳時間戳記的小時部分。",
  function_des_last_day: "回傳日期所屬月份的最後一天。",
  function_des_make_date: "從 year、month 和 day 欄位建立日期。",
  function_des_make_dt_interval: "從天數（days）、小時（hours）、分鐘（mins）和秒（secs）建立 DayTimeIntervalType 期間。",
  function_des_make_interval: "從 years、months、weeks、days、hours、mins 和 secs 建立間隔。",
  function_des_make_timestamp: "從 year、month、day、hour、min、sec 和 timezone 欄位建立時間戳記。",
  function_des_make_ym_interval: "根據年份和月份建立年-月區間。",
  function_des_minute: "回傳 expr 中時間戳記的分鐘部分。",
  function_des_month: "回傳 expr 中時間戳記的月份部分。",
  function_des_months_between: "回傳 expr1 和 expr2 中的日期或時間戳記之間已過去的月數。",
  function_des_next_day: "回傳晚於 expr 並已按 dayOfWeek 命名的第一個日期。",
  function_des_now: "回傳當前的時間戳記。",
  function_des_quarter: "回傳 expr 為該年度的第幾季（範圍為 1 到 4）。",
  function_des_second: "回傳 expr 時間戳記中的秒數。",
  function_des_timestamp: "將 expr 強制轉換為 TIMESTAMP。",
  function_des_timestamp_micros: "根據自 UTC epoch 以來的微秒數建立時間戳記。",
  function_des_timestamp_millis: "根據自 UTC epoch 以來的毫秒數建立時間戳記。",
  function_des_timestamp_seconds: "根據自 UTC epoch 以來的秒數（可以是小數）建立時間戳記。",
  function_des_to_date: "將 expr 轉換為日期。",
  function_des_to_timestamp: "將 expr 強制轉換為時間戳記。",
  function_des_to_unix_timestamp: "將 expr 的時間戳記轉為 UNIX 時間戳記。",
  function_des_to_utc_timestamp: "回傳以不同時區的 UTC 時間為基準的 expr。",
  function_des_trunc: "根據指定的格式模型 fmt，將日期的某部分截斷並回傳一個日期。",
  function_des_try_to_timestamp: "回傳將 timestamp_str 轉換為時間戳記的結果，可以選擇要轉換的格式，如果轉換失敗則回傳 NULL。",
  function_des_unix_date: "回傳自 1970-01-01 00:00:00 UTC 以來的天數。",
  function_des_unix_micros: "回傳自 1970-01-01 00:00:00 UTC 以來的微秒數。",
  function_des_unix_millis: "回傳自 1970-01-01 00:00:00 UTC 以來的毫秒數。會截斷高精度級別。",
  function_des_unix_seconds: "回傳自 1970-01-01 00:00:00 UTC 以來的秒數。會截斷高精度級別。",
  function_des_unix_timestamp: "回傳當前時間或指定時間的 UNIX 時間戳記。",
  function_des_weekday: "回傳 expr 是星期幾。",
  function_des_weekofyear: "回傳 expr 是該年度的第幾週。",
  function_des_year: "回傳 expr 的年份。",
  function_des_window: "將行劃分到一個或多個時間視窗中，根據指定的時間戳列。視窗的開始是包含的，但視窗的結束是不包含的，例如 12:05 將位於視窗[12:05,12:10)，但不在[12:00,12:05)視窗中。視窗可以支持微秒級別的精確度。不支持按月排序的視窗。",
  function_des_window_time: "從時間/會話視窗欄中提取時間值，該值可用於視窗的事件時間值。提取的時間是（window.end - 1），這反映了聚合視窗具有排他性上界的事實 - [start, end)。",
  function_des_boolean: "將 expr 強制轉換為 BOOLEAN。",
  function_des_cast: "將 expr 強制轉為目標資料類型。",
  function_des_decimal: "將 expr 強制轉為 DECIMAL。",
  function_des_named_struct: "建立具有指定的欄位名稱與值的結構。",
  function_des_smallint: "將 expr 強制轉為 SMALLINT。",
  function_des_struct: "建立具有指定欄位值的結構。",
  function_des_tinyint: "將 expr 強制轉為 TINYINT。",
  function_des_from_csv: "回傳具有 csvStr 和 schema 的結構值。",
  function_des_schema_of_csv: "回傳 DDL 格式的 CSV 字串的綱要。",
  function_des_to_csv: "回傳具有指定結構值的 CSV 字串。",
  function_des_from_json: "使用給定的 jsonStr 和格式回傳一個 STRUCT 值。",
  function_des_get_json_object: "從 path 擷取 JSON 物件。",
  function_des_json_array_length: "回傳最外層 JSON 陣列中的元素數量。",
  function_des_json_object_keys: "回傳最外層 JSON 物件的所有鍵作為一個陣列。",
  function_des_json_tuple: "以多元組形式回傳多個 JSON 物件。",
  function_des_schema_of_json: "回傳 DDL 格式的 JSON 字串的架構。",
  function_des_to_json: "回傳一個 JSON 字串，其中 expr 中指定了結構。",
  function_des_xpath: "回傳與 xpath 相符的 xml 節點中的值。",
  function_des_xpath_boolean: "如果 xpath 運算式的計算結果為 true，或者在 xml 中找到符合的節點，則回傳 true。",
  function_des_xpath_double: "從 XML 檔案回傳 DOUBLE 值。",
  function_des_xpath_float: "從 XML 檔案回傳 FLOAT 值。",
  function_des_xpath_int: "從 XML 檔案回傳 INTEGER 值。",
  function_des_xpath_long: "從 XML 檔案回傳 BIGINT 值。",
  function_des_xpath_number: "從 XML 檔案回傳 DOUBLE 值。",
  function_des_xpath_short: "從 XML 檔案回傳 SHORT 值。",
  function_des_xpath_string: "回傳與 XPath 運算式符合的第一個 XML 節點的內容。",
  function_des_assert_true: "如果 expr 不為 true，則回傳錯誤。",
  function_des_case: "回傳等於 expr 的第一個 optN 的 resN，如果沒有任何符合的項目，則回傳 def。",
  function_des_coalesce: "回傳第一個非 NULL 參數。",
  function_des_cube: "使用指定的表示式欄位建立多維度 cube。",
  function_des_current_catalog: "回傳當前目錄。",
  function_des_current_database: "回傳當前的資料庫。",
  function_des_current_schema: "回傳當前的綱要。",
  function_des_current_user: "當前執行上下文的使用者名稱。",
  function_des_elt: "回傳第 n 個運算式。",
  function_des_equal_null: "對於非 NULL 操作數，回傳與 EQUAL(=) 運算元相同的結果，但如果兩個操作數都為 NULL，則回傳 true，如果其中一個為 NULL，則回傳 false。",
  function_des_greatest: "回傳所有參數中的最大值（跳過NULL值）。",
  function_des_grouping: "指示 GROUP BY 中指定的欄是否已聚合，如果已聚合則傳回1，未聚合則傳回0。",
  function_des_grouping_id: "回傳一組欄位的群組層級。",
  function_des_hash: "回傳參數的雜湊值。",
  function_des_if: "如果 cond 為 true，則回傳 expr1，否則回傳 expr2。",
  function_des_ifnull: "如果 expr1 為 NULL，則回傳 expr2，否則回傳 expr1。",
  function_des_input_file_block_length: "回傳正在讀取的資料區塊的位元組長度。",
  function_des_input_file_block_start: "回傳正在讀取的資料區塊起始偏移位元組長度。",
  function_des_input_file_name: "回傳正在讀取的檔案的名稱。如果無法獲得該名稱，則回傳空字串。",
  function_des_isnotnull: "如果 expr 不為 NULL，則回傳 true。",
  function_des_isnull: "如果 expr 為 NULL，則回傳 true。",
  function_des_java_method: "使用反射呼叫某個方法。",
  function_des_least: "回傳所有參數中的最小值（跳過 null 值）。",
  function_des_monotonically_increasing_id: "回傳單調遞增的 64 位元整數。",
  function_des_nullif: "如果 expr1 等於 expr2，則回傳 NULL，否則回傳 expr1。",
  function_des_nvl: "如果 expr1 為NULL，則回傳 expr2，否則回傳 expr1。",
  function_des_nvl2: "如果 expr1 不為 NULL，則回傳 expr2，否則回傳 expr3。",
  function_des_raise_error: "使用 expr 拋出一個異常。",
  function_des_reflect: "使用反射呼叫某個方法。",
  function_des_stack: "將 expr1…exprN 分隔成 numRows 列。",
  function_des_spark_partition_id: "回傳當前分區的 ID。",
  function_des_typeof: "為輸入的資料類型回傳 DDL 格式的類型字串。",
  function_des_user: "當前執行上下文的使用者名稱。",
  function_des_uuid: "回傳全域唯一識別碼（UUID）字串。",
  function_des_version: "回傳 Apache Spark 版本。",
  function_des_when: "當 expr1 = true 時，回傳 expr2；否則當 expr3 = true 時，回傳 expr4；否則回傳 expr5。",
  function_des_xxhash64: "回傳參數的 64 位元雜湊值。備註：使用此函式時，可能會因為結果值大於 JavaScript 中數值類型的最大值而導致精確度損失，而使預覽結果與實際結果不一致。",
};

export default zh_TW;
